(() => {
'use strict';
const SESSION_KEY='tarefasPushSession17', MUSIC_KEY='tarefasGamesMusic';
const user=JSON.parse(localStorage.getItem('usuarioLogado')||'null');
const $=id=>document.getElementById(id);
const picker=$('gamePicker'),stage=$('gameStage'),controls=$('gameControls'),startBtn=$('gameStart'),statusEl=$('gameStatus'),scoreEl=$('gameScore'),bestEl=$('gameBest'),rankEl=$('gameRank'),detailEl=$('gameDetail'),leaderboard=$('leaderboardList'),refreshBtn=$('leaderboardRefresh'),musicBtn=$('musicToggle');
const titleEl=$('gameTitle'),descEl=$('gameDescription'),kickerEl=$('gameKicker'),leaderTitle=$('leaderboardTitle'),versionLabel=$('gamesVersionLabel');
const GAMES={
 dino:{name:'Dinossauro',icon:'🦖',kicker:'CORRIDA',desc:'Toque na pista para saltar barreiras e cones.'},
 snake:{name:'Cobrinha',icon:'🐍',kicker:'ROTA TÁTICA',desc:'Faça a rota crescer sem bater nas bordas ou em você mesmo.'},
 memory:{name:'Memória',icon:'🧠',kicker:'MEMÓRIA',desc:'Encontre os oito pares no menor número de jogadas.'},
 game2048:{name:'2048',icon:'2048',kicker:'PUZZLE',desc:'Junte peças iguais e tente chegar ao 2048.'},
 minesweeper:{name:'Campo Minado',icon:'💣',kicker:'LÓGICA',desc:'Abra todas as casas seguras sem tocar nas minas.'},
 precision:{name:'Precisão',icon:'🎯',kicker:'30 SEGUNDOS',desc:'Acerte o máximo de alvos. Toques fora tiram pontos.'},
 reflex:{name:'Reflexo',icon:'⚡',kicker:'5 RODADAS',desc:'Toque somente quando o painel ficar verde.'},
 flight:{name:'Voo Infinito',icon:'✈️',kicker:'VOO',desc:'Toque para ganhar altitude e atravesse os corredores.'},
 hillclimb:{name:'Subida Infinita',icon:'🚙',kicker:'PATRULHA MEC',desc:'Acelere nas subidas, controle a descida e vá o mais longe possível.'}
};
let current='dino',runToken='',startedAt=0,busy=false,ending=false,cleanups=[],raf=0,timers=[],musicEnabled=localStorage.getItem(MUSIC_KEY)!=='0';
const session=()=>localStorage.getItem(SESSION_KEY)||'';
const fmt=n=>Number(n||0).toLocaleString('pt-BR');
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const rnd=(a,b)=>a+Math.random()*(b-a);
function setStatus(t,bad=false){statusEl.textContent=t;statusEl.classList.toggle('error',bad)}
function score(n){scoreEl.textContent=fmt(Math.max(0,Math.floor(Number(n)||0)))}
function detail(t){detailEl.textContent=t||'—'}
function friendly(e){const t=String(e?.message||e||'');if(t.includes('SESSAO'))return'Sua sessão expirou. Entre novamente no app.';if(t.includes('PARTIDA'))return'A partida não pôde ser validada. Jogue novamente.';if(t.includes('PONTUACAO')||t.includes('DURACAO')||t.includes('DETALHES'))return'O servidor recusou o resultado desta partida.';return'Não foi possível conectar ao placar agora.'}
function on(el,ev,fn,opt){el.addEventListener(ev,fn,opt);cleanups.push(()=>el.removeEventListener(ev,fn,opt))}
function later(fn,ms){const id=setTimeout(fn,ms);timers.push(id);return id}
function every(fn,ms){const id=setInterval(fn,ms);timers.push(id);return id}
function setLayout(v){stage.dataset.layout=v}

const AudioDirector=(()=>{
 let ctx=null,loopId=0,beat=0,key='';
 const themes={
  dino:{bpm:132,wave:'square',mel:[64,67,71,67,62,67,69,67],bass:[40,40,43,43]},
  snake:{bpm:112,wave:'triangle',mel:[57,60,64,67,64,60,55,60],bass:[33,36,31,36]},
  memory:{bpm:86,wave:'sine',mel:[60,64,67,72,67,64,62,67],bass:[36,41,38,43]},
  game2048:{bpm:100,wave:'triangle',mel:[55,62,65,69,62,65,60,67],bass:[31,38,36,43]},
  minesweeper:{bpm:92,wave:'sawtooth',mel:[52,55,59,55,50,55,57,54],bass:[28,31,26,30]},
  precision:{bpm:124,wave:'square',mel:[69,72,76,72,67,71,74,71],bass:[45,43,40,43]},
  reflex:{bpm:140,wave:'triangle',mel:[72,76,79,76,74,77,81,77],bass:[48,50,45,50]},
  flight:{bpm:108,wave:'sine',mel:[67,71,74,79,76,74,71,69],bass:[43,47,40,45]},
  hillclimb:{bpm:118,wave:'square',mel:[52,59,64,59,55,62,67,62],bass:[28,35,31,38]}
 };
 function ensure(){if(!ctx)ctx=new (window.AudioContext||window.webkitAudioContext)();return ctx}
 function freq(m){return 440*Math.pow(2,(m-69)/12)}
 function tone(midi,dur=.12,vol=.018,wave='sine',delay=0){if(!musicEnabled)return;try{const c=ensure(),o=c.createOscillator(),g=c.createGain(),t=c.currentTime+delay;o.type=wave;o.frequency.setValueAtTime(freq(midi),t);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(vol,t+.012);g.gain.exponentialRampToValueAtTime(.0001,t+dur);o.connect(g);g.connect(c.destination);o.start(t);o.stop(t+dur+.03)}catch{}}
 function tick(){const t=themes[key];if(!t||!musicEnabled)return;const note=t.mel[beat%t.mel.length];tone(note,.11,.014,t.wave);if(beat%2===0)tone(t.bass[(beat/2)%t.bass.length|0],.2,.01,'sine');if(beat%4===2)tone(note+12,.055,.005,'sine',.04);beat++}
 function stop(){if(loopId){clearInterval(loopId);loopId=0}beat=0}
 function start(game){stop();key=game;if(!musicEnabled)return;try{const c=ensure();c.resume?.()}catch{}const t=themes[game];if(!t)return;tick();loopId=setInterval(tick,60000/t.bpm/2)}
 function sfx(type){const map={jump:[76,83],point:[84,88],hit:[45,38],match:[72,79],go:[79,86],move:[60,64]};const a=map[type]||[70];a.forEach((m,i)=>tone(m,.08,.025,type==='hit'?'sawtooth':'triangle',i*.045))}
 return{start,stop,sfx};
})();
function updateMusicButton(){musicBtn.setAttribute('aria-pressed',String(musicEnabled));musicBtn.querySelector('span').textContent=musicEnabled?'🔊':'🔇';musicBtn.querySelector('small').textContent=musicEnabled?'MÚSICA':'MUDO'}
musicBtn.addEventListener('click',e=>{e.preventDefault();musicEnabled=!musicEnabled;localStorage.setItem(MUSIC_KEY,musicEnabled?'1':'0');updateMusicButton();if(busy){if(musicEnabled)AudioDirector.start(current);else AudioDirector.stop()}});
updateMusicButton();

function clearActive(){cancelAnimationFrame(raf);raf=0;timers.forEach(clearTimeout);timers.forEach(clearInterval);timers=[];cleanups.splice(0).forEach(fn=>{try{fn()}catch{}});AudioDirector.stop();runToken='';ending=false;busy=false;controls.replaceChildren()}
function message(icon,title,text){setLayout('canvas');stage.innerHTML=`<div class="game-message"><b>${icon}</b><strong>${title}</strong><span>${text}</span></div>`}
function button(text,fn,cls=''){const b=document.createElement('button');b.type='button';b.textContent=text;b.className=cls;b.addEventListener('click',e=>{e.preventDefault();fn(e)});b.addEventListener('contextmenu',e=>e.preventDefault());b.addEventListener('selectstart',e=>e.preventDefault());controls.appendChild(b);return b}
async function startRun(){if(!navigator.onLine)throw new Error('OFFLINE');if(!session())throw new Error('SESSAO_INVALIDA');const {data,error}=await supabaseClient.rpc('v1_9_8_start_game_run',{p_session_token:session(),p_game_key:current});if(error)throw error;if(!data)throw new Error('PARTIDA_INVALIDA');return data}
async function submitResult(value,details={},durationOverride=null){if(ending||!runToken)return;ending=true;AudioDirector.stop();const duration=durationOverride??Math.max(1000,Math.round(performance.now()-startedAt));startBtn.disabled=true;setStatus('Registrando sua pontuação…');try{const {data,error}=await supabaseClient.rpc('v1_9_8_submit_game_score',{p_session_token:session(),p_run_token:runToken,p_game_key:current,p_score:Math.max(0,Math.floor(value)),p_duration_ms:duration,p_details:details});if(error)throw error;bestEl.textContent=fmt(data?.personal_best??value);rankEl.textContent=data?.rank?`#${data.rank}`:'—';setStatus('Pontuação registrada!');await loadLeaderboard()}catch(e){setStatus(friendly(e),true)}finally{runToken='';busy=false;startBtn.disabled=false;startBtn.textContent='Jogar novamente'}}
function lost(text='Fim de jogo.'){AudioDirector.stop();busy=false;runToken='';startBtn.disabled=false;startBtn.textContent='Tentar novamente';setStatus(text,true)}
async function begin(){if(busy||ending)return;clearActive();busy=true;startBtn.disabled=true;startBtn.textContent='Preparando…';setStatus('Validando a partida com o servidor…');try{runToken=await startRun();startedAt=performance.now();startBtn.textContent='Em jogo…';setStatus('Partida válida iniciada.');AudioDirector.start(current);MODULES[current]()}catch(e){busy=false;runToken='';AudioDirector.stop();startBtn.disabled=false;startBtn.textContent='Tentar novamente';setStatus(e.message==='OFFLINE'?'Conecte-se à internet para jogar com placar.':friendly(e),true)}}
function selectGame(key,source){if(!GAMES[key]||key===current&&stage.children.length)return;clearActive();current=key;picker.querySelectorAll('[data-game]').forEach(b=>b.classList.toggle('active',b.dataset.game===key));source?.scrollIntoView?.({behavior:'smooth',block:'nearest',inline:'center'});const g=GAMES[key];titleEl.textContent=g.name;descEl.textContent=g.desc;kickerEl.textContent=g.kicker;leaderTitle.textContent=g.name;score(0);detail('—');bestEl.textContent='—';rankEl.textContent='—';startBtn.disabled=false;startBtn.textContent='Jogar';setStatus('Toque em Jogar para iniciar uma partida válida.');message(g.icon,g.name,g.desc);loadLeaderboard()}

function rr(x,cx,cy,w,h,r,fill,stroke){x.beginPath();x.roundRect?x.roundRect(cx,cy,w,h,r):(x.rect(cx,cy,w,h));if(fill){x.fillStyle=fill;x.fill()}if(stroke){x.strokeStyle=stroke;x.stroke()}}
function canvasBase(){setLayout('canvas');stage.replaceChildren();const c=document.createElement('canvas');c.setAttribute('aria-label',GAMES[current].name);stage.appendChild(c);const ctx=c.getContext('2d');let w=0,h=0,dpr=1;function resize(){const r=stage.getBoundingClientRect(),cr=c.getBoundingClientRect();dpr=Math.min(devicePixelRatio||1,2);w=Math.max(300,Math.round(r.width));h=Math.max(270,Math.round(cr.height||r.height));c.width=Math.round(w*dpr);c.height=Math.round(h*dpr);ctx.setTransform(dpr,0,0,dpr,0,0)}resize();on(window,'resize',resize,{passive:true});on(c,'contextmenu',e=>e.preventDefault());on(c,'selectstart',e=>e.preventDefault());return{c,ctx,get w(){return w},get h(){return h}}}
function sky(x,w,h,t=0){const g=x.createLinearGradient(0,0,0,h);g.addColorStop(0,'#dff4ff');g.addColorStop(.65,'#d8f3e7');g.addColorStop(1,'#b3dbc8');x.fillStyle=g;x.fillRect(0,0,w,h);x.globalAlpha=.25;x.fillStyle='#fff';for(let i=0;i<4;i++){const px=(w*(.12+i*.29)-t*(8+i*2))%(w+120);x.beginPath();x.arc(px,50+i%2*35,28,0,Math.PI*2);x.arc(px+30,45+i%2*35,20,0,Math.PI*2);x.fill()}x.globalAlpha=1}
function drawShield(x,cx,cy,s=1){x.save();x.translate(cx,cy);x.scale(s,s);x.beginPath();x.moveTo(0,-12);x.lineTo(11,-7);x.lineTo(9,6);x.quadraticCurveTo(0,16,-9,6);x.lineTo(-11,-7);x.closePath();x.fillStyle='#0e563e';x.fill();x.strokeStyle='#8de1ba';x.lineWidth=1.5;x.stroke();x.fillStyle='#c9f4df';x.font='900 8px system-ui';x.textAlign='center';x.fillText('26',0,3);x.restore()}
function drawPatrol(x,cx,cy,ang=0,s=1){x.save();x.translate(cx,cy);x.rotate(ang);x.scale(s,s);x.fillStyle='#101d18';x.beginPath();x.arc(-21,12,10,0,Math.PI*2);x.arc(23,12,10,0,Math.PI*2);x.fill();x.fillStyle='#526d3f';rr(x,-31,-8,66,23,6,'#526d3f');x.fillStyle='#73915a';x.beginPath();x.moveTo(-10,-8);x.lineTo(2,-25);x.lineTo(26,-25);x.lineTo(34,-8);x.closePath();x.fill();x.fillStyle='#b9d8d0';x.fillRect(4,-21,12,11);x.fillRect(18,-21,8,11);x.fillStyle='#1e3128';x.fillRect(-27,-3,13,5);x.fillStyle='#f2ca54';x.fillRect(29,-4,5,4);x.fillStyle='#2e82b8';x.fillRect(7,-29,9,4);drawShield(x,-2,1,.55);x.restore()}
function drawDino(x,cx,cy,s=1,step=0){x.save();x.translate(cx,cy);x.scale(s,s);x.fillStyle='#537e31';rr(x,-14,-20,31,24,7,'#537e31');rr(x,7,-31,27,18,6,'#648f38');x.beginPath();x.moveTo(-13,-13);x.lineTo(-35,-5);x.lineTo(-13,0);x.closePath();x.fill();x.fillStyle='#e8f2b7';x.fillRect(24,-27,4,4);x.fillStyle='#172116';x.fillRect(26,-27,2,2);x.fillStyle='#405f28';x.fillRect(30,-19,10,3);x.fillStyle='#537e31';const a=Math.sin(step)>0?1:-1;x.fillRect(-8,2,7,15+(a>0?4:0));x.fillRect(9,2,7,15+(a<0?4:0));x.restore()}
function barrier(x,cx,ground,w=32,h=34){x.save();x.translate(cx,ground-h);x.fillStyle='#e6b83f';rr(x,0,8,w,h-8,4,'#e6b83f');x.fillStyle='#f9f1d2';x.save();x.beginPath();x.rect(0,8,w,h-8);x.clip();x.rotate(-.55);for(let i=-30;i<60;i+=16)x.fillRect(i,0,7,70);x.restore();x.fillStyle='#35463d';x.fillRect(4,h-2,w-8,4);x.restore()}

function dino(){const v=canvasBase(),d={x:68,y:0,vy:0,w:44,h:48,on:true},obs=[];let ground=v.h-44,dist=0,last=performance.now(),spawn=1,step=0;function jump(){if(d.on){d.vy=-700;d.on=false;AudioDirector.sfx('jump')}}let tapX=0,tapY=0;on(v.c,'pointerdown',e=>{tapX=e.clientX;tapY=e.clientY},{passive:true});on(v.c,'pointerup',e=>{if(Math.hypot(e.clientX-tapX,e.clientY-tapY)<18)jump()},{passive:true});on(window,'keydown',e=>{if(e.code==='Space'||e.code==='ArrowUp'){e.preventDefault();jump()}});function loop(now){if(!busy)return;const dt=Math.min(.032,(now-last)/1000);last=now;ground=v.h-44;const sp=Math.min(640,330+dist/155);dist+=sp*dt;step+=dt*13;const sc=Math.floor(dist/10);score(sc);detail((sp/330).toLocaleString('pt-BR',{maximumFractionDigits:1})+'×');d.vy+=1800*dt;d.y+=d.vy*dt;if(d.y>=ground-d.h){d.y=ground-d.h;d.vy=0;d.on=true}spawn-=dt;if(spawn<=0){obs.push({x:v.w+30,w:rnd(30,42),h:rnd(30,46)});spawn=.82+rnd(0,.58)}obs.forEach(o=>o.x-=sp*dt);while(obs[0]&&obs[0].x+obs[0].w<0)obs.shift();if(obs.some(o=>d.x+5<o.x+o.w&&d.x+d.w-5>o.x&&d.y+7<ground&&d.y+d.h>ground-o.h+3)){busy=false;AudioDirector.sfx('hit');submitResult(sc,{distance:Math.floor(dist)});return}const x=v.ctx;sky(x,v.w,v.h,dist/90);x.fillStyle='#789b62';x.beginPath();x.moveTo(0,ground);for(let px=0;px<=v.w;px+=30)x.lineTo(px,ground-10-Math.sin((px+dist/4)/70)*7);x.lineTo(v.w,v.h);x.lineTo(0,v.h);x.fill();x.fillStyle='#385640';x.fillRect(0,ground,v.w,v.h-ground);x.fillStyle='#cad7b5';for(let px=-(dist%50);px<v.w;px+=50)x.fillRect(px,ground+18,27,3);obs.forEach(o=>barrier(x,o.x,ground,o.w,o.h));drawDino(x,d.x+22,d.y+31,1,step);raf=requestAnimationFrame(loop)}d.y=ground-d.h;raf=requestAnimationFrame(loop)}

function snake(){const v=canvasBase(),N=18;let body=[{x:8,y:9},{x:7,y:9},{x:6,y:9}],dir={x:1,y:0},next=dir,food={x:13,y:9},foods=0,last=0;function place(){do{food={x:Math.floor(Math.random()*N),y:Math.floor(Math.random()*N)}}while(body.some(p=>p.x===food.x&&p.y===food.y))}function turn(x,y){if(x!==-dir.x||y!==-dir.y)next={x,y}}button('↑',()=>turn(0,-1));button('←',()=>turn(-1,0));button('↓',()=>turn(0,1));button('→',()=>turn(1,0));on(window,'keydown',e=>{const m={ArrowUp:[0,-1],ArrowDown:[0,1],ArrowLeft:[-1,0],ArrowRight:[1,0]}[e.key];if(m){e.preventDefault();turn(...m)}});let sx=0,sy=0;if(window.__TAREFAS_NATIVE_APP__){on(v.c,'pointerdown',e=>{e.preventDefault();sx=e.clientX;sy=e.clientY},{passive:false});on(v.c,'pointerup',e=>{const dx=e.clientX-sx,dy=e.clientY-sy;if(Math.max(Math.abs(dx),Math.abs(dy))<18)return;if(Math.abs(dx)>Math.abs(dy))turn(Math.sign(dx),0);else turn(0,Math.sign(dy))})}function draw(){const cell=Math.min(v.w-20,v.h-20)/N,ox=(v.w-cell*N)/2,oy=(v.h-cell*N)/2,x=v.ctx;x.fillStyle='#dceee5';x.fillRect(0,0,v.w,v.h);x.strokeStyle='#46725e22';x.lineWidth=1;for(let i=0;i<=N;i++){x.beginPath();x.moveTo(ox+i*cell,oy);x.lineTo(ox+i*cell,oy+cell*N);x.stroke();x.beginPath();x.moveTo(ox,oy+i*cell);x.lineTo(ox+cell*N,oy+i*cell);x.stroke()}x.fillStyle='#e1b846';x.beginPath();x.arc(ox+(food.x+.5)*cell,oy+(food.y+.5)*cell,cell*.34,0,Math.PI*2);x.fill();x.fillStyle='#143d2e';body.forEach((p,i)=>{const cx=ox+(p.x+.5)*cell,cy=oy+(p.y+.5)*cell;x.fillStyle=i?'#2d7f5e':'#153f30';x.beginPath();x.arc(cx,cy,cell*.42,0,Math.PI*2);x.fill();if(i===0){x.fillStyle='#d8f7e8';x.beginPath();x.arc(cx+cell*.14,cy-cell*.12,cell*.07,0,Math.PI*2);x.fill()}});detail(`${body.length} segmentos`)}function loop(now){if(!busy)return;if(now-last>118){last=now;dir=next;const h={x:body[0].x+dir.x,y:body[0].y+dir.y};if(h.x<0||h.y<0||h.x>=N||h.y>=N||body.some(p=>p.x===h.x&&p.y===h.y)){busy=false;AudioDirector.sfx('hit');submitResult(foods*100,{food:foods});return}body.unshift(h);if(h.x===food.x&&h.y===food.y){foods++;score(foods*100);AudioDirector.sfx('point');place()}else body.pop();draw()}raf=requestAnimationFrame(loop)}draw();raf=requestAnimationFrame(loop)}

function memory(){setLayout('grid');const icons=['🚓','🪖','📻','🧭','🔦','🚧','🛡️','🎖️'];let deck=[...icons,...icons].sort(()=>Math.random()-.5),open=[],done=new Set(),moves=0;stage.innerHTML='<div class="tm-memory-grid"></div>';const grid=stage.firstElementChild;deck.forEach((val,i)=>{const b=document.createElement('button');b.className='tm-memory-card';b.type='button';b.textContent=val;b.addEventListener('contextmenu',e=>e.preventDefault());b.onclick=()=>flip(i,b,val);grid.appendChild(b)});function flip(i,b,val){if(!busy||done.has(i)||open.some(x=>x.i===i)||open.length===2)return;b.classList.add('open');open.push({i,b,val});if(open.length===2){moves++;detail(`${moves} jogadas`);const [a,c]=open;if(a.val===c.val){done.add(a.i);done.add(c.i);a.b.classList.add('done');c.b.classList.add('done');AudioDirector.sfx('match');open=[];if(done.size===16){busy=false;const dur=Math.max(1000,Math.round(performance.now()-startedAt)),sc=Math.max(100,20000-Math.floor(dur/10)-moves*120);score(sc);submitResult(sc,{moves,completed:true},dur)}}else later(()=>{a.b.classList.remove('open');c.b.classList.remove('open');open=[]},650)}}}

function game2048(){setLayout('grid');let board=Array(16).fill(0),moves=0,points=0;function add(){const e=board.map((v,i)=>v?null:i).filter(v=>v!==null);if(!e.length)return;board[e[Math.floor(Math.random()*e.length)]]=Math.random()<.9?2:4}function render(){stage.innerHTML='<div class="tm-2048-grid"></div>';const g=stage.firstElementChild;board.forEach(v=>{const c=document.createElement('div');c.className='tm-2048-cell';c.dataset.v=v;c.textContent=v||'';g.appendChild(c)});score(points);detail(`${moves} mov. · maior ${Math.max(...board)}`)}function line(a){const z=a.filter(Boolean),out=[];for(let i=0;i<z.length;i++){if(z[i]===z[i+1]){const n=z[i]*2;out.push(n);points+=n;i++}else out.push(z[i])}while(out.length<4)out.push(0);return out}function move(dx,dy){if(!busy)return;const old=board.join(','),nb=Array(16).fill(0);if(dx){for(let r=0;r<4;r++){let l=[0,1,2,3].map(c=>board[r*4+c]);if(dx>0)l.reverse();l=line(l);if(dx>0)l.reverse();l.forEach((v,c)=>nb[r*4+c]=v)}}else{for(let c=0;c<4;c++){let l=[0,1,2,3].map(r=>board[r*4+c]);if(dy>0)l.reverse();l=line(l);if(dy>0)l.reverse();l.forEach((v,r)=>nb[r*4+c]=v)}}board=nb;if(board.join(',')!==old){moves++;AudioDirector.sfx('move');add();render();if(!canMove())finish2048()}}function canMove(){if(board.some(v=>!v))return true;for(let r=0;r<4;r++)for(let c=0;c<4;c++){const v=board[r*4+c];if((c<3&&v===board[r*4+c+1])||(r<3&&v===board[(r+1)*4+c]))return true}return false}function finish2048(){if(!busy||moves<1)return;busy=false;submitResult(points,{moves,highest_tile:Math.max(...board)})}button('←',()=>move(-1,0));button('↑',()=>move(0,-1));button('↓',()=>move(0,1));button('→',()=>move(1,0));button('Finalizar',finish2048,'primary wide');on(window,'keydown',e=>{const m={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]}[e.key];if(m){e.preventDefault();move(...m)}});let sx=0,sy=0;if(window.__TAREFAS_NATIVE_APP__){on(stage,'pointerdown',e=>{e.preventDefault();sx=e.clientX;sy=e.clientY},{passive:false});on(stage,'pointerup',e=>{const x=e.clientX-sx,y=e.clientY-sy;if(Math.max(Math.abs(x),Math.abs(y))<25)return;if(Math.abs(x)>Math.abs(y))move(Math.sign(x),0);else move(0,Math.sign(y))})}add();add();render()}

function minesweeper(){setLayout('grid');const N=9,M=10,mines=new Set();while(mines.size<M)mines.add(Math.floor(Math.random()*N*N));const open=new Set();stage.innerHTML='<div class="tm-mine-grid"></div>';const grid=stage.firstElementChild,cells=[];for(let i=0;i<N*N;i++){const b=document.createElement('button');b.type='button';b.className='tm-mine-cell';b.onclick=()=>reveal(i);b.addEventListener('contextmenu',e=>e.preventDefault());cells.push(b);grid.appendChild(b)}function around(i){const r=Math.floor(i/N),c=i%N,a=[];for(let y=-1;y<=1;y++)for(let x=-1;x<=1;x++){const rr=r+y,cc=c+x;if((x||y)&&rr>=0&&cc>=0&&rr<N&&cc<N)a.push(rr*N+cc)}return a}function reveal(i){if(!busy||open.has(i))return;if(mines.has(i)){cells[i].classList.add('mine');cells[i].textContent='💣';mines.forEach(m=>{cells[m].textContent='💣';cells[m].classList.add('mine')});AudioDirector.sfx('hit');lost('Você encontrou uma mina. Tente novamente.');return}const q=[i];while(q.length){const n=q.shift();if(open.has(n)||mines.has(n))continue;open.add(n);const near=around(n),count=near.filter(x=>mines.has(x)).length;cells[n].classList.add('open');cells[n].textContent=count||'';if(!count)near.forEach(x=>{if(!open.has(x))q.push(x)})}detail(`${open.size}/71 abertas`);if(open.size>=71){busy=false;AudioDirector.sfx('match');const dur=Math.max(1000,Math.round(performance.now()-startedAt)),sc=Math.max(100,15000-Math.floor(dur/10));score(sc);submitResult(sc,{revealed:open.size,completed:true},dur)}}detail('0/71 abertas')}

function precision(){setLayout('panel');stage.innerHTML='<div class="tm-precision-area"><button class="tm-target" type="button" aria-label="Alvo"></button></div>';const area=stage.firstElementChild,target=area.firstElementChild;let hits=0,misses=0,left=30;function place(){const r=area.getBoundingClientRect(),s=60;target.style.left=rnd(8,Math.max(9,r.width-s-8))+'px';target.style.top=rnd(8,Math.max(9,r.height-s-8))+'px'}target.onclick=e=>{e.stopPropagation();e.preventDefault();if(!busy)return;hits++;AudioDirector.sfx('point');place();score(Math.max(0,hits*100-misses*25));detail(`${hits} acertos · ${misses} erros`)};area.onclick=e=>{if(e.target===target||!busy)return;misses++;score(Math.max(0,hits*100-misses*25));detail(`${hits} acertos · ${misses} erros`)};place();const id=every(()=>{left--;setStatus(`Acerte os alvos — ${left}s restantes.`);if(left<=0){clearInterval(id);busy=false;submitResult(Math.max(0,hits*100-misses*25),{hits,misses})}},1000);detail('0 acertos · 0 erros')}

function reflex(){setLayout('panel');stage.innerHTML='<div class="tm-reflex-pad">Prepare-se<small>Toque quando o painel ficar verde.</small></div>';const pad=stage.firstElementChild;let round=0,ready=false,locked=false,goAt=0,values=[];function next(){if(round>=5){const avg=Math.round(values.reduce((a,b)=>a+b,0)/5),sc=Math.max(100,10000-avg*10);score(sc);detail(`${avg} ms`);busy=false;submitResult(sc,{rounds:5,average_ms:avg});return}round++;ready=false;locked=false;pad.className='tm-reflex-pad wait';pad.innerHTML=`Rodada ${round}/5<small>Espere o verde…</small>`;later(()=>{if(!busy)return;ready=true;locked=false;goAt=performance.now();pad.className='tm-reflex-pad go';pad.innerHTML='AGORA!<small>Toque!</small>';AudioDirector.sfx('go')},900+Math.random()*1500)}pad.onclick=()=>{if(!busy||locked)return;locked=true;if(!ready){values.push(3000);pad.className='tm-reflex-pad early';pad.innerHTML='Muito cedo!<small>Penalidade: 3000 ms</small>';later(next,650)}else{ready=false;const ms=clamp(Math.round(performance.now()-goAt),80,3000);values.push(ms);pad.className='tm-reflex-pad';pad.innerHTML=`${ms} ms<small>Próxima rodada…</small>`;later(next,650)}};next()}

function flight(){const v=canvasBase();let craft={x:82,y:v.h/2,vy:0},gates=[],spawn=1.3,dist=0,last=performance.now();function flap(){craft.vy=-370;AudioDirector.sfx('jump')}let flapX=0,flapY=0;on(v.c,'pointerdown',e=>{flapX=e.clientX;flapY=e.clientY},{passive:true});on(v.c,'pointerup',e=>{if(Math.hypot(e.clientX-flapX,e.clientY-flapY)<18)flap()},{passive:true});on(window,'keydown',e=>{if(e.code==='Space'||e.code==='ArrowUp'){e.preventDefault();flap()}});function drawPlane(x,cx,cy,tilt){x.save();x.translate(cx,cy);x.rotate(tilt);x.fillStyle='#445d4e';x.beginPath();x.moveTo(-23,0);x.lineTo(18,-7);x.lineTo(28,0);x.lineTo(18,7);x.closePath();x.fill();x.fillStyle='#789765';x.beginPath();x.moveTo(-5,-3);x.lineTo(7,-22);x.lineTo(14,-20);x.lineTo(8,-2);x.closePath();x.fill();x.beginPath();x.moveTo(-4,3);x.lineTo(8,22);x.lineTo(15,20);x.lineTo(8,2);x.closePath();x.fill();x.fillStyle='#2c83b0';x.fillRect(-20,-3,8,3);x.restore()}function loop(now){if(!busy)return;const dt=Math.min(.032,(now-last)/1000);last=now;dist+=82*dt;score(Math.floor(dist));detail(`${Math.floor(dist)} m`);craft.vy+=980*dt;craft.y+=craft.vy*dt;spawn-=dt;if(spawn<=0){const gap=116,y=rnd(58,Math.max(60,v.h-gap-58));gates.push({x:v.w+25,y,gap,w:50});spawn=1.45}gates.forEach(p=>p.x-=150*dt);while(gates[0]&&gates[0].x<-70)gates.shift();const hit=craft.y<8||craft.y+26>v.h-8||gates.some(p=>craft.x+25>p.x&&craft.x-20<p.x+p.w&&(craft.y-12<p.y||craft.y+12>p.y+p.gap));if(hit){busy=false;AudioDirector.sfx('hit');submitResult(Math.floor(dist),{distance:Math.floor(dist)});return}const x=v.ctx;sky(x,v.w,v.h,dist/20);x.fillStyle='#526f5e';gates.forEach(p=>{rr(x,p.x,0,p.w,p.y,7,'#526f5e');rr(x,p.x,p.y+p.gap,p.w,v.h,7,'#526f5e');x.fillStyle='#e7c34e';x.fillRect(p.x,p.y-5,p.w,5);x.fillRect(p.x,p.y+p.gap,p.w,5)});drawPlane(x,craft.x,craft.y,clamp(craft.vy/900,-.35,.5));raf=requestAnimationFrame(loop)}raf=requestAnimationFrame(loop)}

function hillclimb(){const v=canvasBase();let dist=0,speedV=0,fuel=42,last=performance.now(),gas=false,brake=false;const gasBtn=button('ACELERAR',()=>{},'primary wide hold'),brakeBtn=button('FREIO',()=>{},'wide hold');function hold(btn,set){const down=e=>{e.preventDefault();try{btn.setPointerCapture(e.pointerId)}catch{}set(true);btn.classList.add('active')},up=e=>{e?.preventDefault?.();set(false);btn.classList.remove('active')};on(btn,'pointerdown',down,{passive:false});on(btn,'pointerup',up,{passive:false});on(btn,'pointercancel',up,{passive:false});on(btn,'lostpointercapture',up);on(btn,'contextmenu',e=>e.preventDefault());on(btn,'selectstart',e=>e.preventDefault())}hold(gasBtn,x=>gas=x);hold(brakeBtn,x=>brake=x);on(window,'keydown',e=>{if(e.key==='ArrowRight'){e.preventDefault();gas=true;gasBtn.classList.add('active')}if(e.key==='ArrowLeft'){e.preventDefault();brake=true;brakeBtn.classList.add('active')}});on(window,'keyup',e=>{if(e.key==='ArrowRight'){gas=false;gasBtn.classList.remove('active')}if(e.key==='ArrowLeft'){brake=false;brakeBtn.classList.remove('active')}});function terrain(wx){return v.h*.70+Math.sin(wx/92)*36+Math.sin(wx/41)*10+Math.sin(wx/240)*18}function loop(now){if(!busy)return;const dt=Math.min(.032,(now-last)/1000);last=now;fuel-=dt;const slope=(terrain(dist+8)-terrain(dist-8))/16;if(gas)speedV+=132*dt;if(brake)speedV-=190*dt;speedV-=slope*58*dt;speedV-=20*dt;speedV=clamp(speedV,0,150);dist+=speedV*dt;score(Math.floor(dist));detail(`${Math.ceil(Math.max(0,fuel))}s combustível`);if(fuel<=0){busy=false;submitResult(Math.floor(dist),{distance:Math.floor(dist)});return}const x=v.ctx;sky(x,v.w,v.h,dist/45);x.fillStyle='#7fa168';x.globalAlpha=.6;x.beginPath();x.moveTo(0,v.h);for(let px=0;px<=v.w;px+=8){const wx=dist-v.w*.25+px;x.lineTo(px,terrain(wx)-44-Math.sin(wx/180)*20)}x.lineTo(v.w,v.h);x.closePath();x.fill();x.globalAlpha=1;x.beginPath();x.moveTo(0,v.h);for(let px=0;px<=v.w;px+=5){const wx=dist-v.w*.25+px;x.lineTo(px,terrain(wx))}x.lineTo(v.w,v.h);x.closePath();x.fillStyle='#6bb06f';x.fill();x.strokeStyle='#355c3c';x.lineWidth=4;x.stroke();const cx=v.w*.25,cy=terrain(dist)-24,ang=Math.atan((terrain(dist+8)-terrain(dist-8))/16);drawPatrol(x,cx,cy,ang,1.05);x.fillStyle='#183529aa';rr(x,12,12,116,32,12,'#183529aa');x.fillStyle='#eaf8ef';x.font='800 12px system-ui';x.fillText(`26 PEL · ${Math.floor(dist)} m`,24,32);raf=requestAnimationFrame(loop)}raf=requestAnimationFrame(loop)}

const MODULES={dino,snake,memory,game2048,minesweeper,precision,reflex,flight,hillclimb};
function formatDate(v){try{return v?new Date(v).toLocaleDateString('pt-BR',{day:'2-digit',month:'short'}):'Agora'}catch{return'—'}}
function renderLeaderboard(rows){leaderboard.replaceChildren();let mine=null;if(!rows.length){leaderboard.innerHTML='<div class="tm-leaderboard-empty">Ainda não há pontuações. Seja o primeiro!</div>';bestEl.textContent='0';rankEl.textContent='—';return}rows.forEach(row=>{if(String(row.usuario_id)===String(user?.id))mine=row;const pos=Number(row.ranking),item=document.createElement('div');item.className=`tm-leaderboard-row top-${Math.min(pos,4)}${String(row.usuario_id)===String(user?.id)?' me':''}`;const extra=current==='reflex'&&row.details?.average_ms?` · ${row.details.average_ms} ms`:'';item.innerHTML=`<div class="tm-leaderboard-place">${pos===1?'🥇':pos===2?'🥈':pos===3?'🥉':'#'+pos}</div><div class="tm-leaderboard-player"><strong></strong><small>${String(row.usuario_id)===String(user?.id)?'Você · ':''}${formatDate(row.achieved_at)}${extra}</small></div><div class="tm-leaderboard-points"><strong>${fmt(row.score)}</strong><small>PONTOS</small></div>`;item.querySelector('.tm-leaderboard-player strong').textContent=row.jogador||'Jogador';leaderboard.appendChild(item)});bestEl.textContent=mine?fmt(mine.score):'0';rankEl.textContent=mine?`#${mine.ranking}`:'—'}
async function loadLeaderboard(){const key=current;refreshBtn.disabled=true;refreshBtn.classList.add('loading');try{const {data,error}=await supabaseClient.rpc('v1_9_8_games_leaderboard',{p_game_key:key,p_limit:50});if(error)throw error;if(key===current)renderLeaderboard(Array.isArray(data)?data:[])}catch{if(key===current)leaderboard.innerHTML='<div class="tm-leaderboard-empty">Não foi possível carregar o placar.</div>'}finally{refreshBtn.disabled=false;refreshBtn.classList.remove('loading')}}
picker.addEventListener('click',e=>{const b=e.target.closest('[data-game]');if(b)selectGame(b.dataset.game,b)});startBtn.addEventListener('click',begin);refreshBtn.addEventListener('click',loadLeaderboard);document.addEventListener('visibilitychange',()=>{if(document.hidden&&busy){clearActive();startBtn.disabled=false;startBtn.textContent='Recomeçar';setStatus('Partida encerrada ao sair da tela.')}});document.addEventListener('contextmenu',e=>{if(e.target.closest('.tm-game-controls,.tm-game-stage,.tm-games-picker'))e.preventDefault()});
versionLabel.textContent=(window.__TAREFAS_NATIVE_APP__?'APP 2.0.0':'WEB 7.6.2')+' · 26º PEL PE MEC';
selectGame('dino');
})();