(()=>{
'use strict';
if(window.__TAREFAS_LAV_PAG_V767__)return;
window.__TAREFAS_LAV_PAG_V767__=true;
const VERSION='7.6.7';
const $=id=>document.getElementById(id);
const money=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v)||0);
const num=v=>Number(String(v??0).replace(',','.'))||0;
let busy=false,lastId=null;
function client(){try{return typeof supabaseClient!=='undefined'?supabaseClient:null}catch(_){return null}}
function currentUser(){try{return JSON.parse(localStorage.getItem('usuarioLogado')||'null')}catch(_){return null}}
function selectedId(){const q=new URLSearchParams(location.search).get('lavagem');if(q)return Number(q)||null;const h=$('lavDetail')?.querySelector('h3')?.textContent||'';const m=h.match(/#(\d+)/);return m?Number(m[1]):null}
function toast(msg,bad=false){const el=$('lavToast');if(!el)return;el.textContent=msg;el.classList.toggle('bad',bad);el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2800)}
function style(){if($('lavPagV767Style'))return;const s=document.createElement('style');s.id='lavPagV767Style';s.textContent=`
.lav-fin-cards{grid-template-columns:repeat(auto-fit,minmax(165px,1fr))!important}.lav-fin-card.cia strong{color:#7dd3fc}.lav-fin-card.total{border-color:#a78bfa}.lav-fin-card.total strong{color:#c4b5fd}
.lav-pay-box{margin-top:12px;padding:13px;border:1px solid #315d4c;border-radius:13px;background:#0a2019}.lav-pay-box h4{margin:0 0 5px}.lav-pay-box>p{margin:0 0 10px;color:#9fb7ad;font-size:10px;line-height:1.45}.lav-pay-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:7px}.lav-pay-stat{border:1px solid #29483d;border-radius:10px;padding:9px;background:#081a14}.lav-pay-stat small{display:block;color:#8ea99e;font-size:8px;font-weight:900}.lav-pay-stat strong{display:block;margin-top:3px;font-size:15px}.lav-pay-controls{display:grid;grid-template-columns:minmax(180px,1fr) auto auto;gap:7px;align-items:end;margin-top:10px}.lav-pay-controls label{font-size:9px;color:#a9c0b6;font-weight:800}.lav-pay-controls input{width:100%;margin-top:4px;padding:10px;border:1px solid #315d4c;border-radius:10px;background:#06150f;color:#fff}.lav-pay-note{margin-top:8px;font-size:9px;color:#9fb7ad}.lav-cia-use-note{display:block!important;margin-top:5px!important;color:#7dd3fc!important;font-size:9px!important}
@media(max-width:720px){.lav-pay-grid{grid-template-columns:1fr}.lav-pay-controls{grid-template-columns:1fr}.lav-fin-cards{grid-template-columns:1fr 1fr!important}.lav-fin-card.total{grid-column:1/-1}}
`;document.head.appendChild(s)}
function ensureFinanceCards(){const cards=$('lavFinV212')?.querySelector('.lav-fin-cards');if(!cards)return null;let cia=$('lavFinCia');if(!cia){cia=document.createElement('div');cia.className='lav-fin-card cia';cia.innerHTML='<small>DÉBITO CIA COM DISPONÍVEL</small><strong id="lavFinCiaValue">R$ 0,00</strong>';cards.appendChild(cia)}let total=$('lavFinTotal');if(!total){total=document.createElement('div');total.className='lav-fin-card total';total.id='lavFinTotal';total.innerHTML='<small>TOTAL DISPONÍVEL (PE + CIA COM)</small><strong id="lavFinTotalValue">R$ 0,00</strong>';cards.appendChild(total)}return cards}
async function loadFinance(){const c=client();if(!c)return;ensureFinanceCards();const [pe,cia]=await Promise.all([c.from('lavanderia_financeiro_pe_resumo').select('*').single(),c.from('lavanderia_cia_com_resumo').select('*').single()]);if(pe.error||cia.error)return;const peSaldo=num(pe.data?.saldo),ciaDisp=num(cia.data?.disponivel);if($('lavFinCiaValue'))$('lavFinCiaValue').textContent=money(ciaDisp);if($('lavFinTotalValue'))$('lavFinTotalValue').textContent=money(peSaldo+ciaDisp);if($('lavDebtPending'))$('lavDebtPending').textContent=money(ciaDisp);}
async function enhanceDebtRows(){const c=client(),list=$('lavDebtList');if(!c||!list)return;const r=await c.from('lavanderia_debitos_cia_com').select('id,valor,valor_utilizado,status').order('id',{ascending:false});if(r.error)return;const rows=[...list.querySelectorAll('.lav-row')];(r.data||[]).forEach((d,i)=>{const row=rows[i];if(!row)return;row.querySelector('.lav-cia-use-note')?.remove();const used=num(d.valor_utilizado),avail=d.status==='pendente'?Math.max(0,num(d.valor)-used):0;if(used>0){const n=document.createElement('small');n.className='lav-cia-use-note';n.textContent=`Usado em lavagens: ${money(used)} · disponível: ${money(avail)}`;row.appendChild(n)}})}
function payHtml(total,ciaAvail,currentCia,status){const max=Math.min(total,ciaAvail+currentCia),pe=Math.max(0,total-currentCia);return `<div class="lav-pay-box" id="lavPayV767"><h4>💳 Origem do pagamento</h4><p>Você pode pagar a lavagem com o saldo do PE, usar o débito pendente da Cia Com, ou dividir entre os dois.</p><div class="lav-pay-grid"><div class="lav-pay-stat"><small>TOTAL DA LAVAGEM</small><strong>${money(total)}</strong></div><div class="lav-pay-stat"><small>CIA COM DISPONÍVEL</small><strong id="lavPayCiaAvail">${money(max)}</strong></div><div class="lav-pay-stat"><small>SAI DO SALDO PE</small><strong id="lavPayPePreview">${money(pe)}</strong></div></div><div class="lav-pay-controls"><label>Usar do débito da Cia Com<input id="lavPayCiaInput" type="number" min="0" max="${max.toFixed(2)}" step="0.01" value="${currentCia.toFixed(2)}"></label><button type="button" class="lav-btn" id="lavPayOnlyPe">Só PE</button><button type="button" class="lav-btn" id="lavPayMaxCia">Usar máximo Cia Com</button></div><div class="lav-actions"><button type="button" class="lav-btn primary" id="lavPaySave">Salvar forma de pagamento</button></div><div class="lav-pay-note">${status==='recebida'?'Esta lavagem já foi recebida. Alterar aqui reclassifica o lançamento do PE automaticamente.':'A divisão será aplicada quando a lavagem for marcada como recebida.'}</div></div>`}
async function loadPayment(){const c=client(),id=selectedId(),detail=$('lavDetail');if(!c||!id||!detail||detail.hidden)return;lastId=id;const [rr,pr,cr]=await Promise.all([c.from('lavanderia_solicitacoes').select('id,status,total_calculado,total_recebido_calculado,recebimento_conferido_em').eq('id',id).single(),c.from('lavanderia_pagamentos').select('*').eq('solicitacao_id',id).maybeSingle(),c.from('lavanderia_cia_com_resumo').select('*').single()]);if(rr.error||cr.error)return;const r=rr.data;if(!r.recebimento_conferido_em||!['enviada','recebida'].includes(r.status)){detail.querySelector('#lavPayV767')?.remove();return}const total=num(r.total_recebido_calculado??r.total_calculado),currentCia=num(pr.data?.valor_cia_com),ciaAvail=num(cr.data?.disponivel);let box=detail.querySelector('#lavPayV767');const html=payHtml(total,ciaAvail,currentCia,r.status);if(!box){const actions=detail.querySelector('.lav-actions');if(actions)actions.insertAdjacentHTML('beforebegin',html);else detail.insertAdjacentHTML('beforeend',html)}else box.outerHTML=html;box=detail.querySelector('#lavPayV767');const input=box.querySelector('#lavPayCiaInput'),preview=box.querySelector('#lavPayPePreview'),max=Math.min(total,ciaAvail+currentCia);const calc=()=>{let v=Math.max(0,Math.min(max,num(input.value)));input.value=v.toFixed(2);preview.textContent=money(total-v)};input.addEventListener('input',()=>{const v=Math.max(0,Math.min(max,num(input.value)));preview.textContent=money(total-v)});box.querySelector('#lavPayOnlyPe').onclick=()=>{input.value='0.00';calc()};box.querySelector('#lavPayMaxCia').onclick=()=>{input.value=max.toFixed(2);calc()};box.querySelector('#lavPaySave').onclick=()=>savePayment(id,input,total);}
async function savePayment(id,input,total){const c=client(),u=currentUser();if(!c||!u?.id)return toast('Usuário não identificado.',true);const btn=$('lavPaySave'),v=Math.max(0,Math.min(total,num(input.value)));if(btn){btn.disabled=true;btn.textContent='Salvando…'}try{const r=await c.rpc('v2_1_1_lavanderia_definir_pagamento',{p_solicitacao_id:id,p_valor_cia_com:v,p_usuario_id:Number(u.id),p_perfil_id:u.perfil_id?Number(u.perfil_id):null});if(r.error)throw r.error;toast(`Pagamento salvo: ${money(total-v)} PE + ${money(v)} Cia Com`);await Promise.all([loadFinance(),loadPayment(),enhanceDebtRows()])}catch(e){toast((e?.message||'Erro ao salvar pagamento.').replaceAll('_',' '),true)}finally{if(btn){btn.disabled=false;btn.textContent='Salvar forma de pagamento'}}}
async function sync(){if(busy)return;busy=true;try{style();await loadFinance();await enhanceDebtRows();await loadPayment();const chip=document.querySelector('#lavanderiaModule .lav-chip');if(chip&&chip.textContent.includes('WEB'))chip.textContent='ORÇAMENTÁRIO · WEB '+VERSION}finally{busy=false}}
function boot(){sync();document.addEventListener('click',e=>{if(e.target.closest('[data-orc-module="lavanderia"],[data-lav-id],[data-lav-tab],[data-lav-action]'))setTimeout(sync,300)});window.addEventListener('focus',sync);const obs=new MutationObserver(()=>{const id=selectedId();if(id!==lastId||!$('lavPayV767')||!$('lavFinCia'))setTimeout(sync,40)});obs.observe(document.body,{subtree:true,childList:true});setInterval(sync,15000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
