(()=>{
'use strict';
const money=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v)||0);
const dateBR=v=>v?new Date(String(v).slice(0,10)+'T12:00:00').toLocaleDateString('pt-BR'):'-';
let loading=false;
function style(){if(document.getElementById('lavFinV212Style'))return;const s=document.createElement('style');s.id='lavFinV212Style';s.textContent=`
.lav-fin-wrap{margin:0 0 12px}.lav-fin-cards{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.lav-fin-card{border:1px solid #29483d;border-radius:14px;padding:12px;background:linear-gradient(145deg,#0d271f,#081b15)}.lav-fin-card small{display:block;color:#8ea99e;font-size:8px;font-weight:900;letter-spacing:.1em}.lav-fin-card strong{display:block;margin-top:4px;font-size:20px;color:#effbf6}.lav-fin-card.saldo{border-color:#37d99c}.lav-fin-card.saldo strong{color:#3ce8a5}.lav-fin-card.gasto strong{color:#ffc777}.lav-fin-history{margin-top:8px;border:1px solid #24483b;border-radius:12px;background:#091c16;overflow:hidden}.lav-fin-history summary{cursor:pointer;padding:10px 12px;font-size:10px;font-weight:900;color:#b8cec5;user-select:none}.lav-fin-list{padding:0 10px 8px}.lav-fin-row{display:grid;grid-template-columns:auto minmax(0,1fr) auto;gap:8px;align-items:center;padding:8px 2px;border-top:1px solid #18362c;font-size:10px}.lav-fin-row span{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.lav-fin-row b.credit{color:#3ce8a5}.lav-fin-row b.debit{color:#ffc777}.lav-fin-empty{padding:10px;color:#8ea99e;font-size:10px;text-align:center}
@media(max-width:620px){.lav-fin-cards{grid-template-columns:1fr 1fr}.lav-fin-card.saldo{grid-column:1/-1}.lav-fin-card strong{font-size:18px}}
`;document.head.appendChild(s)}
function ensure(){const mod=document.getElementById('lavanderiaModule');if(!mod)return null;style();let box=document.getElementById('lavFinV212');if(!box){box=document.createElement('section');box.id='lavFinV212';box.className='lav-fin-wrap';box.innerHTML=`<div class="lav-fin-cards"><div class="lav-fin-card"><small>CRÉDITO / SALDO INFORMADO DO PE</small><strong id="lavFinCredit">R$ 0,00</strong></div><div class="lav-fin-card gasto"><small>GASTO EM LAVAGENS</small><strong id="lavFinDebit">R$ 0,00</strong></div><div class="lav-fin-card saldo"><small>SALDO DISPONÍVEL</small><strong id="lavFinBalance">R$ 0,00</strong></div></div><details class="lav-fin-history"><summary>💰 Movimentações do saldo</summary><div class="lav-fin-list" id="lavFinList"><div class="lav-fin-empty">Carregando…</div></div></details>`;const hero=mod.querySelector('.lav-hero');hero?.insertAdjacentElement('afterend',box)}return box}
function client(){try{return typeof supabaseClient!=='undefined'?supabaseClient:null}catch(_){return null}}
async function load(){const c=client();if(loading||!c)return;const box=ensure();if(!box)return;loading=true;try{const [rs,rm]=await Promise.all([c.from('lavanderia_financeiro_pe_resumo').select('*').single(),c.from('lavanderia_financeiro_pe').select('id,data_movimento,tipo,descricao,valor,solicitacao_id').order('data_movimento',{ascending:false}).order('id',{ascending:false}).limit(12)]);if(rs.error)throw rs.error;if(rm.error)throw rm.error;document.getElementById('lavFinCredit').textContent=money(rs.data?.creditos);document.getElementById('lavFinDebit').textContent=money(rs.data?.debitos);document.getElementById('lavFinBalance').textContent=money(rs.data?.saldo);const list=document.getElementById('lavFinList');const rows=rm.data||[];list.innerHTML=rows.length?rows.map(x=>`<div class="lav-fin-row"><small>${dateBR(x.data_movimento)}</small><span>${String(x.descricao||'Movimentação').replace(/[<>&]/g,'')}</span><b class="${String(x.tipo).includes('credito')?'credit':'debit'}">${String(x.tipo).includes('credito')?'+':'−'} ${money(x.valor)}</b></div>`).join(''):'<div class="lav-fin-empty">Nenhuma movimentação registrada.</div>'}catch(e){console.warn('[TAREFAS LAVANDERIA FINANCEIRO]',e)}finally{loading=false}}
function boot(){ensure();load();document.addEventListener('click',e=>{if(e.target.closest('[data-orc-module="lavanderia"]'))setTimeout(load,250);if(e.target.closest('[data-lav-action="receber"]'))setTimeout(load,1800)});window.addEventListener('focus',load);setInterval(()=>{const m=document.getElementById('lavanderiaModule');if(m&&!m.hidden)load()},20000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
