-- TAREFAS V7.7.0 — conferência, validade e pendências do Material Carga / Depósitos

alter table public.orc_documentos_carga
  add column if not exists conferido_por text,
  add column if not exists conferido_em timestamptz,
  add column if not exists motivo_atualizacao text;

update public.orc_documentos_carga
set conferido_por = coalesce(conferido_por, atualizado_por),
    conferido_em = coalesce(conferido_em, criado_em),
    motivo_atualizacao = coalesce(motivo_atualizacao, 'historico')
where conferido_por is null or conferido_em is null or motivo_atualizacao is null;

alter table public.orc_documentos_carga
  alter column conferido_por set not null,
  alter column conferido_em set default now(),
  alter column conferido_em set not null,
  alter column motivo_atualizacao set default 'manual',
  alter column motivo_atualizacao set not null;

create table if not exists public.orc_carga_pendencias (
  id bigint generated by default as identity primary key,
  tipo_referencia text not null check (tipo_referencia in ('dependencia','deposito')),
  referencia text not null,
  origem_tipo text not null,
  origem_id bigint,
  origem_numero text,
  descricao text,
  status text not null default 'pendente' check (status in ('pendente','resolvida')),
  criada_em timestamptz not null default now(),
  resolvida_em timestamptz,
  resolvida_documento_id bigint references public.orc_documentos_carga(id) on delete set null
);

create index if not exists orc_carga_pendencias_abertas_idx
  on public.orc_carga_pendencias(tipo_referencia, referencia, criada_em desc)
  where status='pendente';

create unique index if not exists orc_carga_pendencias_origem_unq
  on public.orc_carga_pendencias(tipo_referencia, referencia, origem_tipo, origem_id)
  where status='pendente' and origem_id is not null;

alter table public.orc_carga_pendencias enable row level security;
drop policy if exists "orc_carga_pendencias_select_anon" on public.orc_carga_pendencias;
create policy "orc_carga_pendencias_select_anon" on public.orc_carga_pendencias for select to anon using (true);
drop policy if exists "orc_carga_pendencias_select_authenticated" on public.orc_carga_pendencias;
create policy "orc_carga_pendencias_select_authenticated" on public.orc_carga_pendencias for select to authenticated using (true);
grant select on public.orc_carga_pendencias to anon, authenticated;
revoke insert, update, delete, truncate on public.orc_carga_pendencias from anon, authenticated;

create or replace function public.v7_7_0_criar_pendencia_carga(
  p_tipo_referencia text,p_referencia text,p_origem_tipo text,p_origem_id bigint,
  p_origem_numero text,p_descricao text default null
) returns void language plpgsql security definer set search_path=public as $$
begin
  if p_tipo_referencia not in ('dependencia','deposito') or nullif(trim(coalesce(p_referencia,'')),'') is null then return; end if;
  if p_origem_id is not null and exists (
    select 1 from public.orc_carga_pendencias where tipo_referencia=p_tipo_referencia and referencia=p_referencia
      and origem_tipo=p_origem_tipo and origem_id=p_origem_id and status='pendente'
  ) then return; end if;
  insert into public.orc_carga_pendencias(tipo_referencia,referencia,origem_tipo,origem_id,origem_numero,descricao)
  values(p_tipo_referencia,p_referencia,p_origem_tipo,p_origem_id,p_origem_numero,p_descricao);
end;$$;
revoke all on function public.v7_7_0_criar_pendencia_carga(text,text,text,bigint,text,text) from public, anon, authenticated;

create or replace function public.v7_7_0_pedido_carga_trigger() returns trigger
language plpgsql security definer set search_path=public as $$
begin
  if new.status='pronto' and old.status is distinct from new.status then
    if new.tipo='desrelacionamento_baixa' then
      if new.categoria='consumo' then
        perform public.v7_7_0_criar_pendencia_carga('deposito',new.deposito_origem,'desrelacionamento',new.id,new.numero,'Desrelacionamento/Baixa concluído: atualizar a relação do depósito.');
      else
        perform public.v7_7_0_criar_pendencia_carga('dependencia',new.dependencia_origem,'desrelacionamento',new.id,new.numero,'Desrelacionamento/Baixa concluído: gerar e anexar nova relação de carga da dependência.');
      end if;
    elsif new.tipo='distribuicao' then
      if new.deposito_origem is not null then
        perform public.v7_7_0_criar_pendencia_carga('deposito',new.deposito_origem,'distribuicao',new.id,new.numero,'Distribuição concluída: atualizar a relação do depósito de origem.');
      end if;
      if new.dependencia_destino is not null then
        perform public.v7_7_0_criar_pendencia_carga('dependencia',new.dependencia_destino,'distribuicao',new.id,new.numero,'Distribuição concluída: gerar e anexar nova relação de carga da dependência de destino.');
      end if;
    end if;
  end if;
  return new;
end;$$;
revoke all on function public.v7_7_0_pedido_carga_trigger() from public, anon, authenticated;
drop trigger if exists trg_v7_7_0_pedido_carga on public.pedidos_orcamentarios;
create trigger trg_v7_7_0_pedido_carga after update of status on public.pedidos_orcamentarios
for each row execute function public.v7_7_0_pedido_carga_trigger();

create or replace function public.v7_7_0_movimentacao_carga_trigger() returns trigger
language plpgsql security definer set search_path=public as $$
begin
  if new.status='pronto' and old.status is distinct from new.status then
    perform public.v7_7_0_criar_pendencia_carga('dependencia',new.dependencia_origem,'movimentacao',new.id,new.numero,'Movimentação concluída: gerar e anexar nova relação da dependência de origem.');
    perform public.v7_7_0_criar_pendencia_carga('dependencia',new.dependencia_destino,'movimentacao',new.id,new.numero,'Movimentação concluída: gerar e anexar nova relação da dependência de destino.');
  end if;
  return new;
end;$$;
revoke all on function public.v7_7_0_movimentacao_carga_trigger() from public, anon, authenticated;
drop trigger if exists trg_v7_7_0_movimentacao_carga on public.movimentacoes_material;
create trigger trg_v7_7_0_movimentacao_carga after update of status on public.movimentacoes_material
for each row execute function public.v7_7_0_movimentacao_carga_trigger();

create or replace function public.v7_7_0_registrar_documento_carga(
  p_tipo_referencia text,p_referencia text,p_arquivo_nome text,p_arquivo_path text,p_arquivo_url text,
  p_arquivo_mime text,p_arquivo_tamanho bigint,p_usuario_id text,p_perfil_id bigint,p_conferido_por text,
  p_observacao text default null,p_motivo_atualizacao text default 'manual'
) returns bigint language plpgsql security definer set search_path=public as $$
declare v_versao integer; v_id bigint;
begin
  if not public.v5_eh_fiscalizacao(p_usuario_id,p_perfil_id) then raise exception 'Somente a Fiscalização pode atualizar Material Carga/Depósito.'; end if;
  if nullif(trim(coalesce(p_conferido_por,'')),'') is null or not exists(select 1 from public.usuarios u where u.id::text=p_conferido_por) then raise exception 'Informe quem conferiu a relação.'; end if;
  if p_tipo_referencia='dependencia' then
    if not exists(select 1 from public.orc_dependencias d where d.ativo=true and d.nome=p_referencia) then raise exception 'Dependência inválida.'; end if;
  elsif p_tipo_referencia='deposito' then
    if not exists(select 1 from public.orc_depositos d where d.ativo=true and d.nome=p_referencia) then raise exception 'Depósito inválido.'; end if;
  else raise exception 'Tipo de referência inválido.'; end if;

  select coalesce(max(versao),0)+1 into v_versao from public.orc_documentos_carga where tipo_referencia=p_tipo_referencia and referencia=p_referencia;
  insert into public.orc_documentos_carga(tipo_referencia,referencia,versao,arquivo_nome,arquivo_path,arquivo_url,arquivo_mime,arquivo_tamanho,observacao,atualizado_por,atualizado_por_perfil_id,conferido_por,conferido_em,motivo_atualizacao)
  values(p_tipo_referencia,p_referencia,v_versao,p_arquivo_nome,p_arquivo_path,p_arquivo_url,p_arquivo_mime,p_arquivo_tamanho,p_observacao,p_usuario_id,p_perfil_id,p_conferido_por,now(),coalesce(nullif(trim(p_motivo_atualizacao),''),'manual')) returning id into v_id;
  update public.orc_carga_pendencias set status='resolvida',resolvida_em=now(),resolvida_documento_id=v_id where tipo_referencia=p_tipo_referencia and referencia=p_referencia and status='pendente';
  return v_id;
end;$$;
revoke all on function public.v7_7_0_registrar_documento_carga(text,text,text,text,text,text,bigint,text,bigint,text,text,text) from public;
grant execute on function public.v7_7_0_registrar_documento_carga(text,text,text,text,text,text,bigint,text,bigint,text,text,text) to anon, authenticated;