-- =====================================================================
-- V5.4 — ORÇAMENTÁRIOS
-- 1) Editar / excluir Guias e Pedidos
-- 2) Novo módulo Movimentação de Material
--
-- Regra funcional de gerenciamento:
-- - criador do registro; ou
-- - perfil ativo com seção = admin.
--
-- O projeto ainda usa login clássico. A proteção definitiva ficará para
-- Supabase Auth + RLS; estas RPCs centralizam as regras funcionais da V5.4.
-- =====================================================================

begin;

-- ---------------------------------------------------------------------
-- Registro de exclusões para não perder completamente a rastreabilidade.
-- ---------------------------------------------------------------------
create table if not exists public.orcamentarios_exclusoes (
  id bigint generated by default as identity primary key,
  entidade text not null,
  entidade_id text not null,
  identificador text null,
  snapshot jsonb not null,
  excluido_por text not null,
  excluido_por_perfil_id bigint null
    references public.usuario_perfis(id) on delete set null,
  excluido_em timestamptz not null default now()
);

create index if not exists idx_orc_exclusoes_entidade
  on public.orcamentarios_exclusoes(entidade,excluido_em desc);

-- ---------------------------------------------------------------------
-- Pode gerenciar: criador ou Admin ativo.
-- ---------------------------------------------------------------------
create or replace function public.v5_4_pode_gerenciar(
  p_usuario_id text,
  p_perfil_id bigint,
  p_criado_por text
)
returns boolean
language sql
stable
as $$
  select
    p_usuario_id = p_criado_por
    or exists (
      select 1
      from public.usuario_perfis p
      where p.id = p_perfil_id
        and p.usuario_id::text = p_usuario_id
        and p.ativo = true
        and lower(trim(p.secao)) = 'admin'
    );
$$;

-- =====================================================================
-- GUIAS — EDITAR / EXCLUIR
-- =====================================================================

create or replace function public.v5_4_editar_guia(
  p_guia_id bigint,
  p_usuario_id text,
  p_perfil_id bigint,
  p_numero text,
  p_data_guia date,
  p_om_origem text,
  p_om_destino text,
  p_assunto text,
  p_deposito_destino text
)
returns void
language plpgsql
as $$
declare
  g public.guias_orcamentarias%rowtype;
  novo_deposito text;
begin
  select * into g
  from public.guias_orcamentarias
  where id=p_guia_id
  for update;

  if not found then raise exception 'Guia não encontrada.'; end if;

  if not public.v5_4_pode_gerenciar(p_usuario_id,p_perfil_id,g.criado_por) then
    raise exception 'Somente o criador da guia ou um Admin pode editá-la.';
  end if;

  if nullif(trim(coalesce(p_numero,'')),'') is null
     or p_data_guia is null
     or nullif(trim(coalesce(p_om_origem,'')),'') is null
     or nullif(trim(coalesce(p_om_destino,'')),'') is null
     or nullif(trim(coalesce(p_assunto,'')),'') is null then
    raise exception 'Preencha todos os campos obrigatórios.';
  end if;

  if g.tipo in ('transferencia','remessa') then
    if nullif(trim(coalesce(p_deposito_destino,'')),'') is null then
      raise exception 'Informe o depósito de destino.';
    end if;
    if not exists(
      select 1 from public.orc_depositos d
      where d.ativo=true and d.nome=p_deposito_destino
    ) then
      raise exception 'Depósito de destino inválido.';
    end if;
    novo_deposito := p_deposito_destino;
  else
    novo_deposito := null;
  end if;

  update public.guias_orcamentarias
  set numero=trim(p_numero),
      data_guia=p_data_guia,
      om_origem=trim(p_om_origem),
      om_destino=trim(p_om_destino),
      assunto=trim(p_assunto),
      deposito_destino=novo_deposito
  where id=p_guia_id;

  insert into public.guia_tramitacoes(
    guia_id,evento,mensagem,usuario_id,perfil_id
  ) values (
    p_guia_id,
    'guia_editada',
    'Dados cadastrais da guia foram editados.',
    p_usuario_id,
    p_perfil_id
  );
end;
$$;

create or replace function public.v5_4_excluir_guia(
  p_guia_id bigint,
  p_usuario_id text,
  p_perfil_id bigint
)
returns text[]
language plpgsql
as $$
declare
  g public.guias_orcamentarias%rowtype;
  paths text[];
  snap jsonb;
begin
  select * into g
  from public.guias_orcamentarias
  where id=p_guia_id
  for update;

  if not found then raise exception 'Guia não encontrada.'; end if;

  if not public.v5_4_pode_gerenciar(p_usuario_id,p_perfil_id,g.criado_por) then
    raise exception 'Somente o criador da guia ou um Admin pode excluí-la.';
  end if;

  select coalesce(array_agg(a.arquivo_path order by a.id),array[]::text[])
    into paths
    from public.guia_anexos a
   where a.guia_id=p_guia_id;

  select to_jsonb(g) || jsonb_build_object(
    'anexos',coalesce((
      select jsonb_agg(to_jsonb(a) order by a.id)
      from public.guia_anexos a where a.guia_id=p_guia_id
    ),'[]'::jsonb),
    'historico',coalesce((
      select jsonb_agg(to_jsonb(t) order by t.id)
      from public.guia_tramitacoes t where t.guia_id=p_guia_id
    ),'[]'::jsonb)
  ) into snap;

  insert into public.orcamentarios_exclusoes(
    entidade,entidade_id,identificador,snapshot,
    excluido_por,excluido_por_perfil_id
  ) values (
    'guia',p_guia_id::text,g.numero,snap,
    p_usuario_id,p_perfil_id
  );

  delete from public.guias_orcamentarias where id=p_guia_id;
  return paths;
end;
$$;

-- =====================================================================
-- PEDIDOS — EDITAR / EXCLUIR
-- =====================================================================

create or replace function public.v5_4_editar_pedido(
  p_pedido_id bigint,
  p_usuario_id text,
  p_perfil_id bigint,
  p_numero text,
  p_data_pedido date,
  p_dependencia_origem text,
  p_deposito_origem text,
  p_dependencia_destino text,
  p_motivo text,
  p_observacoes text,
  p_itens jsonb
)
returns void
language plpgsql
as $$
declare
  p public.pedidos_orcamentarios%rowtype;
  x jsonb;
  q numeric;
  vu numeric;
begin
  select * into p
  from public.pedidos_orcamentarios
  where id=p_pedido_id
  for update;

  if not found then raise exception 'Pedido não encontrado.'; end if;

  if not public.v5_4_pode_gerenciar(p_usuario_id,p_perfil_id,p.criado_por) then
    raise exception 'Somente o criador do pedido ou um Admin pode editá-lo.';
  end if;

  if nullif(trim(coalesce(p_numero,'')),'') is null
     or p_data_pedido is null
     or nullif(trim(coalesce(p_motivo,'')),'') is null then
    raise exception 'Preencha os dados obrigatórios do pedido.';
  end if;

  if jsonb_typeof(p_itens) <> 'array' or jsonb_array_length(p_itens)=0 then
    raise exception 'O pedido precisa ter pelo menos um material.';
  end if;

  -- Tipo/categoria são imutáveis; valida somente a lotação.
  if p.tipo='desrelacionamento_baixa'
     and p.categoria in ('permanente','uso_duradouro') then
    if nullif(trim(coalesce(p_dependencia_origem,'')),'') is null
       or not exists(
         select 1 from public.orc_dependencias d
         where d.ativo=true and d.nome=p_dependencia_origem
       ) then
      raise exception 'Dependência de origem inválida.';
    end if;
    p_deposito_origem := null;
    p_dependencia_destino := null;

  elsif p.tipo='desrelacionamento_baixa' and p.categoria='consumo' then
    if nullif(trim(coalesce(p_deposito_origem,'')),'') is null
       or not exists(
         select 1 from public.orc_depositos d
         where d.ativo=true and d.nome=p_deposito_origem
       ) then
      raise exception 'Depósito de origem inválido.';
    end if;
    p_dependencia_origem := null;
    p_dependencia_destino := null;

  elsif p.tipo='distribuicao' then
    if nullif(trim(coalesce(p_deposito_origem,'')),'') is null
       or not exists(
         select 1 from public.orc_depositos d
         where d.ativo=true and d.nome=p_deposito_origem
       ) then
      raise exception 'Depósito de origem inválido.';
    end if;
    if nullif(trim(coalesce(p_dependencia_destino,'')),'') is null
       or not exists(
         select 1 from public.orc_dependencias d
         where d.ativo=true and d.nome=p_dependencia_destino
       ) then
      raise exception 'Dependência de destino inválida.';
    end if;
    p_dependencia_origem := null;
  end if;

  -- Validação dos itens.
  for x in select * from jsonb_array_elements(p_itens)
  loop
    if nullif(trim(coalesce(x->>'nome','')),'') is null
       or nullif(trim(coalesce(x->>'numero_ficha','')),'') is null then
      raise exception 'Nome e número da ficha são obrigatórios em todos os materiais.';
    end if;
    q := nullif(x->>'quantidade','')::numeric;
    vu := nullif(x->>'valor_unitario','')::numeric;
    if q is null or q<=0 or vu is null or vu<0 then
      raise exception 'Quantidade/valor unitário inválidos.';
    end if;
  end loop;

  update public.pedidos_orcamentarios
  set numero=trim(p_numero),
      data_pedido=p_data_pedido,
      dependencia_origem=nullif(trim(coalesce(p_dependencia_origem,'')),''),
      deposito_origem=nullif(trim(coalesce(p_deposito_origem,'')),''),
      dependencia_destino=nullif(trim(coalesce(p_dependencia_destino,'')),''),
      motivo=trim(p_motivo),
      observacoes=nullif(trim(coalesce(p_observacoes,'')),'')
  where id=p_pedido_id;

  delete from public.pedido_orcamentario_itens
  where pedido_id=p_pedido_id;

  for x in select * from jsonb_array_elements(p_itens)
  loop
    insert into public.pedido_orcamentario_itens(
      pedido_id,nome,numero_ficha,quantidade,valor_unitario
    ) values (
      p_pedido_id,
      trim(x->>'nome'),
      trim(x->>'numero_ficha'),
      (x->>'quantidade')::numeric,
      (x->>'valor_unitario')::numeric
    );
  end loop;

  insert into public.pedido_orcamentario_tramitacoes(
    pedido_id,evento,mensagem,usuario_id,perfil_id
  ) values (
    p_pedido_id,'pedido_editado',
    'Dados e materiais do pedido foram editados.',
    p_usuario_id,p_perfil_id
  );
end;
$$;

create or replace function public.v5_4_excluir_pedido(
  p_pedido_id bigint,
  p_usuario_id text,
  p_perfil_id bigint
)
returns void
language plpgsql
as $$
declare
  p public.pedidos_orcamentarios%rowtype;
  snap jsonb;
begin
  select * into p
  from public.pedidos_orcamentarios
  where id=p_pedido_id
  for update;

  if not found then raise exception 'Pedido não encontrado.'; end if;

  if not public.v5_4_pode_gerenciar(p_usuario_id,p_perfil_id,p.criado_por) then
    raise exception 'Somente o criador do pedido ou um Admin pode excluí-lo.';
  end if;

  select to_jsonb(p) || jsonb_build_object(
    'itens',coalesce((
      select jsonb_agg(to_jsonb(i) order by i.id)
      from public.pedido_orcamentario_itens i
      where i.pedido_id=p_pedido_id
    ),'[]'::jsonb),
    'historico',coalesce((
      select jsonb_agg(to_jsonb(t) order by t.id)
      from public.pedido_orcamentario_tramitacoes t
      where t.pedido_id=p_pedido_id
    ),'[]'::jsonb)
  ) into snap;

  insert into public.orcamentarios_exclusoes(
    entidade,entidade_id,identificador,snapshot,
    excluido_por,excluido_por_perfil_id
  ) values (
    'pedido',p_pedido_id::text,p.numero,snap,
    p_usuario_id,p_perfil_id
  );

  delete from public.pedidos_orcamentarios
  where id=p_pedido_id;
end;
$$;

-- =====================================================================
-- MOVIMENTAÇÃO DE MATERIAL
-- =====================================================================

create table if not exists public.movimentacoes_material (
  id bigint generated by default as identity primary key,
  numero text not null,
  data_movimentacao date not null default current_date,

  dependencia_origem text not null,
  dependencia_destino text not null,

  finalidade text not null,
  observacoes text null,

  valor_total numeric(16,2) not null default 0,

  criado_por text not null,
  criado_por_perfil_id bigint null
    references public.usuario_perfis(id) on delete set null,
  secao_criador text null,
  posicao_criador text null,

  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create index if not exists idx_mov_material_data
  on public.movimentacoes_material(data_movimentacao desc,id desc);

create table if not exists public.movimentacao_material_itens (
  id bigint generated by default as identity primary key,
  movimentacao_id bigint not null
    references public.movimentacoes_material(id) on delete cascade,

  nome text not null,
  numero_ficha text not null,
  quantidade numeric(14,3) not null check (quantidade>0),
  valor_unitario numeric(16,2) not null check (valor_unitario>=0),

  valor_total numeric(18,2)
    generated always as (round(quantidade*valor_unitario,2)) stored,

  criado_em timestamptz not null default now()
);

create index if not exists idx_mov_material_itens
  on public.movimentacao_material_itens(movimentacao_id,id);

create table if not exists public.movimentacao_material_anexos (
  id bigint generated by default as identity primary key,
  movimentacao_id bigint not null
    references public.movimentacoes_material(id) on delete cascade,

  arquivo_nome text not null,
  arquivo_path text not null,
  arquivo_url text not null,
  arquivo_mime text null,
  arquivo_tamanho bigint null,
  observacao text null,

  enviado_por text not null,
  enviado_por_perfil_id bigint null
    references public.usuario_perfis(id) on delete set null,

  criado_em timestamptz not null default now()
);

create index if not exists idx_mov_material_anexos
  on public.movimentacao_material_anexos(movimentacao_id,criado_em desc,id desc);

create table if not exists public.movimentacao_material_tramitacoes (
  id bigint generated by default as identity primary key,
  movimentacao_id bigint not null
    references public.movimentacoes_material(id) on delete cascade,

  evento text not null,
  mensagem text null,

  usuario_id text not null,
  perfil_id bigint null
    references public.usuario_perfis(id) on delete set null,

  criado_em timestamptz not null default now()
);

create index if not exists idx_mov_material_tramitacoes
  on public.movimentacao_material_tramitacoes(movimentacao_id,criado_em desc,id desc);

-- touch
create or replace function public.v5_4_touch_movimentacao()
returns trigger
language plpgsql
as $$
begin
  new.atualizado_em:=now();
  return new;
end;
$$;

drop trigger if exists trg_v5_4_touch_movimentacao
  on public.movimentacoes_material;

create trigger trg_v5_4_touch_movimentacao
before update on public.movimentacoes_material
for each row execute function public.v5_4_touch_movimentacao();

-- total
create or replace function public.v5_4_recalcular_total_movimentacao()
returns trigger
language plpgsql
as $$
declare
  v_id bigint;
begin
  v_id:=case when tg_op='DELETE' then old.movimentacao_id else new.movimentacao_id end;

  update public.movimentacoes_material m
  set valor_total=coalesce((
    select round(sum(i.valor_total),2)
    from public.movimentacao_material_itens i
    where i.movimentacao_id=v_id
  ),0)
  where m.id=v_id;

  return coalesce(new,old);
end;
$$;

drop trigger if exists trg_v5_4_total_movimentacao
  on public.movimentacao_material_itens;

create trigger trg_v5_4_total_movimentacao
after insert or update or delete
on public.movimentacao_material_itens
for each row execute function public.v5_4_recalcular_total_movimentacao();

create or replace function public.v5_4_editar_movimentacao(
  p_movimentacao_id bigint,
  p_usuario_id text,
  p_perfil_id bigint,
  p_numero text,
  p_data_movimentacao date,
  p_dependencia_origem text,
  p_dependencia_destino text,
  p_finalidade text,
  p_observacoes text,
  p_itens jsonb
)
returns void
language plpgsql
as $$
declare
  m public.movimentacoes_material%rowtype;
  x jsonb;
begin
  select * into m
  from public.movimentacoes_material
  where id=p_movimentacao_id
  for update;

  if not found then raise exception 'Movimentação não encontrada.'; end if;

  if not public.v5_4_pode_gerenciar(p_usuario_id,p_perfil_id,m.criado_por) then
    raise exception 'Somente o criador da movimentação ou um Admin pode editá-la.';
  end if;

  if nullif(trim(coalesce(p_numero,'')),'') is null
     or p_data_movimentacao is null
     or nullif(trim(coalesce(p_finalidade,'')),'') is null then
    raise exception 'Preencha os campos obrigatórios.';
  end if;

  if p_dependencia_origem=p_dependencia_destino then
    raise exception 'A dependência de origem e destino precisam ser diferentes.';
  end if;

  if not exists(
    select 1 from public.orc_dependencias d
    where d.ativo=true and d.nome=p_dependencia_origem
  ) or not exists(
    select 1 from public.orc_dependencias d
    where d.ativo=true and d.nome=p_dependencia_destino
  ) then
    raise exception 'Dependência de origem/destino inválida.';
  end if;

  if jsonb_typeof(p_itens)<>'array' or jsonb_array_length(p_itens)=0 then
    raise exception 'Informe pelo menos um material.';
  end if;

  update public.movimentacoes_material
  set numero=trim(p_numero),
      data_movimentacao=p_data_movimentacao,
      dependencia_origem=p_dependencia_origem,
      dependencia_destino=p_dependencia_destino,
      finalidade=trim(p_finalidade),
      observacoes=nullif(trim(coalesce(p_observacoes,'')),'')
  where id=p_movimentacao_id;

  delete from public.movimentacao_material_itens
  where movimentacao_id=p_movimentacao_id;

  for x in select * from jsonb_array_elements(p_itens)
  loop
    if nullif(trim(coalesce(x->>'nome','')),'') is null
       or nullif(trim(coalesce(x->>'numero_ficha','')),'') is null
       or (x->>'quantidade')::numeric<=0
       or (x->>'valor_unitario')::numeric<0 then
      raise exception 'Confira os dados dos materiais.';
    end if;

    insert into public.movimentacao_material_itens(
      movimentacao_id,nome,numero_ficha,quantidade,valor_unitario
    ) values (
      p_movimentacao_id,
      trim(x->>'nome'),
      trim(x->>'numero_ficha'),
      (x->>'quantidade')::numeric,
      (x->>'valor_unitario')::numeric
    );
  end loop;

  insert into public.movimentacao_material_tramitacoes(
    movimentacao_id,evento,mensagem,usuario_id,perfil_id
  ) values (
    p_movimentacao_id,'movimentacao_editada',
    'Dados e materiais da movimentação foram editados.',
    p_usuario_id,p_perfil_id
  );
end;
$$;

create or replace function public.v5_4_adicionar_atualizacao_movimentacao(
  p_movimentacao_id bigint,
  p_usuario_id text,
  p_perfil_id bigint,
  p_mensagem text
)
returns void
language plpgsql
as $$
begin
  if nullif(trim(coalesce(p_mensagem,'')),'') is null then
    raise exception 'Digite a atualização.';
  end if;

  if not exists(
    select 1 from public.movimentacoes_material m
    where m.id=p_movimentacao_id
  ) then
    raise exception 'Movimentação não encontrada.';
  end if;

  insert into public.movimentacao_material_tramitacoes(
    movimentacao_id,evento,mensagem,usuario_id,perfil_id
  ) values (
    p_movimentacao_id,'atualizacao',
    trim(p_mensagem),p_usuario_id,p_perfil_id
  );
end;
$$;

create or replace function public.v5_4_excluir_movimentacao(
  p_movimentacao_id bigint,
  p_usuario_id text,
  p_perfil_id bigint
)
returns text[]
language plpgsql
as $$
declare
  m public.movimentacoes_material%rowtype;
  paths text[];
  snap jsonb;
begin
  select * into m
  from public.movimentacoes_material
  where id=p_movimentacao_id
  for update;

  if not found then raise exception 'Movimentação não encontrada.'; end if;

  if not public.v5_4_pode_gerenciar(p_usuario_id,p_perfil_id,m.criado_por) then
    raise exception 'Somente o criador da movimentação ou um Admin pode excluí-la.';
  end if;

  select coalesce(array_agg(a.arquivo_path order by a.id),array[]::text[])
    into paths
    from public.movimentacao_material_anexos a
   where a.movimentacao_id=p_movimentacao_id;

  select to_jsonb(m) || jsonb_build_object(
    'itens',coalesce((
      select jsonb_agg(to_jsonb(i) order by i.id)
      from public.movimentacao_material_itens i
      where i.movimentacao_id=p_movimentacao_id
    ),'[]'::jsonb),
    'anexos',coalesce((
      select jsonb_agg(to_jsonb(a) order by a.id)
      from public.movimentacao_material_anexos a
      where a.movimentacao_id=p_movimentacao_id
    ),'[]'::jsonb),
    'historico',coalesce((
      select jsonb_agg(to_jsonb(t) order by t.id)
      from public.movimentacao_material_tramitacoes t
      where t.movimentacao_id=p_movimentacao_id
    ),'[]'::jsonb)
  ) into snap;

  insert into public.orcamentarios_exclusoes(
    entidade,entidade_id,identificador,snapshot,
    excluido_por,excluido_por_perfil_id
  ) values (
    'movimentacao',p_movimentacao_id::text,m.numero,snap,
    p_usuario_id,p_perfil_id
  );

  delete from public.movimentacoes_material
  where id=p_movimentacao_id;

  return paths;
end;
$$;

-- ---------------------------------------------------------------------
-- Bucket de anexos da movimentação.
-- ---------------------------------------------------------------------
insert into storage.buckets(id,name,public,file_size_limit)
values (
  'movimentacoes-material',
  'movimentacoes-material',
  true,
  26214400
)
on conflict (id) do update set
  public=excluded.public,
  file_size_limit=excluded.file_size_limit;

drop policy if exists "v54_mov_public_read" on storage.objects;
create policy "v54_mov_public_read"
on storage.objects for select
to public
using (bucket_id='movimentacoes-material');

drop policy if exists "v54_mov_insert" on storage.objects;
create policy "v54_mov_insert"
on storage.objects for insert
to anon,authenticated
with check (bucket_id='movimentacoes-material');

drop policy if exists "v54_mov_delete" on storage.objects;
create policy "v54_mov_delete"
on storage.objects for delete
to anon,authenticated
using (bucket_id='movimentacoes-material');

-- ---------------------------------------------------------------------
-- Grants do modo clássico atual
-- ---------------------------------------------------------------------
alter table public.orcamentarios_exclusoes disable row level security;
alter table public.movimentacoes_material disable row level security;
alter table public.movimentacao_material_itens disable row level security;
alter table public.movimentacao_material_anexos disable row level security;
alter table public.movimentacao_material_tramitacoes disable row level security;

grant select,insert,update,delete on
  public.orcamentarios_exclusoes,
  public.movimentacoes_material,
  public.movimentacao_material_itens,
  public.movimentacao_material_anexos,
  public.movimentacao_material_tramitacoes
to anon,authenticated;

grant usage,select on all sequences in schema public
to anon,authenticated;

grant execute on function public.v5_4_pode_gerenciar(text,bigint,text)
to anon,authenticated;

grant execute on function public.v5_4_editar_guia(bigint,text,bigint,text,date,text,text,text,text)
to anon,authenticated;

grant execute on function public.v5_4_excluir_guia(bigint,text,bigint)
to anon,authenticated;

grant execute on function public.v5_4_editar_pedido(bigint,text,bigint,text,date,text,text,text,text,text,jsonb)
to anon,authenticated;

grant execute on function public.v5_4_excluir_pedido(bigint,text,bigint)
to anon,authenticated;

grant execute on function public.v5_4_editar_movimentacao(bigint,text,bigint,text,date,text,text,text,text,jsonb)
to anon,authenticated;

grant execute on function public.v5_4_adicionar_atualizacao_movimentacao(bigint,text,bigint,text)
to anon,authenticated;

grant execute on function public.v5_4_excluir_movimentacao(bigint,text,bigint)
to anon,authenticated;

commit;

-- Conferência
select id,numero,data_movimentacao,dependencia_origem,dependencia_destino,valor_total
from public.movimentacoes_material
order by id desc
limit 20;
