(function(){
'use strict';
if(window.__TAREFAS_749_CORE__)return;
window.__TAREFAS_749_CORE__=true;
const VERSION='7.4.9';
const norm=v=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim().toLowerCase();
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const getUser=()=>{try{return JSON.parse(localStorage.getItem('usuarioLogado')||'null')}catch(_){return null}};
const client=()=>{try{return typeof supabaseClient!=='undefined'?supabaseClient:null}catch(_){return null}};
let adminProfileId=null,currentState=null;

function css(){if(document.getElementById('v749Css'))return;const s=document.createElement('style');s.id='v749Css';s.textContent=`
.v749-site-item .v6-nav-item{width:100%}.v749-site-dot{width:7px;height:7px;border-radius:50%;margin-left:auto;background:#22c55e;box-shadow:0 0 0 3px rgba(34,197,94,.12)}.v749-site-item[data-state=off] .v749-site-dot{background:#ef4444}.v749-site-item[data-state=pending] .v749-site-dot{background:#f59e0b}
#v749Modal{position:fixed;inset:0;z-index:2147483646;background:#0009;display:grid;place-items:center;padding:18px;font-family:Arial,sans-serif}#v749Modal[hidden]{display:none!important}#v749Modal .card{width:min(560px,100%);background:#0f172a;color:#e5e7eb;border:1px solid #334155;border-radius:18px;padding:18px;box-shadow:0 25px 70px #000b}#v749Modal h3{margin:0 0 5px;color:#fff;font-size:20px}#v749Modal .sub{font-size:11px;color:#94a3b8;margin-bottom:14px}#v749Modal .status{padding:11px;border:1px solid #334155;border-radius:10px;background:#111827;margin-bottom:12px;font-size:12px;line-height:1.5}#v749Modal .grid{display:grid;grid-template-columns:1fr 1fr;gap:8px}#v749Modal button{border:1px solid #475569;background:#111827;color:#e5e7eb;border-radius:10px;padding:11px;font-weight:800;cursor:pointer}#v749Modal button.danger{border-color:#ef4444;color:#fecaca}#v749Modal button.warn{border-color:#f59e0b;color:#fde68a}#v749Modal button.good{border-color:#22c55e;color:#bbf7d0}#v749Modal .close{width:100%;margin-top:9px}@media(max-width:520px){#v749Modal .grid{grid-template-columns:1fr}}
`;document.head.appendChild(s)}

async function resolveAdmin(){adminProfileId=null;const u=getUser(),c=client();if(!u?.id||!c)return false;try{const q=await c.from('usuario_perfis').select('id,secao,ativo').eq('usuario_id',Number(u.id)).eq('ativo',true).order('principal',{ascending:false}).order('id');if(q.error)throw q.error;for(const p of q.data||[]){if(norm(p.secao)!=='admin')continue;const r=await c.rpc('v7_1_admin_total',{p_usuario_id:Number(u.id),p_perfil_id:Number(p.id)});if(!r.error&&r.data===true){adminProfileId=Number(p.id);return true}}}catch(e){console.warn('V7.4.9 admin:',e?.message||e)}return false}
async function loadState(){const c=client();if(!c)return null;const r=await c.rpc('v7_4_7_estado_site');if(r.error)throw r.error;currentState=Array.isArray(r.data)?r.data[0]:r.data;syncState();return currentState}
function stateName(){return currentState?.acao_pendente?'pending':currentState?.modo==='desligado'?'off':'online'}
function syncState(){document.querySelectorAll('.v749-site-item').forEach(el=>el.dataset.state=stateName())}
function host(){return document.querySelector('.sidebar .menu-items,.sidebar ul')}
function dash(hostEl){return [...hostEl.children].find(li=>norm(li.textContent).includes('dashboard')||((li.querySelector('a')?.getAttribute('href')||'').includes('dashboard.html')))||hostEl.firstElementChild}
function icon(){return '<span class="v6-nav-icon"><svg viewBox="0 0 24 24"><path d="M12 3a9 9 0 1 0 9 9"/><path d="M12 7v5l3 2"/><path d="M16 3h5v5"/><path d="m21 3-6 6"/></svg></span>'}
async function ensureMenu(){if(!await resolveAdmin())return false;const h=host();if(!h)return false;let li=document.getElementById('v749SiteSidebarItem');if(!li){document.getElementById('v748SiteSidebarItem')?.remove();li=document.createElement('li');li.id='v749SiteSidebarItem';li.className='v749-site-item';li.innerHTML=`<button type="button" class="v6-nav-item" title="Abrir Painel SITE">${icon()}<span class="v6-nav-label">Painel SITE</span><span class="v749-site-dot"></span></button>`;const d=dash(h);if(d?.nextSibling)h.insertBefore(li,d.nextSibling);else h.appendChild(li);li.querySelector('button').onclick=openPanel}syncState();return true}
function renderModal(){let m=document.getElementById('v749Modal');if(!m){m=document.createElement('div');m.id='v749Modal';document.body.appendChild(m)}const pending=currentState?.acao_pendente?`${esc(currentState.acao_pendente)} — ação pendente`:'Nenhuma ação pendente';m.innerHTML=`<div class="card"><h3>Painel SITE · V${VERSION}</h3><div class="sub">Controle administrativo global do TAREFAS.</div><div class="status"><b>Status:</b> ${currentState?.modo==='desligado'?'DESLIGADO / MANUTENÇÃO':'ONLINE'}<br><b>Ação:</b> ${pending}</div><div class="grid"><button class="danger" data-act="exit_users">EXIT USERS</button><button class="danger" data-act="desligar">Desligar site</button><button class="warn" data-act="reiniciar">Reiniciar site</button><button class="good" data-act="iniciar">Iniciar site</button>${currentState?.acao_pendente?'<button data-act="cancelar">Cancelar ação</button>':''}</div><button class="close" data-close>Fechar</button></div>`;m.hidden=false;m.querySelector('[data-close]').onclick=()=>m.hidden=true;m.querySelectorAll('[data-act]').forEach(b=>b.onclick=()=>act(b.dataset.act))}
async function openPanel(){if(!await resolveAdmin())return alert('Painel SITE disponível somente para usuário com perfil Admin ativo.');try{await loadState()}catch(e){return alert('Não foi possível consultar o estado do SITE: '+(e?.message||e))}renderModal()}
async function act(action){const u=getUser(),c=client();if(!u?.id||!c||!adminProfileId)return alert('Não foi possível validar o perfil Admin.');const msg=action==='exit_users'?'Encerrar as sessões dos usuários comuns em 30 segundos?':action==='desligar'?'Desligar o site em 30 segundos?':action==='reiniciar'?'Reiniciar o site em 30 segundos?':action==='iniciar'?'Iniciar o site agora?':'Cancelar a ação pendente?';if(!confirm(msg))return;const r=await c.rpc('v7_4_7_controle_site',{p_acao:action,p_usuario_id:Number(u.id),p_perfil_id:Number(adminProfileId)});if(r.error)return alert(r.error.message||'Falha ao alterar o SITE.');currentState=Array.isArray(r.data)?r.data[0]:r.data;renderModal();syncState()}
function version(){document.querySelectorAll('small,span,strong,div').forEach(el=>{if((el.textContent||'').trim()==='v7.4.8')el.textContent='v7.4.9'});document.documentElement.dataset.tarefasVersion=VERSION}
function init(){css();version();ensureMenu();loadState().catch(()=>{});const obs=new MutationObserver(()=>{version();ensureMenu()});obs.observe(document.body,{childList:true,subtree:true});setInterval(()=>{ensureMenu();loadState().catch(()=>{})},5000)}
window.SitePanel749={open:openPanel,refresh:loadState,version:VERSION};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();