(function(){
'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const page=(location.pathname.split('/').pop()||'').toLowerCase(),svc=page==='pessoal.html',mis=page==='missao.html';
if(!svc&&!mis)return;
let mode='month';
function css(){if($('#v741PeriodCss'))return;const s=document.createElement('style');s.id='v741PeriodCss';s.textContent='.v741-periods{display:flex;gap:6px;flex-wrap:wrap}.v741-periods .v7-btn.active{background:var(--v4-accent);border-color:var(--v4-accent);color:#fff}.v741-annual{display:grid;grid-template-columns:repeat(4,minmax(120px,1fr));gap:8px;margin:8px 0}.v741-annual>div{border:1px solid var(--v4-border);border-radius:9px;padding:10px;background:var(--v4-surface)}.v741-annual small{display:block;color:var(--v4-muted);font-size:8px}.v741-annual b{display:block;font-size:18px;margin-top:4px}@media(max-width:700px){.v741-periods{display:grid;grid-template-columns:1fr 1fr;width:100%}.v741-periods .v7-btn{width:100%}.v741-annual{grid-template-columns:1fr 1fr}}';document.head.appendChild(s)}
function today(){return new Date()}
function mon(d){const x=new Date(d),n=(x.getDay()+6)%7;x.setDate(x.getDate()-n);x.setHours(0,0,0,0);return x}
function same(a,b){return a&&a.getFullYear()===b.getFullYear()&&a.getMonth()===b.getMonth()&&a.getDate()===b.getDate()}
function monthYear(){const t=(document.getElementById('monthLabel')?.textContent||'').toLowerCase(),ms=['janeiro','fevereiro','março','abril','maio','junho','julho','agosto','setembro','outubro','novembro','dezembro'],m=ms.findIndex(x=>t.includes(x)),y=Number((t.match(/20\d{2}/)||[])[0])||today().getFullYear();return{m:m>=0?m:today().getMonth(),y}}
function dates(table){const {m,y}=monthYear();return [...table.querySelectorAll('thead th')].slice(1).map(th=>{const n=Number(th.querySelector('b')?.textContent||th.textContent.match(/\b\d{1,2}\b/)?.[0]);return n?new Date(y,m,n):null})}
function board(){return svc?$('#scaleBoard'):$('#missionScaleBoard')}
function apply(next){mode=next;$$('.v741-periods [data-v741-mode]').forEach(b=>b.classList.toggle('active',b.dataset.v741Mode===next));$('#v741Annual')?.remove();const b=board();if(b)b.style.display='';if(next==='year'){annual();return}const base=today(),ws=mon(base),we=new Date(ws);we.setDate(we.getDate()+6);const tom=today();tom.setDate(tom.getDate()+1);$$((svc?'#scaleBoard ':'#missionScaleBoard ')+'.v7-table').forEach(t=>{const ds=dates(t),rows=[...t.rows];ds.forEach((d,i)=>{let show=true;if(next==='today')show=same(d,today());else if(next==='tomorrow')show=same(d,tom);else if(next==='week')show=!!d&&d>=ws&&d<=we;for(const r of rows)if(r.cells[i+1])r.cells[i+1].style.display=show?'':'none'})})}
async function annual(){const b=board();if(!b||typeof supabaseClient==='undefined')return;b.style.display='none';const w=document.createElement('div');w.id='v741Annual';w.className='v741-annual';b.parentNode.insertBefore(w,b);const y=today().getFullYear(),a=`${y}-01-01`,z=`${y}-12-31`;let data=[];try{const q=svc?supabaseClient.from('escala_servicos').select('data_servico').gte('data_servico',a).lte('data_servico',z):supabaseClient.from('missoes_escala').select('data_inicio').gte('data_inicio',a).lte('data_inicio',z);const r=await q;if(r.error)throw r.error;data=r.data||[]}catch(e){w.innerHTML='<div><b>Erro</b><small>'+String(e.message||e)+'</small></div>';return}const ms=['Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez'];w.innerHTML=ms.map((n,i)=>{const c=data.filter(x=>new Date((x.data_servico||x.data_inicio)+'T12:00:00').getMonth()===i).length;return `<div><small>${n} ${y}</small><b>${c}</b><span>${svc?'serviço(s)':'missão(ões)'}</span></div>`}).join('')}
function init(){css();const a=$('.v7-head .v7-actions');if(!a||$('#v741Periods'))return;const d=document.createElement('div');d.id='v741Periods';d.className='v741-periods';d.innerHTML='<button class="v7-btn" data-v741-mode="today">Hoje</button><button class="v7-btn" data-v741-mode="tomorrow">Amanhã</button><button class="v7-btn" data-v741-mode="week">Esta semana</button><button class="v7-btn active" data-v741-mode="month">Mês</button><button class="v7-btn" data-v741-mode="year">Ano</button>';d.onclick=e=>{const b=e.target.closest('[data-v741-mode]');if(b)apply(b.dataset.v741Mode)};a.insertBefore(d,a.firstChild);new MutationObserver(()=>{if(mode!=='month'&&mode!=='year')apply(mode)}).observe(board()||document.body,{childList:true,subtree:true})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
