(function(){
'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const page=(location.pathname.split('/').pop()||'').toLowerCase(),svc=page==='pessoal.html',mis=page==='missao.html';if(!svc&&!mis)return;
function modal(on){document.getElementById('v741PdfModal')?.classList.toggle('open',on)}
function load(){return new Promise((ok,no)=>{if(window.jspdf?.jsPDF)return ok();const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/jspdf@2.5.2/dist/jspdf.umd.min.js';s.onload=ok;s.onerror=()=>no(new Error('Falha ao carregar jsPDF.'));document.head.appendChild(s)})}
function groups(){return svc?['Sargentos','Motoristas','Patrulheiros','Permanência']:['Sargentos','Cabos','Soldados']}
function ensure(){if($('#v741PdfModal'))return;const bg=document.createElement('div');bg.id='v741PdfModal';bg.className='v7-modal-bg';bg.innerHTML=`<div class="v7-modal" style="width:min(560px,100%)"><div class="v7-modal-head"><h3>Gerar tabela PDF <small style="font-size:9px;color:var(--v4-muted)">V7.4.1</small></h3><button class="v7-close" data-v741-close>×</button></div><div style="display:grid;gap:7px">${groups().map(g=>`<label style="display:flex;gap:8px;align-items:center"><input type="checkbox" data-v741-group="${g}" checked> ${g}</label>`).join('')}<label><input type="checkbox" id="v741Legend" checked> Incluir legenda Preta / Vermelha</label></div><div class="v7-modal-actions"><button class="v7-btn" data-v741-close>Cancelar</button><button class="v7-btn primary" id="v741GoPdf">Gerar PDF</button></div></div>`;document.body.appendChild(bg);bg.onclick=e=>{if(e.target===bg||e.target.closest('[data-v741-close]'))modal(false)};$('#v741GoPdf').onclick=generate}
async function generate(){try{await load();const {jsPDF}=window.jspdf,doc=new jsPDF({orientation:'landscape',unit:'mm',format:'a4'});let y=12;doc.setFont('helvetica','bold');doc.setFontSize(14);doc.text((svc?'Escala de Serviço':'Escala de Missão')+' — V7.4.1',14,y);y+=7;doc.setFont('helvetica','normal');doc.setFontSize(8);if($('#v741Legend')?.checked){doc.text('Preta = dias úteis | Vermelha = sábados, domingos e feriados',14,y);y+=6}const chosen=new Set($$('[data-v741-group]:checked').map(x=>x.dataset.v741Group)),panels=$$((svc?'#scaleBoard ':'#missionScaleBoard ')+'.v7-panel').filter(p=>chosen.has(p.querySelector('.v7-panel-head h3')?.textContent.trim()));for(const p of panels){if(y>185){doc.addPage();y=12}const title=p.querySelector('.v7-panel-head h3')?.textContent.trim()||'Tabela';doc.setFont('helvetica','bold');doc.setFontSize(11);doc.text(title,14,y);y+=5;doc.setFont('helvetica','normal');doc.setFontSize(7);for(const r of p.querySelectorAll('tbody tr')){const text=[...r.cells].filter(c=>c.style.display!=='none').map(c=>c.innerText.replace(/\s+/g,' ').trim()).filter(Boolean).join(' | '),lines=doc.splitTextToSize(text,268);if(y+lines.length*3.6>195){doc.addPage();y=12}doc.text(lines,16,y);y+=lines.length*3.6+1.5}}doc.save((svc?'escala_servico':'escala_missao')+'_v7.4.1.pdf');modal(false)}catch(e){alert('Erro ao gerar PDF: '+(e.message||e))}}
function init(){ensure();const a=$('.v7-head .v7-actions');if(!a||$('#v741PdfBtn'))return;const b=document.createElement('button');b.id='v741PdfBtn';b.className='v7-btn';b.textContent='Gerar tabela PDF';b.onclick=()=>modal(true);a.appendChild(b)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
