(function(){
'use strict';
if((location.pathname.split('/').pop()||'').toLowerCase()!=='pessoal.html')return;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let transferData=null,transferPeople=null;
function user(){try{return JSON.parse(localStorage.getItem('usuarioLogado')||'null')}catch(_){return null}}
function pid(){const u=user();return u?.perfil_id?Number(u.perfil_id):null}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function norm(v){return String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase()}
function groupLabel(g){return g==='motorista'?'Motoristas':g==='patrulheiro'?'Patrulheiros':g==='permanencia'?'Permanência':g==='canil'?'Permanência/Canil':g}
function modal(on){document.getElementById('v742TransferModal')?.classList.toggle('open',on)}
function ensureModal(){if($('#v742TransferModal'))return;const bg=document.createElement('div');bg.id='v742TransferModal';bg.className='v7-modal-bg';bg.innerHTML=`<div class="v7-modal" style="width:min(720px,100%)"><div class="v7-modal-head"><h3 id="v742TransferTitle">Transferir / substituir</h3><button class="v7-close" data-v742-transfer-close>×</button></div><div id="v742TransferSource" class="v742-transfer-person"></div><div class="v7-note" style="margin-top:9px">O substituto assume a <b>mesma ordem da vaga</b> e continua as referências de folga <b>Preta e Vermelha</b>. O militar transferido entra no fim da nova escala e passa a contar folgas somente nela.</div><div class="v7-field"><label>Quem assumirá a vaga *</label><input id="v742TransferSearch" class="v742-search-input" type="search" placeholder="Buscar militar..."><input id="v742TransferSelected" type="hidden"></div><div id="v742TransferCandidates" class="v742-candidates"></div><div class="v7-modal-actions"><button class="v7-btn" type="button" data-v742-transfer-close>Cancelar</button><button class="v7-btn primary" type="button" id="v742TransferConfirm">Confirmar transferência</button></div></div>`;document.body.appendChild(bg);bg.onclick=e=>{if(e.target===bg||e.target.closest('[data-v742-transfer-close]'))modal(false)};$('#v742TransferSearch').oninput=renderCandidates;$('#v742TransferConfirm').onclick=confirmTransfer}
async function loadPeople(origin){if(transferPeople?.origin===origin)return transferPeople;const [u,e,m]=await Promise.all([supabaseClient.from('usuarios').select('id,patente,nome_guerra,secao,posicao,ativo').eq('ativo',true).order('nome_guerra'),supabaseClient.from('pessoal_nomes_externos').select('id,patente,nome,ativo').eq('ativo',true).order('nome'),supabaseClient.from('escala_integrantes').select('id,grupo,usuario_id,pessoa_externa_id,ativo').eq('ativo',true)]);for(const r of [u,e,m])if(r.error)throw r.error;const mem=m.data||[],groupsFor=(kind,id)=>mem.filter(x=>(kind==='u'?String(x.usuario_id)===String(id):String(x.pessoa_externa_id)===String(id))).map(x=>x.grupo);const rows=[...(u.data||[]).map(x=>({key:`u:${x.id}`,name:[x.patente,x.nome_guerra].filter(Boolean).join(' '),meta:[x.secao,x.posicao].filter(Boolean).join(' · '),groups:groupsFor('u',x.id)})),...(e.data||[]).map(x=>({key:`e:${x.id}`,name:[x.patente,x.nome].filter(Boolean).join(' '),meta:'Nome externo',groups:groupsFor('e',x.id)}))].filter(x=>!x.groups.includes(origin));transferPeople={origin,rows};return transferPeople}
function renderCandidates(){if(!transferPeople)return;const q=norm($('#v742TransferSearch').value),host=$('#v742TransferCandidates'),rows=transferPeople.rows.filter(x=>!q||norm(x.name+' '+x.meta+' '+x.groups.join(' ')).includes(q)).slice(0,80);host.innerHTML=rows.length?rows.map(x=>`<button type="button" class="v742-candidate" data-key="${esc(x.key)}"><b>${esc(x.name)}</b><small>${esc(x.meta||'')}${x.groups.length?' · Escalas: '+x.groups.map(groupLabel).join(', '):' · Fora das escalas de serviço'}</small></button>`).join(''):'<div class="v7-empty">Nenhum militar encontrado.</div>';host.onclick=e=>{const b=e.target.closest('[data-key]');if(!b)return;host.querySelectorAll('.v742-candidate.active').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#v742TransferSelected').value=b.dataset.key}}
async function openTransfer(id,row,origin,dest){try{ensureModal();if(origin==='canil'||dest==='canil')return alert('Permanência/Canil é uma escala separada e não participa de transferências.');const name=row.querySelector('b')?.childNodes?.[0]?.textContent?.trim()||row.querySelector('b')?.textContent?.trim()||'Militar';transferData={id:Number(id),origin,dest,name};$('#v742TransferTitle').textContent=`Transferir ${groupLabel(origin)} → ${groupLabel(dest)}`;$('#v742TransferSource').innerHTML=`<b>${esc(name)}</b><small>${esc(groupLabel(origin))} → ${esc(groupLabel(dest))}. Um substituto assumirá a vaga atual.</small>`;$('#v742TransferSearch').value='';$('#v742TransferSelected').value='';$('#v742TransferCandidates').innerHTML='<div class="v7-empty">Carregando militares...</div>';modal(true);transferPeople=null;await loadPeople(origin);renderCandidates()}catch(e){alert('Erro ao preparar transferência: '+(e.message||e))}}
async function confirmTransfer(){const u=user(),value=$('#v742TransferSelected').value;if(!transferData||!value)return alert('Selecione quem assumirá a vaga.');if(!confirm(`${transferData.name} irá para ${groupLabel(transferData.dest)}. O substituto escolhido assumirá a vaga em ${groupLabel(transferData.origin)} e herdará as folgas da vaga. Confirmar?`))return;const [kind,id]=value.split(':'),btn=$('#v742TransferConfirm');try{btn.disabled=true;btn.textContent='Transferindo...';const r=await supabaseClient.rpc('v7_4_2_transferir_substituir_integrante',{p_integrante_origem_id:transferData.id,p_grupo_destino:transferData.dest,p_substituto_usuario_id:kind==='u'?Number(id):null,p_substituto_pessoa_externa_id:kind==='e'?Number(id):null,p_usuario_id:Number(u.id),p_perfil_id:pid()});if(r.error)throw r.error;alert('Transferência concluída. A vaga manteve a ordem e as referências de folga.');location.reload()}catch(e){alert('Erro na transferência: '+(e.message||e))}finally{btn.disabled=false;btn.textContent='Confirmar transferência'}}
function inject(){const g=document.getElementById('memberGroup')?.value;$$('#membersList .v7-list-row').forEach(row=>{if(row.querySelector('[data-v742-transfer-tools]'))return;const rm=row.querySelector('[data-rm-member]');if(!rm)return;const id=rm.dataset.rmMember,dests=g==='motorista'?['patrulheiro']:g==='patrulheiro'?['motorista','permanencia']:g==='permanencia'?['patrulheiro']:[];if(!dests.length)return;const marker=document.createElement('span');marker.dataset.v742TransferTools='1';marker.style.display='contents';for(const dest of dests){const t=document.createElement('button');t.type='button';t.className='v7-btn v742-transfer-btn';t.textContent=(g==='permanencia'?'↑ ':g==='motorista'||dest==='permanencia'?'↓ ':'↑ ')+groupLabel(dest);t.title=`Transferir de ${groupLabel(g)} para ${groupLabel(dest)} e colocar substituto na vaga`;t.onclick=()=>openTransfer(id,row,g,dest);marker.appendChild(t)}rm.parentNode.insertBefore(marker,rm)})}
function init(){ensureModal();new MutationObserver(inject).observe(document.body,{childList:true,subtree:true});setTimeout(inject,400);document.getElementById('memberGroup')?.addEventListener('change',()=>setTimeout(inject,90))}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
