(function(){
'use strict';
const KEY='tarefas_v743_period';
const $=s=>document.querySelector(s);
const page=(location.pathname.split('/').pop()||'').toLowerCase();
const enabled=page==='pessoal.html';
if(!enabled)return;
function pad(n){return String(n).padStart(2,'0')}
function iso(d){return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`}
function parse(s){const m=String(s||'').match(/^(\d{4})-(\d{2})-(\d{2})$/);return m?new Date(+m[1],+m[2]-1,+m[3]):new Date()}
function read(){let x=null;try{x=JSON.parse(localStorage.getItem(KEY)||'null')}catch(_){}const mode=['day','week','month'].includes(x?.mode)?x.mode:'day';const anchor=x?.anchor&&/^\d{4}-\d{2}-\d{2}$/.test(x.anchor)?x.anchor:iso(new Date());return{mode,anchor}}
function save(s){localStorage.setItem(KEY,JSON.stringify(s))}
function bounds(st=read()){const a=parse(st.anchor);a.setHours(0,0,0,0);let start=new Date(a),end=new Date(a);if(st.mode==='week'){start.setDate(start.getDate()-start.getDay());end=new Date(start);end.setDate(end.getDate()+6)}else if(st.mode==='month'){start=new Date(a.getFullYear(),a.getMonth(),1);end=new Date(a.getFullYear(),a.getMonth()+1,0)}return{...st,anchorDate:a,start,end,ini:iso(start),fim:iso(end)}}
function cap(s){return s.charAt(0).toUpperCase()+s.slice(1)}
function label(st=read()){const b=bounds(st);if(st.mode==='day')return cap(b.anchorDate.toLocaleDateString('pt-BR',{weekday:'long',day:'2-digit',month:'2-digit',year:'numeric'}));if(st.mode==='week')return `${b.start.toLocaleDateString('pt-BR')} — ${b.end.toLocaleDateString('pt-BR')}`;return cap(b.anchorDate.toLocaleDateString('pt-BR',{month:'long',year:'numeric'}))}
function shift(st,dir){const d=parse(st.anchor);if(st.mode==='day')d.setDate(d.getDate()+dir);else if(st.mode==='week')d.setDate(d.getDate()+7*dir);else d.setMonth(d.getMonth()+dir,1);return{mode:st.mode,anchor:iso(d)}}
function apply(st){save(st);const u=new URL(location.href);u.searchParams.set('_v755period',String(Date.now()));location.replace(u.href)}
function css(){if($('#v743PeriodCss'))return;const s=document.createElement('style');s.id='v743PeriodCss';s.textContent=`
.v743-period{display:grid;gap:7px;min-width:min(520px,100%)}.v743-modes{display:flex;gap:5px;flex-wrap:wrap}.v743-modes .v7-btn.active{background:var(--v4-accent);border-color:var(--v4-accent);color:#fff}.v743-nav{display:grid;grid-template-columns:38px minmax(180px,1fr) 42px 38px;gap:5px;align-items:center}.v743-nav .v743-label{min-height:38px;display:flex;align-items:center;justify-content:center;border:1px solid var(--v4-border);border-radius:8px;background:var(--v4-surface-2);font-size:10px;font-weight:900;text-align:center;padding:7px}.v743-cal{position:relative;overflow:hidden}.v743-cal input{position:absolute;inset:0;width:100%;height:100%;opacity:0;cursor:pointer}.v743-help{font-size:8px;color:var(--v4-muted);text-align:center}.v7-head .v7-month{display:none!important}@media(max-width:720px){.v743-period{width:100%;min-width:0}.v743-modes{display:grid;grid-template-columns:repeat(3,1fr)}.v743-nav{grid-template-columns:38px minmax(120px,1fr) 42px 38px}.v743-label{font-size:9px!important}}
`;document.head.appendChild(s)}
function build(){css();document.getElementById('v742Periods')?.remove();document.getElementById('v741Periods')?.remove();const actions=$('.v7-head .v7-actions');if(!actions||$('#v743Period'))return;const st=read(),b=bounds(st),wrap=document.createElement('div');wrap.id='v743Period';wrap.className='v743-period';const pickerType=st.mode==='month'?'month':'date';const pickerValue=st.mode==='month'?`${b.anchorDate.getFullYear()}-${pad(b.anchorDate.getMonth()+1)}`:st.anchor;wrap.innerHTML=`<div class="v743-modes"><button class="v7-btn ${st.mode==='day'?'active':''}" data-v743-mode="day">Dia</button><button class="v7-btn ${st.mode==='week'?'active':''}" data-v743-mode="week">Semana</button><button class="v7-btn ${st.mode==='month'?'active':''}" data-v743-mode="month">Mês</button></div><div class="v743-nav"><button class="v7-btn" data-v743-shift="-1" title="Anterior">←</button><div class="v743-label">${label(st)}</div><button class="v7-btn v743-cal" title="Escolher ${st.mode==='month'?'mês':'data'}">📅<input id="v743Picker" type="${pickerType}" value="${pickerValue}"></button><button class="v7-btn" data-v743-shift="1" title="Próximo">→</button></div><div class="v743-help">${st.mode==='day'?'Use as setas para trocar o dia ou o calendário para escolher qualquer data.':st.mode==='week'?'Semana operacional: domingo → sábado. Escolha qualquer data para abrir a semana correspondente.':'Use as setas para trocar o mês ou escolha diretamente no calendário.'}</div>`;actions.insertBefore(wrap,actions.firstChild);wrap.onclick=e=>{const m=e.target.closest('[data-v743-mode]');if(m){apply({mode:m.dataset.v743Mode,anchor:st.anchor});return}const sh=e.target.closest('[data-v743-shift]');if(sh){apply(shift(read(),Number(sh.dataset.v743Shift)));return}};const picker=wrap.querySelector('#v743Picker');picker.onchange=()=>{const cur=read();if(cur.mode==='month'){if(!/^\d{4}-\d{2}$/.test(picker.value))return;apply({mode:'month',anchor:picker.value+'-01'})}else if(/^\d{4}-\d{2}-\d{2}$/.test(picker.value))apply({mode:cur.mode,anchor:picker.value})};
 const summaryTexts=[['#serviceSummary small','Serviços no mês','Serviços no período']];for(const [sel,a,b2] of summaryTexts)document.querySelectorAll(sel).forEach(el=>{if(el.textContent.trim()===a)el.textContent=b2});
 document.documentElement.dataset.v743Mode=st.mode;window.dispatchEvent(new CustomEvent('v743:period',{detail:bounds(st)}));}
window.TAREFAS_PERIOD_V743={key:KEY,read,bounds,label,save,shift};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',build);else build();
})();