(function(){
'use strict';
if((location.pathname.split('/').pop()||'').toLowerCase()!=='pessoal.html')return;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let replaceData=null,replacePeople=null;
function user(){try{return JSON.parse(localStorage.getItem('usuarioLogado')||'null')}catch(_){return null}}
function pid(){const u=user();return u?.perfil_id?Number(u.perfil_id):null}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function norm(v){return String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase()}
function groupLabel(g){return g==='sargento'?'Sargentos':g==='motorista'?'Motoristas':g==='patrulheiro'?'Patrulheiros':g==='permanencia'?'Permanência':g==='canil'?'Permanência/Canil':g}
function modal(on){document.getElementById('v742DirectReplaceModal')?.classList.toggle('open',on)}
function ensureModal(){if($('#v742DirectReplaceModal'))return;const bg=document.createElement('div');bg.id='v742DirectReplaceModal';bg.className='v7-modal-bg';bg.innerHTML=`<div class="v7-modal" style="width:min(720px,100%)"><div class="v7-modal-head"><h3 id="v742DirectReplaceTitle">Trocar pessoa da escala</h3><button class="v7-close" data-v742-replace-close>×</button></div><div id="v742DirectReplaceSource" class="v742-transfer-person"></div><div class="v7-note" style="margin-top:9px">Esta opção <b>não transfere</b> o militar atual para outra escala. Ele sai da escala atual e o novo militar, que deve estar <b>fora de todas as escalas de serviço</b>, assume a mesma ordem e as referências de folga Preta/Vermelha da vaga.</div><div class="v7-field"><label>Novo militar *</label><input id="v742DirectReplaceSearch" class="v742-search-input" type="search" placeholder="Buscar militar fora das escalas..."><input id="v742DirectReplaceSelected" type="hidden"></div><div id="v742DirectReplaceCandidates" class="v742-candidates"></div><div class="v7-modal-actions"><button class="v7-btn" type="button" data-v742-replace-close>Cancelar</button><button class="v7-btn primary" type="button" id="v742DirectReplaceConfirm">Confirmar troca</button></div></div>`;document.body.appendChild(bg);bg.onclick=e=>{if(e.target===bg||e.target.closest('[data-v742-replace-close]'))modal(false)};$('#v742DirectReplaceSearch').oninput=renderCandidates;$('#v742DirectReplaceConfirm').onclick=confirmReplace}
async function loadPeople(){if(replacePeople)return replacePeople;const [u,e,m]=await Promise.all([supabaseClient.from('usuarios').select('id,patente,nome_guerra,secao,posicao,ativo').eq('ativo',true).order('nome_guerra'),supabaseClient.from('pessoal_nomes_externos').select('id,patente,nome,ativo').eq('ativo',true).order('nome'),supabaseClient.from('escala_integrantes').select('id,grupo,usuario_id,pessoa_externa_id,ativo').eq('ativo',true)]);for(const r of [u,e,m])if(r.error)throw r.error;const mem=m.data||[],usedU=new Set(mem.map(x=>x.usuario_id).filter(Boolean).map(String)),usedE=new Set(mem.map(x=>x.pessoa_externa_id).filter(Boolean).map(String));const rows=[...(u.data||[]).filter(x=>!usedU.has(String(x.id))).map(x=>({key:`u:${x.id}`,name:[x.patente,x.nome_guerra].filter(Boolean).join(' '),meta:[x.secao,x.posicao].filter(Boolean).join(' · ')||'Usuário do sistema'})),...(e.data||[]).filter(x=>!usedE.has(String(x.id))).map(x=>({key:`e:${x.id}`,name:[x.patente,x.nome].filter(Boolean).join(' '),meta:'Nome externo'}))];replacePeople={rows};return replacePeople}
function renderCandidates(){if(!replacePeople)return;const q=norm($('#v742DirectReplaceSearch').value),host=$('#v742DirectReplaceCandidates'),rows=replacePeople.rows.filter(x=>!q||norm(x.name+' '+x.meta).includes(q)).slice(0,80);host.innerHTML=rows.length?rows.map(x=>`<button type="button" class="v742-candidate" data-replace-key="${esc(x.key)}"><b>${esc(x.name)}</b><small>${esc(x.meta)} · Fora de todas as escalas de serviço</small></button>`).join(''):'<div class="v7-empty">Nenhum militar fora das escalas encontrado.</div>';host.onclick=e=>{const b=e.target.closest('[data-replace-key]');if(!b)return;host.querySelectorAll('.v742-candidate.active').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#v742DirectReplaceSelected').value=b.dataset.replaceKey}}
async function openReplace(id,row,group){try{ensureModal();const name=row.querySelector('b')?.childNodes?.[0]?.textContent?.trim()||row.querySelector('b')?.textContent?.trim()||'Militar';replaceData={id:Number(id),group,name};$('#v742DirectReplaceTitle').textContent=`Trocar integrante — ${groupLabel(group)}`;$('#v742DirectReplaceSource').innerHTML=`<b>${esc(name)}</b><small>${esc(groupLabel(group))}. O novo militar assumirá exatamente esta vaga.</small>`;$('#v742DirectReplaceSearch').value='';$('#v742DirectReplaceSelected').value='';$('#v742DirectReplaceCandidates').innerHTML='<div class="v7-empty">Carregando militares fora das escalas...</div>';modal(true);replacePeople=null;await loadPeople();renderCandidates()}catch(e){alert('Erro ao preparar a troca: '+(e.message||e))}}
async function confirmReplace(){const u=user(),value=$('#v742DirectReplaceSelected').value;if(!replaceData||!value)return alert('Selecione o novo militar.');if(!confirm(`${replaceData.name} sairá de ${groupLabel(replaceData.group)}. O novo militar assumirá a mesma vaga, ordem e referências de folga. Confirmar?`))return;const [kind,id]=value.split(':'),btn=$('#v742DirectReplaceConfirm');try{btn.disabled=true;btn.textContent='Trocando...';const r=await supabaseClient.rpc('v7_4_2_substituir_integrante_fora_escala',{p_integrante_origem_id:replaceData.id,p_substituto_usuario_id:kind==='u'?Number(id):null,p_substituto_pessoa_externa_id:kind==='e'?Number(id):null,p_usuario_id:Number(u.id),p_perfil_id:pid()});if(r.error)throw r.error;alert('Troca concluída. O novo militar assumiu a vaga com a mesma ordem e referências de folga.');location.reload()}catch(e){alert('Erro na troca de integrante: '+(e.message||e))}finally{btn.disabled=false;btn.textContent='Confirmar troca'}}
function inject(){const group=document.getElementById('memberGroup')?.value;$$('#membersList .v7-list-row').forEach(row=>{if(row.querySelector('[data-v742-direct-replace]'))return;const rm=row.querySelector('[data-rm-member]');if(!rm)return;const b=document.createElement('button');b.type='button';b.className='v7-btn v742-transfer-btn';b.dataset.v742DirectReplace='1';b.textContent='Trocar por fora da escala';b.title='Substituir por um militar que não esteja em nenhuma escala de serviço';b.onclick=()=>openReplace(rm.dataset.rmMember,row,group);rm.parentNode.insertBefore(b,rm)})}
function init(){ensureModal();new MutationObserver(inject).observe(document.body,{childList:true,subtree:true});setTimeout(inject,430);document.getElementById('memberGroup')?.addEventListener('change',()=>setTimeout(inject,100))}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
