(function(){
'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const page=(location.pathname.split('/').pop()||'').toLowerCase(),svc=page==='pessoal.html',mis=page==='missao.html';
if(!svc&&!mis)return;
let transferData=null,transferPeople=null,replaceData=null,replacePeople=null;
function user(){try{return JSON.parse(localStorage.getItem('usuarioLogado')||'null')}catch(_){return null}}
function pid(){const u=user();return u?.perfil_id?Number(u.perfil_id):null}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function norm(v){return String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase()}
function css(){if($('#v742PeopleCss'))return;const s=document.createElement('style');s.id='v742PeopleCss';s.textContent=`
.v742-search-select{position:relative}.v742-search-input{width:100%;border:1px solid var(--v4-border-strong);border-radius:8px;padding:10px;background:var(--v4-surface);color:var(--v4-text)}.v742-search-list{position:absolute;left:0;right:0;top:calc(100% + 4px);z-index:130500;display:none;max-height:260px;overflow:auto;background:var(--v4-surface);border:1px solid var(--v4-border);border-radius:9px;box-shadow:0 14px 34px rgba(0,0,0,.22);padding:5px}.v742-search-list.open{display:block}.v742-search-option{display:block;width:100%;border:0;background:transparent;color:var(--v4-text);text-align:left;padding:8px 9px;border-radius:7px;cursor:pointer;font-size:9px}.v742-search-option:hover{background:var(--v4-surface-2)}.v742-search-option small{display:block;color:var(--v4-muted);font-size:7.5px;margin-top:2px}.v742-order-tools{display:inline-flex;gap:4px;align-items:center}.v742-order-tools .v7-btn{padding:5px 7px}.v742-transfer-btn{white-space:nowrap}.v742-transfer-person{border:1px solid var(--v4-border);border-radius:8px;padding:9px;background:var(--v4-surface-2)}.v742-transfer-person b{display:block;font-size:11px}.v742-transfer-person small{display:block;margin-top:3px;color:var(--v4-muted);font-size:8px}.v742-candidates{max-height:260px;overflow:auto;display:grid;gap:5px;margin-top:7px}.v742-candidate{border:1px solid var(--v4-border);background:var(--v4-surface);color:var(--v4-text);border-radius:8px;padding:8px 9px;text-align:left;cursor:pointer}.v742-candidate:hover,.v742-candidate.active{border-color:var(--v4-accent);background:var(--v4-accent-soft)}.v742-candidate b{display:block;font-size:10px}.v742-candidate small{display:block;color:var(--v4-muted);font-size:8px;margin-top:2px}.v742-group-chip{display:inline-flex;border-radius:999px;padding:2px 5px;margin-left:4px;background:var(--v4-surface-3);font-size:6.5px;font-weight:900}
`;document.head.appendChild(s)}
function enhanceSelect(id){const select=document.getElementById(id);if(!select||select.dataset.v742Search)return;select.dataset.v742Search='1';const wrap=document.createElement('div');wrap.className='v742-search-select';const input=document.createElement('input');input.type='search';input.className='v742-search-input';input.placeholder='Buscar usuário do sistema...';input.autocomplete='off';const list=document.createElement('div');list.className='v742-search-list';select.parentNode.insertBefore(wrap,select);wrap.appendChild(input);wrap.appendChild(list);wrap.appendChild(select);select.style.display='none';
 function options(){return [...select.options].filter(o=>o.value&&!o.disabled).map(o=>({value:o.value,label:o.textContent.trim()}))}
 function render(){const q=norm(input.value),items=options().filter(o=>!q||norm(o.label).includes(q)).slice(0,80);list.innerHTML=items.length?items.map(o=>`<button type="button" class="v742-search-option" data-value="${esc(o.value)}"><b>${esc(o.label.split(' — ')[0])}</b><small>${esc(o.label.includes(' — ')?o.label.split(' — ').slice(1).join(' — '):'Usuário do sistema')}</small></button>`).join(''):'<div class="v7-empty" style="padding:14px">Nenhum usuário encontrado.</div>';list.classList.add('open')}
 input.addEventListener('focus',render);input.addEventListener('input',render);list.addEventListener('click',e=>{const b=e.target.closest('[data-value]');if(!b)return;select.value=b.dataset.value;select.dispatchEvent(new Event('change',{bubbles:true}));input.value=select.options[select.selectedIndex]?.textContent?.trim()||'';list.classList.remove('open')});document.addEventListener('pointerdown',e=>{if(!wrap.contains(e.target))list.classList.remove('open')});new MutationObserver(()=>{if(!select.value&&!document.activeElement?.isSameNode(input))input.value=''}).observe(select,{childList:true,subtree:true});
 const addBtn=document.getElementById(id==='memberUser'?'addMember':'addMissionMember');addBtn?.addEventListener('click',()=>setTimeout(()=>{if(!select.value)input.value=''},250));
}
function next(sel){const n=$$(sel+' .v7-mini').map(x=>Number((x.textContent.match(/Ordem\s+(\d+)/i)||[])[1])).filter(Number.isFinite);return Math.max(0,...n)+1}
function auto(){if(svc){const i=document.getElementById('memberOrder');if(i){i.readOnly=true;i.value=next('#membersList')}}else{const i=document.getElementById('missionMemberOrder');if(i){i.readOnly=true;i.value=next('#missionMembersList')}}}
async function move(id,dir){const u=user();if(!u?.id||typeof supabaseClient==='undefined')return;const rpc=svc?'v7_4_1_mover_integrante_escala':'v7_4_1_mover_integrante_missao',r=await supabaseClient.rpc(rpc,{p_integrante_id:Number(id),p_direcao:dir,p_usuario_id:Number(u.id),p_perfil_id:pid()});if(r.error)return alert(r.error.message);location.reload()}
function arrows(){const sel=svc?'#membersList .v7-list-row':'#missionMembersList .v7-list-row';$$(sel).forEach((row,i,all)=>{if(row.querySelector('[data-v742-order]'))return;const rm=row.querySelector(svc?'[data-rm-member]':'[data-rm-mission-member]');if(!rm)return;const id=svc?rm.dataset.rmMember:rm.dataset.rmMissionMember,box=document.createElement('span');box.dataset.v742Order='1';box.className='v742-order-tools';box.innerHTML=`<button type="button" class="v7-btn" ${i===0?'disabled':''} title="Subir na ordem">↑</button><button type="button" class="v7-btn" ${i===all.length-1?'disabled':''} title="Descer na ordem">↓</button>`;const [up,down]=box.querySelectorAll('button');up.onclick=()=>move(id,'up');down.onclick=()=>move(id,'down');rm.parentNode.insertBefore(box,rm);if(svc){const g=document.getElementById('memberGroup')?.value;const swap=document.createElement('button');swap.type='button';swap.className='v7-btn v742-transfer-btn';swap.textContent='Trocar por fora da escala';swap.title='Substituir por um militar que não esteja em nenhuma escala de serviço';swap.onclick=()=>openDirectReplace(id,row,g);rm.parentNode.insertBefore(swap,rm);const dests=g==='motorista'?['patrulheiro']:g==='patrulheiro'?['motorista','permanencia']:g==='permanencia'?['patrulheiro']:[];for(const dest of dests){const t=document.createElement('button');t.type='button';t.className='v7-btn v742-transfer-btn';t.dataset.v742Transfer=id;t.dataset.v742Dest=dest;t.textContent=(g==='permanencia'?'↑ ':g==='motorista'||dest==='permanencia'?'↓ ':'↑ ')+groupLabel(dest);t.title=`Transferir de ${groupLabel(g)} para ${groupLabel(dest)} e colocar substituto na vaga`;t.onclick=()=>openTransfer(id,row,g,dest);rm.parentNode.insertBefore(t,rm)}}});auto()}
function modal(on){document.getElementById('v742TransferModal')?.classList.toggle('open',on)}
function groupLabel(g){return g==='motorista'?'Motoristas':g==='patrulheiro'?'Patrulheiros':g==='permanencia'?'Permanência':g==='canil'?'Permanência/Canil':g}
function ensureTransferModal(){if(!svc||$('#v742TransferModal'))return;const bg=document.createElement('div');bg.id='v742TransferModal';bg.className='v7-modal-bg';bg.innerHTML=`<div class="v7-modal" style="width:min(720px,100%)"><div class="v7-modal-head"><h3 id="v742TransferTitle">Transferir / substituir</h3><button class="v7-close" data-v742-transfer-close>×</button></div><div id="v742TransferSource" class="v742-transfer-person"></div><div class="v7-note" style="margin-top:9px">O substituto assume a <b>mesma ordem da vaga</b> e continua as referências de folga <b>Preta e Vermelha</b>. O militar transferido entra no fim da nova escala e passa a contar folgas somente nela.</div><div class="v7-field"><label>Quem assumirá a vaga *</label><input id="v742TransferSearch" class="v742-search-input" type="search" placeholder="Buscar militar..."><input id="v742TransferSelected" type="hidden"></div><div id="v742TransferCandidates" class="v742-candidates"></div><div class="v7-modal-actions"><button class="v7-btn" type="button" data-v742-transfer-close>Cancelar</button><button class="v7-btn primary" type="button" id="v742TransferConfirm">Confirmar transferência</button></div></div>`;document.body.appendChild(bg);bg.onclick=e=>{if(e.target===bg||e.target.closest('[data-v742-transfer-close]'))modal(false)};$('#v742TransferSearch').oninput=renderCandidates;$('#v742TransferConfirm').onclick=confirmTransfer}
async function loadTransferPeople(origin){if(transferPeople?.origin===origin)return transferPeople;const [u,e,m]=await Promise.all([supabaseClient.from('usuarios').select('id,patente,nome_guerra,secao,posicao,ativo').eq('ativo',true).order('nome_guerra'),supabaseClient.from('pessoal_nomes_externos').select('id,patente,nome,ativo').eq('ativo',true).order('nome'),supabaseClient.from('escala_integrantes').select('id,grupo,usuario_id,pessoa_externa_id,ativo').eq('ativo',true)]);for(const r of [u,e,m])if(r.error)throw r.error;const mem=m.data||[],groupsFor=(kind,id)=>mem.filter(x=>(kind==='u'?String(x.usuario_id)===String(id):String(x.pessoa_externa_id)===String(id))).map(x=>x.grupo);const rows=[...(u.data||[]).map(x=>({key:`u:${x.id}`,name:[x.patente,x.nome_guerra].filter(Boolean).join(' '),meta:[x.secao,x.posicao].filter(Boolean).join(' · '),groups:groupsFor('u',x.id)})),...(e.data||[]).map(x=>({key:`e:${x.id}`,name:[x.patente,x.nome].filter(Boolean).join(' '),meta:'Nome externo',groups:groupsFor('e',x.id)}))].filter(x=>!x.groups.includes(origin));transferPeople={origin,rows};return transferPeople}
function renderCandidates(){if(!transferPeople)return;const q=norm($('#v742TransferSearch').value),host=$('#v742TransferCandidates'),rows=transferPeople.rows.filter(x=>!q||norm(x.name+' '+x.meta+' '+x.groups.join(' ')).includes(q)).slice(0,80);host.innerHTML=rows.length?rows.map(x=>`<button type="button" class="v742-candidate" data-key="${esc(x.key)}"><b>${esc(x.name)}</b><small>${esc(x.meta||'')}${x.groups.length?' · Escalas: '+x.groups.map(groupLabel).join(', '):' · Fora das escalas de serviço'}</small></button>`).join(''):'<div class="v7-empty">Nenhum militar encontrado.</div>';host.onclick=e=>{const b=e.target.closest('[data-key]');if(!b)return;$$('.v742-candidate.active').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#v742TransferSelected').value=b.dataset.key}}
async function openTransfer(id,row,origin,dest){try{ensureTransferModal();if(origin==='canil'||dest==='canil')return alert('Permanência/Canil é uma escala separada e não participa de transferências.');const name=row.querySelector('b')?.childNodes?.[0]?.textContent?.trim()||row.querySelector('b')?.textContent?.trim()||'Militar';transferData={id:Number(id),origin,dest,name};$('#v742TransferTitle').textContent=`Transferir ${groupLabel(origin)} → ${groupLabel(dest)}`;$('#v742TransferSource').innerHTML=`<b>${esc(name)}</b><small>${esc(groupLabel(origin))} → ${esc(groupLabel(dest))}. Um substituto assumirá a vaga atual.</small>`;$('#v742TransferSearch').value='';$('#v742TransferSelected').value='';$('#v742TransferCandidates').innerHTML='<div class="v7-empty">Carregando militares...</div>';modal(true);transferPeople=null;await loadTransferPeople(origin);renderCandidates()}catch(e){alert('Erro ao preparar transferência: '+(e.message||e))}}
async function confirmTransfer(){const u=user(),value=$('#v742TransferSelected').value;if(!transferData||!value)return alert('Selecione quem assumirá a vaga.');if(!confirm(`${transferData.name} irá para ${groupLabel(transferData.dest)}. O substituto escolhido assumirá a vaga em ${groupLabel(transferData.origin)} e herdará as folgas da vaga. Confirmar?`))return;const [kind,id]=value.split(':'),btn=$('#v742TransferConfirm');try{btn.disabled=true;btn.textContent='Transferindo...';const r=await supabaseClient.rpc('v7_4_2_transferir_substituir_integrante',{p_integrante_origem_id:transferData.id,p_grupo_destino:transferData.dest,p_substituto_usuario_id:kind==='u'?Number(id):null,p_substituto_pessoa_externa_id:kind==='e'?Number(id):null,p_usuario_id:Number(u.id),p_perfil_id:pid()});if(r.error)throw r.error;alert('Transferência concluída. A vaga manteve a ordem e as referências de folga.');location.reload()}catch(e){alert('Erro na transferência: '+(e.message||e))}finally{btn.disabled=false;btn.textContent='Confirmar transferência'}}
function replaceModal(on){document.getElementById('v742DirectReplaceModal')?.classList.toggle('open',on)}
function ensureDirectReplaceModal(){if(!svc||$('#v742DirectReplaceModal'))return;const bg=document.createElement('div');bg.id='v742DirectReplaceModal';bg.className='v7-modal-bg';bg.innerHTML=`<div class="v7-modal" style="width:min(720px,100%)"><div class="v7-modal-head"><h3 id="v742DirectReplaceTitle">Trocar pessoa da escala</h3><button class="v7-close" data-v742-replace-close>×</button></div><div id="v742DirectReplaceSource" class="v742-transfer-person"></div><div class="v7-note" style="margin-top:9px">Esta opção <b>não transfere</b> o militar atual para outra escala. Ele sai da escala atual e o novo militar, que deve estar <b>fora de todas as escalas de serviço</b>, assume a mesma ordem e as referências de folga Preta/Vermelha da vaga.</div><div class="v7-field"><label>Novo militar *</label><input id="v742DirectReplaceSearch" class="v742-search-input" type="search" placeholder="Buscar militar fora das escalas..."><input id="v742DirectReplaceSelected" type="hidden"></div><div id="v742DirectReplaceCandidates" class="v742-candidates"></div><div class="v7-modal-actions"><button class="v7-btn" type="button" data-v742-replace-close>Cancelar</button><button class="v7-btn primary" type="button" id="v742DirectReplaceConfirm">Confirmar troca</button></div></div>`;document.body.appendChild(bg);bg.onclick=e=>{if(e.target===bg||e.target.closest('[data-v742-replace-close]'))replaceModal(false)};$('#v742DirectReplaceSearch').oninput=renderDirectReplaceCandidates;$('#v742DirectReplaceConfirm').onclick=confirmDirectReplace}
async function loadDirectReplacePeople(){if(replacePeople)return replacePeople;const [u,e,m]=await Promise.all([supabaseClient.from('usuarios').select('id,patente,nome_guerra,secao,posicao,ativo').eq('ativo',true).order('nome_guerra'),supabaseClient.from('pessoal_nomes_externos').select('id,patente,nome,ativo').eq('ativo',true).order('nome'),supabaseClient.from('escala_integrantes').select('id,grupo,usuario_id,pessoa_externa_id,ativo').eq('ativo',true)]);for(const r of [u,e,m])if(r.error)throw r.error;const mem=m.data||[],usedU=new Set(mem.map(x=>x.usuario_id).filter(Boolean).map(String)),usedE=new Set(mem.map(x=>x.pessoa_externa_id).filter(Boolean).map(String));const rows=[...(u.data||[]).filter(x=>!usedU.has(String(x.id))).map(x=>({key:`u:${x.id}`,name:[x.patente,x.nome_guerra].filter(Boolean).join(' '),meta:[x.secao,x.posicao].filter(Boolean).join(' · ')||'Usuário do sistema'})),...(e.data||[]).filter(x=>!usedE.has(String(x.id))).map(x=>({key:`e:${x.id}`,name:[x.patente,x.nome].filter(Boolean).join(' '),meta:'Nome externo'}))];replacePeople={rows};return replacePeople}
function renderDirectReplaceCandidates(){if(!replacePeople)return;const q=norm($('#v742DirectReplaceSearch').value),host=$('#v742DirectReplaceCandidates'),rows=replacePeople.rows.filter(x=>!q||norm(x.name+' '+x.meta).includes(q)).slice(0,80);host.innerHTML=rows.length?rows.map(x=>`<button type="button" class="v742-candidate" data-replace-key="${esc(x.key)}"><b>${esc(x.name)}</b><small>${esc(x.meta)} · Fora de todas as escalas de serviço</small></button>`).join(''):'<div class="v7-empty">Nenhum militar fora das escalas encontrado.</div>';host.onclick=e=>{const b=e.target.closest('[data-replace-key]');if(!b)return;host.querySelectorAll('.v742-candidate.active').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#v742DirectReplaceSelected').value=b.dataset.replaceKey}}
async function openDirectReplace(id,row,group){try{ensureDirectReplaceModal();const name=row.querySelector('b')?.childNodes?.[0]?.textContent?.trim()||row.querySelector('b')?.textContent?.trim()||'Militar';replaceData={id:Number(id),group,name};$('#v742DirectReplaceTitle').textContent=`Trocar integrante — ${groupLabel(group)}`;$('#v742DirectReplaceSource').innerHTML=`<b>${esc(name)}</b><small>${esc(groupLabel(group))}. O novo militar assumirá exatamente esta vaga.</small>`;$('#v742DirectReplaceSearch').value='';$('#v742DirectReplaceSelected').value='';$('#v742DirectReplaceCandidates').innerHTML='<div class="v7-empty">Carregando militares fora das escalas...</div>';replaceModal(true);replacePeople=null;await loadDirectReplacePeople();renderDirectReplaceCandidates()}catch(e){alert('Erro ao preparar a troca: '+(e.message||e))}}
async function confirmDirectReplace(){const u=user(),value=$('#v742DirectReplaceSelected').value;if(!replaceData||!value)return alert('Selecione o novo militar.');if(!confirm(`${replaceData.name} sairá de ${groupLabel(replaceData.group)}. O novo militar assumirá a mesma vaga, ordem e referências de folga. Confirmar?`))return;const [kind,id]=value.split(':'),btn=$('#v742DirectReplaceConfirm');try{btn.disabled=true;btn.textContent='Trocando...';const r=await supabaseClient.rpc('v7_4_2_substituir_integrante_fora_escala',{p_integrante_origem_id:replaceData.id,p_substituto_usuario_id:kind==='u'?Number(id):null,p_substituto_pessoa_externa_id:kind==='e'?Number(id):null,p_usuario_id:Number(u.id),p_perfil_id:pid()});if(r.error)throw r.error;alert('Troca concluída. O novo militar assumiu a vaga com a mesma ordem e referências de folga.');location.reload()}catch(e){alert('Erro na troca de integrante: '+(e.message||e))}finally{btn.disabled=false;btn.textContent='Confirmar troca'}}
function init(){css();ensureTransferModal();ensureDirectReplaceModal();enhanceSelect(svc?'memberUser':'missionMemberUser');auto();new MutationObserver(()=>{arrows();enhanceSelect(svc?'memberUser':'missionMemberUser')}).observe(document.body,{childList:true,subtree:true});setTimeout(arrows,350);if(svc)document.getElementById('memberGroup')?.addEventListener('change',()=>setTimeout(arrows,80))}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
