(function(){
'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const page=(location.pathname.split('/').pop()||'').toLowerCase(),svc=page==='pessoal.html',mis=page==='missao.html';
if(!svc&&!mis)return;
function user(){try{return JSON.parse(localStorage.getItem('usuarioLogado')||'null')}catch(_){return null}}
function pid(){const u=user();return u?.perfil_id?Number(u.perfil_id):null}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function norm(v){return String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase()}
function css(){if($('#v742SearchOrderCss'))return;const s=document.createElement('style');s.id='v742SearchOrderCss';s.textContent=`
.v742-search-select{position:relative}.v742-search-input{width:100%;border:1px solid var(--v4-border-strong);border-radius:8px;padding:10px;background:var(--v4-surface);color:var(--v4-text)}.v742-search-list{position:absolute;left:0;right:0;top:calc(100% + 4px);z-index:130500;display:none;max-height:260px;overflow:auto;background:var(--v4-surface);border:1px solid var(--v4-border);border-radius:9px;box-shadow:0 14px 34px rgba(0,0,0,.22);padding:5px}.v742-search-list.open{display:block}.v742-search-option{display:block;width:100%;border:0;background:transparent;color:var(--v4-text);text-align:left;padding:8px 9px;border-radius:7px;cursor:pointer;font-size:9px}.v742-search-option:hover{background:var(--v4-surface-2)}.v742-search-option small{display:block;color:var(--v4-muted);font-size:7.5px;margin-top:2px}.v742-order-tools{display:inline-flex;gap:4px;align-items:center}.v742-order-tools .v7-btn{padding:5px 7px}.v742-transfer-btn{white-space:nowrap}.v742-transfer-person{border:1px solid var(--v4-border);border-radius:8px;padding:9px;background:var(--v4-surface-2)}.v742-transfer-person b{display:block;font-size:11px}.v742-transfer-person small{display:block;margin-top:3px;color:var(--v4-muted);font-size:8px}.v742-candidates{max-height:260px;overflow:auto;display:grid;gap:5px;margin-top:7px}.v742-candidate{border:1px solid var(--v4-border);background:var(--v4-surface);color:var(--v4-text);border-radius:8px;padding:8px 9px;text-align:left;cursor:pointer}.v742-candidate:hover,.v742-candidate.active{border-color:var(--v4-accent);background:var(--v4-accent-soft)}.v742-candidate b{display:block;font-size:10px}.v742-candidate small{display:block;color:var(--v4-muted);font-size:8px;margin-top:2px}
`;document.head.appendChild(s)}
function enhanceSelect(id){const select=document.getElementById(id);if(!select||select.dataset.v742Search)return;select.dataset.v742Search='1';const wrap=document.createElement('div');wrap.className='v742-search-select';const input=document.createElement('input');input.type='search';input.className='v742-search-input';input.placeholder='Buscar usuário do sistema...';input.autocomplete='off';const list=document.createElement('div');list.className='v742-search-list';select.parentNode.insertBefore(wrap,select);wrap.appendChild(input);wrap.appendChild(list);wrap.appendChild(select);select.style.display='none';
 function options(){return [...select.options].filter(o=>o.value&&!o.disabled).map(o=>({value:o.value,label:o.textContent.trim()}))}
 function render(){const q=norm(input.value),items=options().filter(o=>!q||norm(o.label).includes(q)).slice(0,80);list.innerHTML=items.length?items.map(o=>`<button type="button" class="v742-search-option" data-value="${esc(o.value)}"><b>${esc(o.label.split(' — ')[0])}</b><small>${esc(o.label.includes(' — ')?o.label.split(' — ').slice(1).join(' — '):'Usuário do sistema')}</small></button>`).join(''):'<div class="v7-empty" style="padding:14px">Nenhum usuário encontrado.</div>';list.classList.add('open')}
 input.addEventListener('focus',render);input.addEventListener('input',render);list.addEventListener('click',e=>{const b=e.target.closest('[data-value]');if(!b)return;select.value=b.dataset.value;select.dispatchEvent(new Event('change',{bubbles:true}));input.value=select.options[select.selectedIndex]?.textContent?.trim()||'';list.classList.remove('open')});document.addEventListener('pointerdown',e=>{if(!wrap.contains(e.target))list.classList.remove('open')});new MutationObserver(()=>{if(!select.value&&!document.activeElement?.isSameNode(input))input.value=''}).observe(select,{childList:true,subtree:true});
 const addBtn=document.getElementById(id==='memberUser'?'addMember':'addMissionMember');addBtn?.addEventListener('click',()=>setTimeout(()=>{if(!select.value)input.value=''},250));
}
function next(sel){const n=$$(sel+' .v7-mini').map(x=>Number((x.textContent.match(/Ordem\s+(\d+)/i)||[])[1])).filter(Number.isFinite);return Math.max(0,...n)+1}
function auto(){if(svc){const i=document.getElementById('memberOrder');if(i){i.readOnly=true;i.value=next('#membersList')}}else{const i=document.getElementById('missionMemberOrder');if(i){i.readOnly=true;i.value=next('#missionMembersList')}}}
async function move(id,dir){const u=user();if(!u?.id||typeof supabaseClient==='undefined')return;const rpc=svc?'v7_4_1_mover_integrante_escala':'v7_4_1_mover_integrante_missao',r=await supabaseClient.rpc(rpc,{p_integrante_id:Number(id),p_direcao:dir,p_usuario_id:Number(u.id),p_perfil_id:pid()});if(r.error)return alert(r.error.message);location.reload()}
function arrows(){const sel=svc?'#membersList .v7-list-row':'#missionMembersList .v7-list-row';$$(sel).forEach((row,i,all)=>{if(row.querySelector('[data-v742-order]'))return;const rm=row.querySelector(svc?'[data-rm-member]':'[data-rm-mission-member]');if(!rm)return;const id=svc?rm.dataset.rmMember:rm.dataset.rmMissionMember,box=document.createElement('span');box.dataset.v742Order='1';box.className='v742-order-tools';box.innerHTML=`<button type="button" class="v7-btn" ${i===0?'disabled':''} title="Subir na ordem">↑</button><button type="button" class="v7-btn" ${i===all.length-1?'disabled':''} title="Descer na ordem">↓</button>`;const [up,down]=box.querySelectorAll('button');up.onclick=()=>move(id,'up');down.onclick=()=>move(id,'down');rm.parentNode.insertBefore(box,rm)});auto()}
function init(){css();enhanceSelect(svc?'memberUser':'missionMemberUser');auto();new MutationObserver(()=>{arrows();enhanceSelect(svc?'memberUser':'missionMemberUser')}).observe(document.body,{childList:true,subtree:true});setTimeout(arrows,350);if(svc)document.getElementById('memberGroup')?.addEventListener('change',()=>setTimeout(arrows,80))}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
