(function(){
'use strict';
if((location.pathname.split('/').pop()||'').toLowerCase()!=='pessoal.html')return;
const $=id=>document.getElementById(id),MONTHS=['JANEIRO','FEVEREIRO','MARÇO','ABRIL','MAIO','JUNHO','JULHO','AGOSTO','SETEMBRO','OUTUBRO','NOVEMBRO','DEZEMBRO'],GDH=['JAN','FEV','MAR','ABR','MAI','JUN','JUL','AGO','SET','OUT','NOV','DEZ'],WEEK=['Domingo','Segunda-feira','Terça-feira','Quarta-feira','Quinta-feira','Sexta-feira','Sábado'];
const ROWS=[['sargento','COMANDANTE'],['motorista','MOTORISTA'],['patrulheiro','PATRULHEIRO'],['permanencia','PERMANÊNCIA'],['canil','PERMANÊNCIA/CANIL']];
const pad=n=>String(n).padStart(2,'0'),parse=s=>{const[y,m,d]=String(s).split('-').map(Number);return new Date(y,m-1,d)},iso=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`,add=(s,n)=>{const d=parse(s);d.setDate(d.getDate()+n);return iso(d)},clean=v=>String(v??'').trim();
const full=s=>{const d=parse(s);return `${pad(d.getDate())} DE ${MONTHS[d.getMonth()]} DE ${d.getFullYear()}`},week=s=>WEEK[parse(s).getDay()],fileDate=s=>{const d=parse(s);return `${pad(d.getDate())}-${pad(d.getMonth()+1)}-${d.getFullYear()}`};
const key=x=>x?.usuario_id?`u:${x.usuario_id}`:x?.pessoa_externa_id?`e:${x.pessoa_externa_id}`:'',move=(q,k)=>{const i=q.indexOf(k);if(i>=0){q.splice(i,1);q.push(k)}};
function gdh(date,time){const d=parse(date),m=String(time||'').match(/^(\d{2}):(\d{2})/);return m?`${pad(d.getDate())}${m[1]}${m[2]} ${GDH[d.getMonth()]} ${String(d.getFullYear()).slice(-2)}`:''}
function ready(v){return v==='pelotao'?'prontos no pelotão':v==='local'?'prontos no local':''}
function pass(v){const m=String(v||'').match(/^(\d{2}):(\d{2})/);return m?`${m[1]}:${m[2]}h`:'08:00h'}
function injectStyle(){if($('v747AditStyle'))return;const s=document.createElement('style');s.id='v747AditStyle';s.textContent='.v731-adit-day{grid-template-columns:minmax(150px,.8fr) minmax(150px,.8fr) minmax(210px,1.1fr) auto!important}@media(max-width:800px){.v731-adit-day{grid-template-columns:1fr!important}}';document.head.appendChild(s)}
function enhanceRows(){injectStyle();document.querySelectorAll('[data-aditamento-dia]').forEach(row=>{if(row.querySelector('[data-v747-pass]'))return;const first=row.querySelector('.v731-adit-date');if(!first)return;const box=document.createElement('div');box.className='v731-adit-date';box.dataset.v747Pass='1';box.innerHTML='<label>Passagem de serviço</label><input type="time" data-aditamento-passagem value="08:00">';first.after(box)})}
function days(){enhanceRows();const out=[],seen=new Set();document.querySelectorAll('[data-aditamento-dia]').forEach(row=>{const date=row.querySelector('[data-aditamento-date]')?.value;if(!date||seen.has(date))return;seen.add(date);out.push({date,passageTime:row.querySelector('[data-aditamento-passagem]')?.value||'08:00',includeStandby:!!row.querySelector('[data-aditamento-standby]')?.checked})});return out.sort((a,b)=>a.date.localeCompare(b.date))}
async function jsPDF(){if(window.jspdf?.jsPDF)return window.jspdf.jsPDF;await new Promise((ok,no)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/jspdf@2.5.2/dist/jspdf.umd.min.js';s.onload=ok;s.onerror=no;document.head.appendChild(s)});if(!window.jspdf?.jsPDF)throw new Error('Biblioteca de PDF indisponível.');return window.jspdf.jsPDF}
function dataUrl(blob){return new Promise((ok,no)=>{const r=new FileReader();r.onload=()=>ok(r.result);r.onerror=no;r.readAsDataURL(blob)})}
async function logo(){for(const src of ['brasao_exercito_v742.png?v=7.4.7','brasao_exercito.png?v=7.4.7'])try{const r=await fetch(src,{cache:'reload'});if(r.ok)return await dataUrl(await r.blob())}catch(_){}return null}
async function rows(table,ids,cols){if(!ids.length)return[];const r=await supabaseClient.from(table).select(cols).in('id',ids);if(r.error)throw r.error;return r.data||[]}
function holiday(c,date){return c.holidays.has(date)}
function lane(c,date){const d=parse(date);return d.getDay()===0||d.getDay()===6||holiday(c,date)?'vermelha':'preta'}
function vacation(c,row,date){return c.vac.find(v=>((row.usuario_id&&String(v.usuario_id)===String(row.usuario_id))||(row.pessoa_externa_id&&String(v.pessoa_externa_id)===String(row.pessoa_externa_id)))&&v.data_inicio<=date&&v.data_fim>=date)}
function adp(c,row,date){return c.vac.find(v=>((row.usuario_id&&String(v.usuario_id)===String(row.usuario_id))||(row.pessoa_externa_id&&String(v.pessoa_externa_id)===String(row.pessoa_externa_id)))&&add(v.data_fim,1)===date)}
function eligible(c,row,date){return !vacation(c,row,date)&&!adp(c,row,date)}
async function context(opts){
 const dates=opts.map(x=>x.date),min=dates[0],max=dates[dates.length-1],ext=add(min,-365);
 const [sv,hist,mi,mem,hol,vac]=await Promise.all([
  supabaseClient.from('escala_servicos').select('id,grupo,usuario_id,pessoa_externa_id,data_servico,marcacao').in('data_servico',dates).order('data_servico').order('grupo').order('id'),
  supabaseClient.from('escala_servicos').select('id,grupo,usuario_id,pessoa_externa_id,data_servico,marcacao').gte('data_servico',ext).lte('data_servico',max).order('data_servico').order('grupo').order('id'),
  supabaseClient.from('missoes_escala').select('id,titulo,data_inicio,data_fim,horario,pronto_em,local,descricao').lte('data_inicio',max).gte('data_fim',min).order('data_inicio').order('id'),
  supabaseClient.from('escala_integrantes').select('id,grupo,usuario_id,pessoa_externa_id,ordem,ativo,heranca_preta_data,heranca_vermelha_data').eq('ativo',true).order('grupo').order('ordem').order('id'),
  supabaseClient.from('escala_feriados').select('data').gte('data',ext).lte('data',max),
  supabaseClient.from('pessoal_ferias').select('usuario_id,pessoa_externa_id,data_inicio,data_fim').lte('data_inicio',max).gte('data_fim',ext)
 ]);for(const r of[sv,hist,mi,mem,hol,vac])if(r.error)throw r.error;
 const missions=(mi.data||[]).filter(m=>dates.some(d=>m.data_inicio<=d&&m.data_fim>=d)),ids=missions.map(x=>x.id);let parts=[];
 if(ids.length){const p=await supabaseClient.from('missao_participantes').select('id,missao_id,usuario_id,pessoa_externa_id').in('missao_id',ids).order('id');if(p.error)throw p.error;parts=p.data||[]}
 const all=[...(sv.data||[]),...(hist.data||[]),...(mem.data||[]),...parts],uids=[...new Set(all.map(x=>x.usuario_id).filter(Boolean).map(Number))],eids=[...new Set(all.map(x=>x.pessoa_externa_id).filter(Boolean).map(Number))];
 const [us,ex]=await Promise.all([rows('usuarios',uids,'id,patente,nome_guerra,nome_completo'),rows('pessoal_nomes_externos',eids,'id,patente,nome')]);const um=new Map(us.map(x=>[String(x.id),x])),em=new Map(ex.map(x=>[String(x.id),x]));
 const person=x=>{if(x?.usuario_id){const u=um.get(String(x.usuario_id));return{grad:clean(u?.patente),nome:clean(u?.nome_guerra||u?.nome_completo)}}if(x?.pessoa_externa_id){const e=em.get(String(x.pessoa_externa_id));return{grad:clean(e?.patente),nome:clean(e?.nome)}}return{grad:'',nome:''}};
 const c={services:sv.data||[],history:hist.data||[],missions,parts,members:mem.data||[],holidays:new Set((hol.data||[]).map(x=>x.data)),vac:vac.data||[],person};c.days=opts.map(o=>({...o,services:c.services.filter(x=>x.data_servico===o.date)}));for(const d of c.days)d.standby=standby(c,d.date);return c
}
function service(c,d,g){const p=d.services.filter(x=>x.grupo===g).map(c.person);return{grad:[...new Set(p.map(x=>x.grad).filter(Boolean))].join(' / '),nome:p.map(x=>x.nome).filter(Boolean).join(', ')}}
function standby(c,date){const out=new Map(),ln=lane(c,date);for(const [g] of ROWS){const actual=c.services.filter(x=>x.data_servico===date&&x.grupo===g);if(!actual.length){out.set(g,{grad:'',nome:''});continue}const rs=c.members.filter(x=>x.grupo===g).sort((a,b)=>(a.ordem||100)-(b.ordem||100)||Number(a.id)-Number(b.id)),keys=rs.map(key).filter(Boolean);if(!keys.length){out.set(g,{grad:'',nome:''});continue}let q=[...keys],conf=c.history.filter(x=>x.grupo===g&&keys.includes(key(x))&&lane(c,x.data_servico)===ln&&x.data_servico<=date);for(const r of rs){const inh=ln==='vermelha'?r.heranca_vermelha_data:r.heranca_preta_data;if(inh&&inh<=date&&!conf.some(x=>key(x)===key(r)&&x.data_servico>=inh))conf.push({id:-Number(r.id||0),grupo:g,data_servico:inh,usuario_id:r.usuario_id,pessoa_externa_id:r.pessoa_externa_id})}conf.sort((a,b)=>a.data_servico.localeCompare(b.data_servico)||Number(a.id)-Number(b.id));if(!conf.length){out.set(g,{grad:'',nome:''});continue}let day=conf[0].data_servico;while(day<=date){if(lane(c,day)!==ln){day=add(day,1);continue}const acts=conf.filter(x=>x.data_servico===day);if(acts.length)acts.forEach(a=>move(q,key(a)));else if(day<date){let idx=-1;for(let i=0;i<q.length;i++){const r=rs.find(z=>key(z)===q[i]);if(r&&eligible(c,r,day)){idx=i;break}}if(idx>=0){const[k]=q.splice(idx,1);q.push(k)}}day=add(day,1)}const used=new Set(actual.map(key));let r=null;for(const k of q){const z=rs.find(x=>key(x)===k);if(z&&!used.has(k)&&eligible(c,z,date)){r=z;break}}out.set(g,r?c.person(r):{grad:'',nome:''})}return out}
function missionPeople(c,id){return c.parts.filter(x=>String(x.missao_id)===String(id)).map(c.person).map(x=>[x.grad,x.nome].filter(Boolean).join(' '))}
function table(doc,c,d,y,over=false){const x=[17,72,94,193],hh=7,rh=7;doc.setFillColor(225);doc.rect(x[0],y,x[3]-x[0],hh,'F');doc.setDrawColor(40);doc.rect(x[0],y,x[3]-x[0],hh);for(let i=1;i<3;i++)doc.line(x[i],y,x[i],y+hh);doc.setFont('times','bold');doc.setFontSize(9.3);doc.text('FUNÇÃO',(x[0]+x[1])/2,y+4.7,{align:'center'});doc.text('GRAD.',(x[1]+x[2])/2,y+4.7,{align:'center'});doc.text('NOME',(x[2]+x[3])/2,y+4.7,{align:'center'});y+=hh;doc.setFont('times','normal');for(const [g,f] of ROWS){const p=over?(d.standby.get(g)||{grad:'',nome:''}):service(c,d,g);doc.rect(x[0],y,x[3]-x[0],rh);for(let i=1;i<3;i++)doc.line(x[i],y,x[i],y+rh);doc.text(f,(x[0]+x[1])/2,y+4.7,{align:'center'});doc.text(p.grad,(x[1]+x[2])/2,y+4.7,{align:'center'});doc.text(doc.splitTextToSize(String(p.nome||'').toLocaleUpperCase('pt-BR'),95),(x[2]+x[3])/2,y+4.7,{align:'center'});y+=rh}return y}
async function build(c){const J=await jsPDF(),doc=new J({orientation:'portrait',unit:'mm',format:'a4'}),border=()=>{doc.setDrawColor(15,23,42);doc.setLineWidth(.55);doc.rect(8,7,194,283);doc.setLineWidth(.18);doc.rect(10,9,190,279)},center=(t,y,s=10,b=false)=>{doc.setFont('times',b?'bold':'normal');doc.setFontSize(s);doc.text(String(t),105,y,{align:'center'})},newPage=()=>{doc.addPage();border();return 17},ensure=(y,n)=>y+n>280?newPage():y;border();let y=14,l=await logo();if(l)try{doc.addImage(l,'PNG',96,13,18,19)}catch(_){}y=36;center('MINISTÉRIO DA DEFESA',y);y+=4;center('EXÉRCITO BRASILEIRO',y);y+=4;center('26º PELOTÃO DE POLÍCIA DO EXÉRCITO MECANIZADO',y,10,true);y+=8;const first=c.days[0].date,intro=`ADITAMENTO AO BOLETIM INTERNO DA 6ª BRIGADA DE INFANTARIA BLINDADA,\nDO DIA ${full(add(first,-1))}, PARA O CONHECIMENTO DO PELOTÃO E A DEVIDA\nEXECUÇÃO, PUBLICO O SEGUINTE:`;doc.setFont('times','bold');doc.setFontSize(9.6);doc.text(intro.split('\n'),105,y,{align:'center'});y+=15;center('1ª PARTE - SERVIÇOS DIÁRIOS',y,10.5,true);y+=8;for(const d of c.days){y=ensure(y,58);center(`SERVIÇO PARA O DIA ${full(d.date)} (${week(d.date)})`,y,9.6,true);y+=3;y=table(doc,c,d,y,false);y+=5;doc.setFont('times','bold');doc.setFontSize(9.5);doc.text(`- PASSAGEM DE SERVIÇO ÀS ${pass(d.passageTime)}.`,17,y);y+=12}for(const d of c.days.filter(x=>x.includeStandby)){y=ensure(y,54);center(`SOBREAVISO PARA O DIA ${full(d.date)} (${week(d.date)})`,y,9.6,true);y+=3;y=table(doc,c,d,y,true);y+=10}y=ensure(y,30);center('2ª PARTE - INSTRUÇÃO:',y,10,true);doc.setFont('times','normal');doc.setFontSize(9.5);doc.text('Sem alteração.',105,y+4,{align:'center'});y+=14;center('3ª PARTE - ASSUNTOS GERAIS E ADMINISTRATIVOS:',y,10,true);y+=8;if(!c.missions.length){doc.text('Sem alteração.',105,y,{align:'center'});y+=8}else for(const m of c.missions){const gd=gdh(m.data_inicio,m.horario),rd=ready(m.pronto_em);if(!gd)throw new Error(`A missão "${m.titulo}" está sem horário.`);if(!rd)throw new Error(`A missão "${m.titulo}" está sem apresentação.`);const pp=missionPeople(c,m.id),lines=[['Missão:',`${clean(m.titulo)};`],['Data/Hora:',`${gd}, ${rd};`],['Local:',`${clean(m.local)||'-'}; e`],['Militares:',pp.length?pp.join(', '):'Nenhum participante cadastrado']];if(clean(m.descricao))lines.push(['Observação:',m.descricao]);y=ensure(y,lines.length*6+6);for(const[a,b]of lines){doc.setFont('times','bold');doc.setFontSize(9.3);doc.text(a,17,y);doc.setFont('times','normal');const xx=17+doc.getTextWidth(a)+2.2,wr=doc.splitTextToSize(String(b),193-xx);doc.text(wr,xx,y);y+=Math.max(1,wr.length)*4.2}y+=4}y=ensure(y,34);y+=3;center('4ª PARTE - JUSTIÇA E DISCIPLINA:',y,10,true);doc.setFont('times','normal');doc.setFontSize(9.5);doc.text('Sem alteração.',105,y+4,{align:'center'});y+=24;center('GUILLEN GABRIEL DOS SANTOS SILVA - 1º Ten',y,10.5,true);y+=4.5;center('Comandante do 26º Pelotão de Polícia do Exército Mecanizado',y,9.5);return doc}
async function generate(e){e.preventDefault();e.stopImmediatePropagation();const btn=$('aditamentoGerar'),ds=days();if(!ds.length)return alert('Adicione pelo menos um dia ao aditamento.');try{btn.disabled=true;btn.textContent='Gerando PDF V7.4.7...';const c=await context(ds),doc=await build(c),a=ds[0].date,b=ds[ds.length-1].date,name=`Aditamento_${a===b?fileDate(a):fileDate(a)+'_a_'+fileDate(b)}.pdf`;doc.save(name);$('aditamentoModal')?.classList.remove('open')}catch(err){console.error(err);alert('Erro ao gerar aditamento: '+(err?.message||err))}finally{btn.disabled=false;btn.textContent='Gerar PDF'}}
function bind(){const host=$('aditamentoDias'),go=$('aditamentoGerar');if(!host||!go)return;enhanceRows();new MutationObserver(enhanceRows).observe(host,{childList:true,subtree:true});go.addEventListener('click',generate,true)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind);else bind();
})();