(function(){
'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const page=(location.pathname.split('/').pop()||'').toLowerCase(),svc=page==='pessoal.html',mis=page==='missao.html';if(!svc&&!mis)return;
function next(sel){const n=$$(sel+' .v7-mini').map(x=>Number((x.textContent.match(/Ordem\s+(\d+)/i)||[])[1])).filter(Number.isFinite);return Math.max(0,...n)+1}
function auto(){if(svc){const i=document.getElementById('memberOrder'),b=document.getElementById('addMember');if(i){i.readOnly=true;i.value=next('#membersList')}if(b&&!b.dataset.v741){b.dataset.v741='1';b.addEventListener('click',()=>{if(i)i.value=next('#membersList')},true)}}else{const i=document.getElementById('missionMemberOrder'),b=document.getElementById('addMissionMember');if(i){i.readOnly=true;i.value=next('#missionMembersList')}if(b&&!b.dataset.v741){b.dataset.v741='1';b.addEventListener('click',()=>{if(i)i.value=next('#missionMembersList')},true)}}}
async function move(id,dir){const u=(()=>{try{return JSON.parse(localStorage.getItem('usuarioLogado')||'null')}catch(_){return null}})();if(!u?.id||typeof supabaseClient==='undefined')return;const rpc=svc?'v7_4_1_mover_integrante_escala':'v7_4_1_mover_integrante_missao',r=await supabaseClient.rpc(rpc,{p_integrante_id:Number(id),p_direcao:dir,p_usuario_id:Number(u.id),p_perfil_id:u.perfil_id?Number(u.perfil_id):null});if(r.error)return alert(r.error.message);location.reload()}
function arrows(){const sel=svc?'#membersList .v7-list-row':'#missionMembersList .v7-list-row';$$(sel).forEach((row,i,all)=>{if(row.querySelector('[data-v741-order]'))return;const rm=row.querySelector(svc?'[data-rm-member]':'[data-rm-mission-member]');if(!rm)return;const id=svc?rm.dataset.rmMember:rm.dataset.rmMissionMember,box=document.createElement('span');box.dataset.v741Order='1';box.style.cssText='display:inline-flex;gap:4px;margin-right:5px';box.innerHTML=`<button type="button" class="v7-btn" ${i===0?'disabled':''}>↑</button><button type="button" class="v7-btn" ${i===all.length-1?'disabled':''}>↓</button>`;const [up,down]=box.querySelectorAll('button');up.onclick=()=>move(id,'up');down.onclick=()=>move(id,'down');rm.parentNode.insertBefore(box,rm)});auto()}
function init(){auto();new MutationObserver(arrows).observe(document.body,{childList:true,subtree:true});setTimeout(arrows,400)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
