(function(){
'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const page=(location.pathname.split('/').pop()||'').toLowerCase();
const svc=page==='pessoal.html',mis=page==='missao.html';
if(!svc&&!mis)return;

const CFG=window.TAREFAS_PDF_V742=Object.assign({
 crest:'brasao_exercito.png?v=7.4.2',
 unit:'26º PELOTÃO DE POLÍCIA DO EXÉRCITO MECANIZADO',
 serviceTitle:'ESCALA DE SERVIÇO',missionTitle:'ESCALA DE MISSÃO',
 footer:'26º PELOTÃO DE POLÍCIA DO EXÉRCITO MECANIZADO',
 marginX:10,headerY:8,tableFont:7.4,nameWidth:43,rowHeight:5.3,
 colors:{dark:[31,36,41],red:[185,35,35],weekend:[255,243,243],grid:[75,82,88],text:[20,24,28],muted:[100,105,110],service:[236,253,245],pred:[255,251,220],vac:[239,246,255],adp:[244,244,245]}
},window.TAREFAS_PDF_V742||{});

function loadScript(src,test){return new Promise((ok,no)=>{if(test())return ok();const old=[...document.scripts].find(s=>s.src.includes(src.split('/').pop().split('@')[0]));if(old){old.addEventListener('load',()=>ok(),{once:true});setTimeout(()=>test()?ok():no(new Error('Biblioteca não disponível.')),3000);return}const s=document.createElement('script');s.src=src;s.onload=()=>test()?ok():no(new Error('Biblioteca carregada sem API esperada.'));s.onerror=()=>no(new Error('Falha ao carregar biblioteca de PDF.'));document.head.appendChild(s)})}
async function libs(){await loadScript('https://cdn.jsdelivr.net/npm/jspdf@2.5.2/dist/jspdf.umd.min.js',()=>!!window.jspdf?.jsPDF);await loadScript('https://cdn.jsdelivr.net/npm/jspdf-autotable@3.8.4/dist/jspdf.plugin.autotable.min.js',()=>!!window.jspdf?.jsPDF?.API?.autoTable)}
function dataUrl(blob){return new Promise((ok,no)=>{const r=new FileReader();r.onload=()=>ok(r.result);r.onerror=no;r.readAsDataURL(blob)})}
async function crest(){try{const r=await fetch(CFG.crest,{cache:'force-cache'});if(!r.ok)return null;return await dataUrl(await r.blob())}catch(_){return null}}
function modal(on){document.getElementById('v742PdfModal')?.classList.toggle('open',on)}
function groupNames(){return svc?['Sargentos','Motoristas','Patrulheiros','Permanência','Permanência/Canil']:['Sargentos','Cabos','Soldados']}
function periodText(){const active=$('#v742Periods .active')?.textContent?.trim()||'Mês',label=document.getElementById('monthLabel')?.textContent?.trim()||'';return active==='Mês'?(label||'Mês exibido'):active}
function cleanText(v){return String(v??'').replace(/\s+/g,' ').trim()}
function cleanNameCell(cell){const c=cell.cloneNode(true);c.querySelectorAll('button,.v7-online,.v721-person-meta,.v74-member-meta,.v72-external-tag,.v741-order-tools,.v742-order-tools').forEach(x=>x.remove());return cleanText(c.textContent)}
function visibleCell(c){return c.style.display!=='none'&&getComputedStyle(c).display!=='none'}
function tableData(panel){const table=panel.querySelector('.v7-table');if(!table)return null;const headRow=table.tHead?.rows?.[0];if(!headRow)return null;const allHeads=[...headRow.cells],visibleIndexes=allHeads.map((c,i)=>visibleCell(c)?i:-1).filter(i=>i>=0);const heads=visibleIndexes.map(i=>cleanText(allHeads[i].innerText));const weekendCols=new Set();visibleIndexes.forEach((orig,newIndex)=>{if(allHeads[orig].classList.contains('weekend'))weekendCols.add(newIndex)});const body=[...table.tBodies].flatMap(tb=>[...tb.rows]).map(row=>visibleIndexes.map((orig,newIndex)=>{const cell=row.cells[orig];if(!cell)return'';return newIndex===0?cleanNameCell(cell):cleanText(cell.innerText)}));return{heads,body,weekendCols}}
function selectedPanels(){const chosen=new Set($$('[data-v742-pdf-group]:checked').map(x=>x.dataset.v742PdfGroup));const root=svc?'#scaleBoard':'#missionScaleBoard';return $$(root+' .v7-panel').filter(p=>chosen.has(cleanText(p.querySelector('.v7-panel-head h3')?.textContent)))}
function cellKind(text){const t=cleanText(text).toUpperCase();if(t==='SV'||t==='MS'||t==='MIS')return'service';if(t==='PREV'||t==='PRV')return'pred';if(t.includes('FÉRIAS'))return'vac';if(t==='ADP')return'adp';return''}
function drawHeader(doc,img,pageNo){const W=doc.internal.pageSize.getWidth();if(img){try{doc.addImage(img,'PNG',W/2-6,5,12,12)}catch(_){try{doc.addImage(img,'JPEG',W/2-6,5,12,12)}catch(__){}}}doc.setTextColor(...CFG.colors.text);doc.setFont('helvetica','bold');doc.setFontSize(14);doc.text(CFG.unit,W/2,21,{align:'center'});doc.setFontSize(11);doc.text(svc?CFG.serviceTitle:CFG.missionTitle,W/2,27,{align:'center'});doc.setFont('helvetica','normal');doc.setFontSize(8);doc.text(`Período: ${periodText()}  •  Gerado em: ${new Date().toLocaleDateString('pt-BR')}`,W/2,32,{align:'center'});doc.setDrawColor(120);doc.setLineWidth(.2);doc.line(CFG.marginX,35,W-CFG.marginX,35)}
function drawLegend(doc,y){const items=[['Preta','dias úteis',CFG.colors.dark],['Vermelha','sábados, domingos e feriados',CFG.colors.red],['SV','serviço',null],['PREV','previsão',null],['ADP','adaptação',null],['FÉRIAS','afastado',null]];let x=CFG.marginX;const widths=[34,61,33,36,34,38];doc.setFontSize(7.5);items.forEach((it,i)=>{const w=widths[i];doc.setDrawColor(120);doc.roundedRect(x,y,w,7,1,1);if(it[2]){doc.setFillColor(...it[2]);doc.roundedRect(x+2,y+1.3,13,4.4,.7,.7,'F');doc.setTextColor(255);doc.setFont('helvetica','bold');doc.text(it[0],x+8.5,y+4.3,{align:'center'});doc.setTextColor(...CFG.colors.text);doc.setFont('helvetica','normal');doc.text('= '+it[1],x+16.5,y+4.3)}else{doc.setFont('helvetica','bold');doc.text(it[0],x+3,y+4.3);doc.setFont('helvetica','normal');doc.text('= '+it[1],x+14,y+4.3)}x+=w+2});return y+10}
function drawFooter(doc,page,total){const W=doc.internal.pageSize.getWidth(),H=doc.internal.pageSize.getHeight();doc.setDrawColor(130);doc.setLineWidth(.2);doc.line(CFG.marginX,H-9,W-CFG.marginX,H-9);doc.setTextColor(...CFG.colors.muted);doc.setFont('helvetica','normal');doc.setFontSize(6.8);doc.text(CFG.footer,W/2,H-5,{align:'center'});doc.text(`Página ${page} de ${total}`,W-CFG.marginX,H-5,{align:'right'})}
function titleBar(doc,title,y){const W=doc.internal.pageSize.getWidth();doc.setFillColor(...CFG.colors.dark);doc.roundedRect(CFG.marginX,y,W-CFG.marginX*2,6,1,1,'F');doc.setTextColor(255);doc.setFont('helvetica','bold');doc.setFontSize(9.5);doc.text(title.toUpperCase(),W/2,y+4.2,{align:'center'});doc.setTextColor(...CFG.colors.text);return y+6.5}
function ensureModal(){document.getElementById('v741PdfModal')?.remove();document.getElementById('v741PdfBtn')?.remove();if($('#v742PdfModal'))return;const bg=document.createElement('div');bg.id='v742PdfModal';bg.className='v7-modal-bg';bg.innerHTML=`<div class="v7-modal" style="width:min(600px,100%)"><div class="v7-modal-head"><h3>Gerar tabela PDF <small style="font-size:9px;color:var(--v4-muted)">V7.4.2</small></h3><button class="v7-close" data-v742-pdf-close>×</button></div><div class="v7-note">O PDF é montado como <b>tabela editável pelo template do sistema</b>, com bordas, cabeçalhos, fins de semana destacados e quebra automática de páginas.</div><div style="display:grid;gap:7px">${groupNames().map(g=>`<label style="display:flex;gap:8px;align-items:center;border:1px solid var(--v4-border);border-radius:8px;padding:9px"><input type="checkbox" data-v742-pdf-group="${g}" checked> ${g}</label>`).join('')}<label style="display:flex;gap:8px;align-items:center"><input type="checkbox" id="v742Legend" checked> Incluir legenda</label></div><div class="v7-modal-actions"><button type="button" class="v7-btn" data-v742-pdf-close>Cancelar</button><button type="button" class="v7-btn primary" id="v742GoPdf">Gerar PDF</button></div></div>`;document.body.appendChild(bg);bg.onclick=e=>{if(e.target===bg||e.target.closest('[data-v742-pdf-close]'))modal(false)};$('#v742GoPdf').onclick=generate}
async function generate(){const panels=selectedPanels();if(!panels.length)return alert('Selecione pelo menos uma tabela.');const btn=$('#v742GoPdf');try{if(btn){btn.disabled=true;btn.textContent='Gerando...'}await libs();const img=await crest(),{jsPDF}=window.jspdf,doc=new jsPDF({orientation:'landscape',unit:'mm',format:'a4'});let y=40;if($('#v742Legend')?.checked)y=drawLegend(doc,y);for(const panel of panels){const title=cleanText(panel.querySelector('.v7-panel-head h3')?.textContent)||'Tabela',data=tableData(panel);if(!data||!data.body.length)continue;if(y>175){doc.addPage();y=40;if($('#v742Legend')?.checked)y=drawLegend(doc,y)}y=titleBar(doc,title,y);const tableWidth=doc.internal.pageSize.getWidth()-CFG.marginX*2;const otherCount=Math.max(1,data.heads.length-1),dayWidth=Math.max(8,(tableWidth-CFG.nameWidth)/otherCount);const colStyles={0:{cellWidth:CFG.nameWidth,halign:'left',fontStyle:'bold'}};for(let i=1;i<data.heads.length;i++)colStyles[i]={cellWidth:dayWidth};doc.autoTable({startY:y,head:[data.heads],body:data.body,theme:'grid',margin:{left:CFG.marginX,right:CFG.marginX,top:40,bottom:13},styles:{font:'helvetica',fontSize:CFG.tableFont,cellPadding:1.2,minCellHeight:CFG.rowHeight,halign:'center',valign:'middle',lineWidth:.18,lineColor:CFG.colors.grid,textColor:CFG.colors.text,fillColor:[255,255,255],overflow:'linebreak'},headStyles:{fillColor:CFG.colors.dark,textColor:[255,255,255],fontStyle:'bold',lineColor:[255,255,255],lineWidth:.12},columnStyles:colStyles,showHead:'everyPage',horizontalPageBreak:true,horizontalPageBreakRepeat:0,didParseCell:d=>{if(d.column.index===0&&d.section==='body'){d.cell.styles.halign='left';d.cell.styles.fontStyle='bold'}if(data.weekendCols.has(d.column.index)){d.cell.styles.fillColor=d.section==='head'?CFG.colors.red:CFG.colors.weekend;d.cell.styles.textColor=d.section==='head'?[255,255,255]:CFG.colors.text}if(d.section==='body'){const k=cellKind(d.cell.raw);if(k==='service')d.cell.styles.fillColor=CFG.colors.service;else if(k==='pred')d.cell.styles.fillColor=CFG.colors.pred;else if(k==='vac')d.cell.styles.fillColor=CFG.colors.vac;else if(k==='adp')d.cell.styles.fillColor=CFG.colors.adp}},didDrawPage:()=>drawHeader(doc,img,doc.internal.getCurrentPageInfo().pageNumber)});y=(doc.lastAutoTable?.finalY||y)+5}
 const total=doc.getNumberOfPages();for(let p=1;p<=total;p++){doc.setPage(p);drawHeader(doc,img,p);drawFooter(doc,p,total)}const suffix=periodText().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/gi,'_').replace(/^_|_$/g,'').toLowerCase();doc.save(`${svc?'escala_servico':'escala_missao'}_${suffix||'periodo'}_v7.4.2.pdf`);modal(false)}catch(e){console.error(e);alert('Erro ao gerar PDF V7.4.2: '+(e.message||e))}finally{if(btn){btn.disabled=false;btn.textContent='Gerar PDF'}}}
function init(){ensureModal();const a=$('.v7-head .v7-actions');if(!a||$('#v742PdfBtn'))return;const b=document.createElement('button');b.id='v742PdfBtn';b.className='v7-btn';b.textContent='Gerar tabela PDF';b.onclick=()=>modal(true);a.appendChild(b)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
