(function(){
'use strict';
if((location.pathname.split('/').pop()||'').toLowerCase()!=='about.html')return;
const VERSION='7.6.4';
const releases=[
 {v:'7.6.4',title:'Lavagem com escolha ODT ou PDF',current:true,items:['Ao gerar a folha Forro de Cama para Lavar, o sistema agora abre uma escolha entre ODT e PDF.','O ODT continua editável e o PDF é gerado diretamente no navegador, pronto para visualizar, compartilhar ou imprimir.','A escolha funciona tanto no site quanto no aplicativo Android.','Mantida a correção 7.6.3 que impede serviço no fim de semana protegido pelas férias até a ADP.']},
 {v:'7.6.3',title:'Férias protegem também o fim de semana antes da ADP',current:false,items:['Corrigida a Escala Vermelha quando as férias terminam antes do fim de semana: sábado e domingo permanecem bloqueados até a ADP do próximo dia útil.','O militar não perde a vez no rodízio quando seu serviço cair nesse período protegido; ele permanece na fila e é colocado no próximo fim de semana elegível.','O Supabase agora impede confirmar ou transferir serviço para qualquer data entre o início das férias e a ADP, inclusive o fim de semana intermediário.','Mantida a correção 7.6.2 que gera o ODT Forro de Cama para Lavar no site e no aplicativo.']},
 {v:'7.6.2',title:'Arquivo ODT da Lavagem de Forro de Cama',current:false,items:['Corrigida a geração da folha Forro de Cama para Lavar no site: o botão passa a criar um arquivo ODT real em vez de depender de janela de impressão.','O documento reproduz a tabela Material/Quantidade e as linhas Quem mandou lavar e Quem recebeu.','A Lavagem de Forro de Cama foi incorporada à Base Web 7.6.2 com o mesmo fluxo já usado no aplicativo.','O download funciona mesmo com bloqueio de pop-up, pois a geração é feita diretamente no navegador.']},
 {v:'7.6.1',title:'Rolagem dos Jogos e retorno de férias',current:false,items:['Corrigida a rolagem vertical da página Jogos no site, inclusive quando o gesto começa sobre a pista do Dinossauro ou Voo Infinito.','No site, Cobrinha e 2048 passam a priorizar os botões de direção para não prender o scroll da página.','A ADP após férias nunca mais cai em sábado ou domingo: o retorno é deslocado para o próximo dia útil.','Exemplo: férias terminando na sexta-feira geram ADP na segunda-feira e o primeiro serviço permitido passa a ser terça-feira.','A regra também foi aplicada às validações do Supabase, escala de serviço, férias e aditamento.']},
 {v:'7.6.0',title:'Jogos, ranking público e acabamento visual',current:false,items:['Adicionada a nova área Jogos com nove desafios: Dinossauro, Cobrinha, Memória, 2048, Campo Minado, Precisão, Reflexo, Voo Infinito e Subida Infinita.','Cada jogo possui recorde pessoal e placar público compartilhado entre os usuários do TAREFAS.','Adicionadas trilhas procedurais próprias e diferentes para cada jogo, com botão para ativar ou silenciar a música.','Corrigido o enquadramento dos jogos no celular, inclusive tabuleiros de Memória, 2048 e Campo Minado.','Controles de toque passam a bloquear seleção de texto e menu de contexto; segurar Acelerar na Subida Infinita funciona como controle contínuo.','Gráficos dos jogos foram redesenhados com identidade visual inspirada no 26º Pel PE Mec, incluindo viatura de patrulha, sinalização e cenários próprios.']},
 {v:'7.5.11',title:'Histórico das versões 7.5.9 e 7.5.10 corrigido',items:['Adicionados ao About os registros completos das versões 7.5.9 e 7.5.10.','A versão atual do site passa a ser exibida como 7.5.11.','Atualizado o carregamento do histórico para evitar que o navegador mantenha a lista antiga em cache.']},
 {v:'7.5.10',title:'Folgas e previsões restauradas',items:['As folgas voltam a ser calculadas somente desde o último serviço confirmado de cada escala.','Próximo serviço confirmado e próxima previsão automática passam a ser mostrados separadamente.','As previsões das escalas Preta e Vermelha continuam independentes e não são tratadas como serviço confirmado.','Corrigida a projeção quando já existe serviço futuro confirmado, mantendo a próxima previsão visível.','O resumo de folgas volta a usar a distância até a próxima previsão automática.']},
 {v:'7.5.9',title:'Intervalo mínimo e operação do próprio serviço',items:['Previsões automáticas deixam de ser tratadas como serviços confirmados.','O sistema bloqueia serviços da mesma pessoa com intervalo inferior a três dias corridos.','O militar ativo na escala pode confirmar, trocar ou retirar o próprio serviço.','A administração de integrantes e feriados continua restrita aos perfis autorizados.','O rodízio evita prever o mesmo militar em datas separadas por apenas 24 horas.']},
 {v:'7.5.8',title:'Alteração de tarefas e bloqueio de mensagens',items:['Adicionado o botão Alterar tarefa em Minhas Tarefas para editar título, descrição, prioridade e prazo.','Usuários passam a poder bloquear e desbloquear mensagens diretamente na conversa.','O sistema avisa quando o outro usuário bloqueou suas mensagens e desativa o envio.','O bloqueio é validado no Supabase para impedir envio mesmo fora da interface.','O login do site passa a emitir a sessão protegida usada pelas funções de mensagens.']},
 {v:'7.5.7',title:'Escala de missão importada e contraste dos temas',items:['Importada para a Escala de missão a composição e a ordem dos militares da planilha fornecida.','Preparada a base para incorporar o histórico das missões após conferência dos aditamentos com horário, local e apresentação.','Corrigida a leitura dos nomes nas Escalas de serviço e missão no tema claro.','Cores das tabelas, cabeçalhos, dias úteis, finais de semana, serviço, missão, férias e ADP passam a manter contraste adequado em todos os temas.']},
 {v:'7.5.6',title:'Correções de serviços e Orçamentários',items:['Serviços confirmados voltam a aparecer no Calendário.','O Dashboard volta a exibir o Próximo serviço previsto ou confirmado.','Corrigida a aprovação pelo perfil Auxiliar da Fiscalização.','Adicionadas notificações para as novas áreas do Orçamentários.']},
 {v:'7.5.5',title:'Navegação das escalas restaurada',items:['Restaurada a navegação de Dia, Semana e Mês na Escala de serviço.','As setas passam a atualizar o período salvo e recarregar diretamente o intervalo correto.','A Escala de missão deixa de receber o seletor de período incompatível e volta a usar sua navegação mensal própria.','A correção impede a regressão causada pelo carregador da V7.5.4.']},
 {v:'7.5.4',title:'Ajustes mobile, TS e preferências de atualização',items:['Corrigido o recorte horizontal das telas de Escala de serviço e Escala de missão no mobile.','A identificação TSV passa a ser exibida como TS para serviço assumido por substituição.','O modal Criar Nova Tarefa passa a abrir acima da interface mobile.','Detalhes e mensagens de Usuários passam a abrir logo abaixo do usuário selecionado no celular.','Configurações ganham opção para ocultar no site os avisos de atualização do aplicativo Android.']},
 {v:'7.5.3',title:'Navegação da escala e serviço no calendário',items:['Corrigidas as setas de navegação por período na Escala de serviço.','O avanço e retorno de Dia, Semana e Mês passam a atualizar corretamente o período exibido.','Serviços confirmados do militar passam a aparecer também no Calendário.','Ao tocar no serviço exibido no Calendário, o sistema abre a Escala de serviço.']},
 {v:'7.5.2',title:'TSV para substituto e SV para escalado original',items:['Militar que assume um serviço por substituição passa a aparecer como TSV.','Militar originalmente escalado permanece identificado como SV.','A mudança é visual e não altera a correção de rodízio/folgas da V7.5.1.','Ao abrir o SV original de uma substituição, o sistema direciona para o lançamento efetivamente executado pelo TSV.','Versão visual passa a ser unificada em 7.5.2.']},
 {v:'7.5.1',title:'Substituição preserva o rodízio e versão unificada',items:['Substituir militar altera somente quem executa o serviço confirmado.','O militar originalmente escalado continua sendo a referência normal do rodízio e das folgas.','O militar substituto não herda a posição nem as folgas do militar substituído.','A Escala Preta e a Escala Vermelha continuam independentes.']},
 {v:'7.5',title:'Edição e exclusão de serviços',items:['Serviços confirmados podem ser editados.','Novo comando Excluir serviço com auditoria e notificação de cancelamento.','Substituir militar fica separado da exclusão.']}
];
function apply(){const versions=window.versions;if(!Array.isArray(versions))return false;versions.forEach(x=>{if(x)x.current=false});for(const rel of [...releases].reverse()){const old=versions.find(x=>x.v===rel.v);if(old)Object.assign(old,rel);else versions.unshift({...rel})}const sel=document.getElementById('versionSelect');if(sel){sel.innerHTML=versions.map(x=>`<option value="${x.v}">${x.v} — ${x.title}</option>`).join('');sel.value=VERSION;sel.dispatchEvent(new Event('change'))}const meta=[...document.querySelectorAll('.meta div')].find(x=>x.querySelector('small')?.textContent.includes('Versão atual'));if(meta?.querySelector('b'))meta.querySelector('b').textContent=VERSION;return true}
let tries=0;(function retry(){tries++;if(!apply()&&tries<100)setTimeout(retry,100)})();
})();