(function(){
'use strict';
if(window.__TAREFAS_V756_PATCH__)return;
window.__TAREFAS_V756_PATCH__=true;
const VERSION='7.5.6';
const page=(location.pathname.split('/').pop()||'').toLowerCase();
const PERIOD_KEY='tarefas_v743_period';
const GROUPS={sargento:'Sargentos',motorista:'Motoristas',patrulheiro:'Patrulheiros',permanencia:'Permanência',canil:'Permanência/Canil'};
const LANES={preta:'Escala Preta',vermelha:'Escala Vermelha'};
function logged(){try{return JSON.parse(localStorage.getItem('usuarioLogado')||'null')}catch(_){return null}}
function client(){try{return typeof supabaseClient!=='undefined'?supabaseClient:null}catch(_){return null}}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#039;'}[c]))}
function pad(n){return String(n).padStart(2,'0')}
function iso(d){return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`}
function parseDate(s){const m=String(s||'').match(/^(\d{4})-(\d{2})-(\d{2})/);return m?new Date(+m[1],+m[2]-1,+m[3]):new Date()}
function addDays(s,n){const d=parseDate(s);d.setDate(d.getDate()+n);return iso(d)}
function todayIso(){const d=new Date();d.setHours(0,0,0,0);return iso(d)}
function br(s){return parseDate(s).toLocaleDateString('pt-BR')}
function dayLabel(s){return parseDate(s).toLocaleDateString('pt-BR',{weekday:'short',day:'2-digit',month:'2-digit'}).replace('.','').toUpperCase()}
async function q(table,select,build){const c=client();if(!c)return[];try{let req=c.from(table).select(select);if(build)req=build(req);const r=await req;return r.error?[]:(r.data||[])}catch(_){return[]}}
let calendarServices=[],calendarLoading=false,calendarRangeKey='',calendarDomKey='',calendarChannel=null;
function calendarRange(){const cells=[...document.querySelectorAll('#calendarGrid .day-cell[data-date]')];const dates=cells.map(x=>x.dataset.date).filter(x=>/^\d{4}-\d{2}-\d{2}$/.test(x)).sort();return dates.length?{ini:dates[0],fim:dates[dates.length-1]}:null}
function serviceLabel(s){return `${s.marcacao||'SV'} · ${GROUPS[s.grupo]||s.grupo||'Serviço'}`}
function ensureCalendarCss(){if(document.getElementById('v756CalendarCss'))return;const s=document.createElement('style');s.id='v756CalendarCss';s.textContent=`.day-service-v756{display:flex;gap:7px;align-items:flex-start;font-size:11px;line-height:1.25;margin:5px 0 2px;min-width:0;font-weight:800;color:var(--v4-text,#111827)}.day-service-v756 .v756-service-dot{width:8px;height:8px;border-radius:2px;flex:0 0 8px;margin-top:2px;background:var(--v4-accent,#eab308)}.v756-service-title{overflow:hidden;white-space:nowrap;text-overflow:ellipsis}.v756-service-card{border:1px solid var(--line,var(--v4-border));border-left:4px solid var(--v4-accent,#eab308);border-radius:9px;padding:14px;margin-bottom:12px;cursor:pointer;background:var(--v4-surface,#fff)}.v756-service-card b{display:block;font-size:14px;margin-bottom:5px}.v756-service-card small{display:block;color:var(--v4-muted,#6b7280);line-height:1.4}.v756-service-badge{display:inline-flex;margin-top:8px;border-radius:5px;padding:5px 9px;background:var(--v4-accent-soft,#fff4c9);font-size:10px;font-weight:900}`;document.head.appendChild(s)}
function ensureCalendarLegend(){const legend=document.querySelector('.legend');if(!legend||legend.querySelector('[data-v756-service-legend]'))return;const el=document.createElement('div');el.className='legend-item';el.dataset.v756ServiceLegend='1';el.innerHTML='<span style="width:12px;height:12px;border-radius:2px;background:var(--v4-accent,#eab308)"></span>Serviço';legend.insertBefore(el,legend.querySelector('.legend-spacer'))}
function applyCalendarServices(){if(page!=='calendario.html')return;ensureCalendarCss();ensureCalendarLegend();document.querySelectorAll('[data-v756-service-item],[data-v756-service-card]').forEach(x=>x.remove());for(const s of calendarServices){const date=String(s.data_servico||'').slice(0,10);const cell=document.querySelector(`#calendarGrid .day-cell[data-date="${date}"]`);if(!cell)continue;const item=document.createElement('div');item.className='day-service-v756';item.dataset.v756ServiceItem=String(s.id);item.title='Abrir Escala de serviço';item.innerHTML=`<span class="v756-service-dot"></span><span class="v756-service-title">${esc(serviceLabel(s))}</span>`;item.onclick=e=>{e.stopPropagation();try{localStorage.setItem(PERIOD_KEY,JSON.stringify({mode:'day',anchor:date}))}catch(_){}location.href='pessoal.html'};cell.appendChild(item)}const selected=document.querySelector('#calendarGrid .day-cell.selected[data-date]')?.dataset.date;const list=document.getElementById('dayTasksList');if(selected&&list){calendarServices.filter(x=>String(x.data_servico||'').slice(0,10)===selected).forEach(s=>{const card=document.createElement('div');card.className='v756-service-card';card.dataset.v756ServiceCard=String(s.id);card.innerHTML=`<b>🛡️ ${esc(GROUPS[s.grupo]||'Serviço')}</b><small>Serviço confirmado na escala.</small>${s.observacao?`<small>${esc(s.observacao)}</small>`:''}<span class="v756-service-badge">${esc(s.marcacao||'SV')}</span>`;card.onclick=()=>{try{localStorage.setItem(PERIOD_KEY,JSON.stringify({mode:'day',anchor:selected}))}catch(_){}location.href='pessoal.html'};list.appendChild(card)})}}
async function loadCalendarServices(force=false){if(page!=='calendario.html'||calendarLoading)return;const c=client(),u=logged(),rg=calendarRange();if(!c||!u?.id||!rg)return;const key=`${rg.ini}|${rg.fim}|${u.id}`;if(!force&&key===calendarRangeKey){applyCalendarServices();return}calendarLoading=true;try{const r=await c.from('escala_servicos').select('id,grupo,data_servico,usuario_id,marcacao,observacao').eq('usuario_id',Number(u.id)).gte('data_servico',rg.ini).lte('data_servico',rg.fim).order('data_servico').order('grupo').order('id');if(!r.error){calendarServices=r.data||[];calendarRangeKey=key}}catch(_){}finally{calendarLoading=false;applyCalendarServices()}}
function calendarSignature(){const rg=calendarRange();if(!rg)return'';return `${rg.ini}|${rg.fim}|${document.querySelector('#calendarGrid .day-cell.selected[data-date]')?.dataset.date||''}`}
function startCalendar(){if(page!=='calendario.html')return;loadCalendarServices(true);setInterval(()=>{const sig=calendarSignature();if(!sig||sig===calendarDomKey)return;calendarDomKey=sig;loadCalendarServices()},700);try{const c=client();if(c)calendarChannel=c.channel('v756-calendario-servicos').on('postgres_changes',{event:'*',schema:'public',table:'escala_servicos'},()=>loadCalendarServices(true)).subscribe()}catch(_){}window.addEventListener('focus',()=>loadCalendarServices(true))}
const NEXT_CARD_ID='kNextServiceCard';let dashboardLoading=false;
function personKey(x){if(x?.usuario_id)return `u:${x.usuario_id}`;if(x?.pessoa_externa_id)return `e:${x.pessoa_externa_id}`;return''}
function rotationKey(s){if(s?.rodizio_usuario_id)return `u:${s.rodizio_usuario_id}`;if(s?.rodizio_pessoa_externa_id)return `e:${s.rodizio_pessoa_externa_id}`;return personKey(s)}
function moveToBack(queue,key){const i=queue.indexOf(key);if(i>=0){queue.splice(i,1);queue.push(key)}}
function inheritedAnchor(row,lane){return(lane==='vermelha'?row?.heranca_vermelha_data:row?.heranca_preta_data)||null}
function vacationFor(vacations,row,date){return vacations.find(v=>((row.usuario_id&&String(v.usuario_id)===String(row.usuario_id))||(row.pessoa_externa_id&&String(v.pessoa_externa_id)===String(row.pessoa_externa_id)))&&v.data_inicio<=date&&v.data_fim>=date)}
function adaptationFor(vacations,row,date){return vacations.find(v=>((row.usuario_id&&String(v.usuario_id)===String(row.usuario_id))||(row.pessoa_externa_id&&String(v.pessoa_externa_id)===String(row.pessoa_externa_id)))&&addDays(v.data_fim,1)===date)}
function eligible(vacations,row,date){return!vacationFor(vacations,row,date)&&!adaptationFor(vacations,row,date)}
function laneFor(date,holidays){const d=parseDate(date);return d.getDay()===0||d.getDay()===6||holidays.has(date)?'vermelha':'preta'}
function ensureNextCard(){let card=document.getElementById(NEXT_CARD_ID);if(card)return card;const grid=document.querySelector('.v6-kpis');if(!grid)return null;card=document.createElement('article');card.id=NEXT_CARD_ID;card.className='v6-kpi v756-next-service';card.tabIndex=0;card.setAttribute('role','button');card.innerHTML='<div class="v6-kpi-icon" data-v756-next-icon>★</div><div><small>Próximo serviço</small><strong id="kNextService">...</strong><span id="kNextServiceSub">Calculando previsão...</span></div>';grid.appendChild(card);if(!document.getElementById('v756NextServiceCss')){const s=document.createElement('style');s.id='v756NextServiceCss';s.textContent='.v756-next-service{cursor:pointer}.v756-next-service strong{font-size:clamp(22px,3vw,31px)}.v756-next-service span{line-height:1.35}';document.head.appendChild(s)}return card}
function setNextCard(state){const card=ensureNextCard();if(!card)return;const main=card.querySelector('#kNextService'),sub=card.querySelector('#kNextServiceSub'),icon=card.querySelector('[data-v756-next-icon]');if(!state){main.textContent='—';sub.textContent='Sem previsão disponível na escala';icon.textContent='•';card.onclick=null;return}const tag=state.kind==='confirmed'?(state.mark||'SV'):'PREV.';main.textContent=dayLabel(state.date);sub.textContent=`${tag} · ${GROUPS[state.group]||state.group} · ${LANES[state.lane]||state.lane}`;icon.textContent=state.kind==='confirmed'?'✓':'→';const open=()=>{try{localStorage.setItem(PERIOD_KEY,JSON.stringify({mode:'day',anchor:state.date}))}catch(_){}location.href='pessoal.html'};card.onclick=open;card.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open()}};card.title=`${state.kind==='confirmed'?'Serviço confirmado':'Próximo serviço previsto'} em ${br(state.date)}`}
function predictedForGroup({group,members,services,vacations,holidaySet,userId,start,end}){const rows=members.filter(x=>x.grupo===group).sort((a,b)=>(a.ordem||100)-(b.ordem||100)||Number(a.id)-Number(b.id));if(!rows.length)return[];const rowMap=new Map(rows.map(r=>[personKey(r),r])),keys=[...rowMap.keys()],userKey=`u:${userId}`;if(!keys.includes(userKey))return[];const out=[];for(const lane of['preta','vermelha']){const queue=[...keys];let confirmed=services.filter(s=>s.grupo===group&&keys.includes(rotationKey(s))&&laneFor(String(s.data_servico).slice(0,10),holidaySet)===lane).slice();for(const row of rows){const anchor=inheritedAnchor(row,lane),key=personKey(row);if(anchor&&!confirmed.some(s=>rotationKey(s)===key&&String(s.data_servico).slice(0,10)>=anchor))confirmed.push({id:-Number(row.id||0),grupo:group,data_servico:anchor,_rotation_key:key,_inherited:true})}confirmed.sort((a,b)=>String(a.data_servico).localeCompare(String(b.data_servico))||Number(a.id||0)-Number(b.id||0));if(!confirmed.length)continue;const anchorDate=String(confirmed[0].data_servico).slice(0,10);confirmed.filter(s=>String(s.data_servico).slice(0,10)===anchorDate).forEach(s=>moveToBack(queue,s._rotation_key||rotationKey(s)));let date=addDays(anchorDate,1);while(date<=end){if(laneFor(date,holidaySet)!==lane){date=addDays(date,1);continue}const actuals=confirmed.filter(s=>String(s.data_servico).slice(0,10)===date);if(actuals.length){actuals.forEach(s=>moveToBack(queue,s._rotation_key||rotationKey(s)))}else{let idx=-1;for(let i=0;i<queue.length;i++){const row=rowMap.get(queue[i]);if(row&&eligible(vacations,row,date)){idx=i;break}}if(idx>=0){const key=queue[idx];if(key===userKey&&date>=start)out.push({date,group,lane,kind:'predicted',mark:'PREV.'});queue.splice(idx,1);queue.push(key)}}date=addDays(date,1)}}return out}
async function loadDashboardService(){if(page!=='dashboard.html'||dashboardLoading)return;dashboardLoading=true;ensureNextCard();try{const user=logged(),c=client();if(!user?.id||!c){setNextCard(null);return}const today=todayIso(),from=addDays(today,-365),to=addDays(today,365),uid=Number(user.id);const[members,services,holidays,vacations]=await Promise.all([q('escala_integrantes','id,grupo,usuario_id,pessoa_externa_id,ordem,ativo,heranca_preta_data,heranca_vermelha_data',x=>x.eq('ativo',true).order('grupo').order('ordem').order('id')),q('escala_servicos','id,grupo,usuario_id,pessoa_externa_id,rodizio_usuario_id,rodizio_pessoa_externa_id,data_servico,marcacao,observacao',x=>x.gte('data_servico',from).lte('data_servico',to).order('data_servico').order('grupo').order('id')),q('escala_feriados','data',x=>x.gte('data',from).lte('data',to).order('data')),q('pessoal_ferias','usuario_id,pessoa_externa_id,data_inicio,data_fim',x=>x.lte('data_inicio',to).gte('data_fim',from).order('data_inicio'))]);const holidaySet=new Set(holidays.map(h=>String(h.data).slice(0,10))),groups=[...new Set(members.filter(m=>String(m.usuario_id)===String(uid)).map(m=>m.grupo))],candidates=[];for(const s of services.filter(s=>String(s.usuario_id)===String(uid)&&String(s.data_servico).slice(0,10)>=today)){const date=String(s.data_servico).slice(0,10),substituted=!!(s.rodizio_usuario_id||s.rodizio_pessoa_externa_id);candidates.push({date,group:s.grupo,lane:laneFor(date,holidaySet),kind:'confirmed',mark:substituted?'TS':(s.marcacao||'SV')})}for(const group of groups)candidates.push(...predictedForGroup({group,members,services,vacations,holidaySet,userId:uid,start:today,end:to}));candidates.sort((a,b)=>a.date.localeCompare(b.date)||(a.kind==='confirmed'?-1:1));const next=candidates.find((x,i,arr)=>x.kind==='confirmed'||!arr.some(y=>y.kind==='confirmed'&&y.date===x.date&&y.group===x.group))||null;setNextCard(next)}finally{dashboardLoading=false}}
function startDashboard(){if(page!=='dashboard.html')return;ensureNextCard();loadDashboardService().catch(()=>setNextCard(null));setTimeout(()=>loadDashboardService().catch(()=>{}),2500);window.addEventListener('focus',()=>loadDashboardService().catch(()=>{}))}
function init(){document.documentElement.dataset.tarefasVersion=VERSION;startCalendar();startDashboard()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();