(function(){
'use strict';
if(window.__TAREFAS_V756_PATCH__)return;
window.__TAREFAS_V756_PATCH__=true;
const VERSION='7.5.6';
const page=(location.pathname.split('/').pop()||'').toLowerCase();
const PERIOD_KEY='tarefas_v743_period';
const GROUPS={sargento:'Sargentos',motorista:'Motoristas',patrulheiro:'Patrulheiros',permanencia:'Permanência',canil:'Permanência/Canil'};
const LANES={preta:'Escala Preta',vermelha:'Escala Vermelha'};
function logged(){try{return JSON.parse(localStorage.getItem('usuarioLogado')||'null')}catch(_){return null}}
function client(){try{return typeof supabaseClient!=='undefined'?supabaseClient:null}catch(_){return null}}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#039;'}[c]))}
function pad(n){return String(n).padStart(2,'0')}
function iso(d){return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`}
function parseDate(s){const m=String(s||'').match(/^(\d{4})-(\d{2})-(\d{2})/);return m?new Date(+m[1],+m[2]-1,+m[3]):new Date()}
function addDays(s,n){const d=parseDate(s);d.setDate(d.getDate()+n);return iso(d)}
function todayIso(){const d=new Date();d.setHours(0,0,0,0);return iso(d)}
function br(s){return parseDate(s).toLocaleDateString('pt-BR')}
function dayLabel(s){return parseDate(s).toLocaleDateString('pt-BR',{weekday:'short',day:'2-digit',month:'2-digit'}).replace('.','').toUpperCase()}
async function q(table,select,build){const c=client();if(!c)return[];try{let req=c.from(table).select(select);if(build)req=build(req);const r=await req;return r.error?[]:(r.data||[])}catch(_){return[]}}
let calendarServices=[],calendarLoading=false,calendarRangeKey='',calendarDomKey='',calendarChannel=null;
function calendarRange(){const cells=[...document.querySelectorAll('#calendarGrid .day-cell[data-date]')];const dates=cells.map(x=>x.dataset.date).filter(x=>/^\d{4}-\d{2}-\d{2}$/.test(x)).sort();return dates.length?{ini:dates[0],fim:dates[dates.length-1]}:null}
function serviceLabel(s){return `${s.marcacao||'SV'} · ${GROUPS[s.grupo]||s.grupo||'Serviço'}`}
function ensureCalendarCss(){if(document.getElementById('v756CalendarCss'))return;const s=document.createElement('style');s.id='v756CalendarCss';s.textContent=`.day-service-v756{display:flex;gap:7px;align-items:flex-start;font-size:11px;line-height:1.25;margin:5px 0 2px;min-width:0;font-weight:800;color:var(--v4-text,#111827)}.day-service-v756 .v756-service-dot{width:8px;height:8px;border-radius:2px;flex:0 0 8px;margin-top:2px;background:var(--v4-accent,#eab308)}.v756-service-title{overflow:hidden;white-space:nowrap;text-overflow:ellipsis}.v756-service-card{border:1px solid var(--line,var(--v4-border));border-left:4px solid var(--v4-accent,#eab308);border-radius:9px;padding:14px;margin-bottom:12px;cursor:pointer;background:var(--v4-surface,#fff)}.v756-service-card b{display:block;font-size:14px;margin-bottom:5px}.v756-service-card small{display:block;color:var(--v4-muted,#6b7280);line-height:1.4}.v756-service-badge{display:inline-flex;margin-top:8px;border-radius:5px;padding:5px 9px;background:var(--v4-accent-soft,#fff4c9);font-size:10px;font-weight:900}`;document.head.appendChild(s)}
function ensureCalendarLegend(){const legend=document.querySelector('.legend');if(!legend||legend.querySelector('[data-v756-service-legend]'))return;const el=document.createElement('div');el.className='legend-item';el.dataset.v756ServiceLegend='1';el.innerHTML='<span style="width:12px;height:12px;border-radius:2px;background:var(--v4-accent,#eab308)"></span>Serviço';legend.insertBefore(el,legend.querySelector('.legend-spacer'))}
function applyCalendarServices(){if(page!=='calendario.html')return;ensureCalendarCss();ensureCalendarLegend();document.querySelectorAll('[data-v756-service-item],[data-v756-service-card]').forEach(x=>x.remove());for(const s of calendarServices){const date=String(s.data_servico||'').slice(0,10);const cell=document.querySelector(`#calendarGrid .day-cell[data-date="${date}"]`);if(!cell)continue;const item=document.createElement('div');item.className='day-service-v756';item.dataset.v756ServiceItem=String(s.id);item.title='Abrir Escala de serviço';item.innerHTML=`<span class="v756-service-dot"></span><span class="v756-service-title">${esc(serviceLabel(s))}</span>`;item.onclick=e=>{e.stopPropagation();try{localStorage.setItem(PERIOD_KEY,JSON.stringify({mode:'day',anchor:date}))}catch(_){}location.href='pessoal.html'};cell.appendChild(item)}const selected=document.querySelector('#calendarGrid .day-cell.selected[data-date]')?.dataset.date;const list=document.getElementById('dayTasksList');if(selected&&list){calendarServices.filter(x=>String(x.data_servico||'').slice(0,10)===selected).forEach(s=>{const card=document.createElement('div');card.className='v756-service-card';card.dataset.v756ServiceCard=String(s.id);card.innerHTML=`<b>🛡️ ${esc(GROUPS[s.grupo]||'Serviço')}</b><small>Serviço confirmado na escala.</small>${s.observacao?`<small>${esc(s.observacao)}</small>`:''}<span class="v756-service-badge">${esc(s.marcacao||'SV')}</span>`;card.onclick=()=>{try{localStorage.setItem(PERIOD_KEY,JSON.stringify({mode:'day',anchor:selected}))}catch(_){}location.href='pessoal.html'};list.appendChild(card)})}}
async function loadCalendarServices(force=false){if(page!=='calendario.html'||calendarLoading)return;const c=client(),u=logged(),rg=calendarRange();if(!c||!u?.id||!rg)return;const key=`${rg.ini}|${rg.fim}|${u.id}`;if(!force&&key===calendarRangeKey){applyCalendarServices();return}calendarLoading=true;try{const r=await c.from('escala_servicos').select('id,grupo,data_servico,usuario_id,marcacao,observacao').eq('usuario_id',Number(u.id)).gte('data_servico',rg.ini).lte('data_servico',rg.fim).order('data_servico').order('grupo').order('id');if(!r.error){calendarServices=r.data||[];calendarRangeKey=key}}catch(_){}finally{calendarLoading=false;applyCalendarServices()}}
function calendarSignature(){const rg=calendarRange();if(!rg)return'';return `${rg.ini}|${rg.fim}|${document.querySelector('#calendarGrid .day-cell.selected[data-date]')?.dataset.date||''}`}
function startCalendar(){if(page!=='calendario.html')return;loadCalendarServices(true);setInterval(()=>{const sig=calendarSignature();if(!sig||sig===calendarDomKey)return;calendarDomKey=sig;loadCalendarServices()},700);try{const c=client();if(c)calendarChannel=c.channel('v756-calendario-servicos').on('postgres_changes',{event:'*',schema:'public',table:'escala_servicos'},()=>loadCalendarServices(true)).subscribe()}catch(_){}window.addEventListener('focus',()=>loadCalendarServices(true))}
function init(){document.documentElement.dataset.tarefasVersion=VERSION;startCalendar();startDashboard()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();