(function(){
'use strict';
if(window.__TAREFAS_V772_SCALE_EXPORT__)return;
window.__TAREFAS_V772_SCALE_EXPORT__=true;
const VER='7.7.2',ODT='application/vnd.oasis.opendocument.text';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const page=(location.pathname.split('/').pop()||'').toLowerCase();
const service=page==='pessoal.html',mission=page==='missao.html';
if(!service&&!mission)return;
const root=service?'#scaleBoard':'#missionScaleBoard';
const groups=service?['Sargentos','Motoristas','Patrulheiros','Permanência','Permanência/Canil']:['Sargentos','Cabos','Soldados'];
const clean=v=>String(v??'').replace(/\s+/g,' ').trim();
const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&apos;');
function period(){return clean($('#monthLabel')?.textContent)||new Date().toLocaleDateString('pt-BR',{month:'long',year:'numeric'});}
function visible(c){return c&&c.style.display!=='none'&&getComputedStyle(c).display!=='none';}
function nameText(c){const n=c.cloneNode(true);n.querySelectorAll('button,.v7-online,.v721-person-meta,.v74-member-meta,.v72-external-tag,.v741-order-tools,.v742-order-tools,.v75-order-tools,.v7-order-tools').forEach(x=>x.remove());return clean(n.textContent);}
function readTable(panel){const t=panel.querySelector('.v7-table');const hr=t?.tHead?.rows?.[0];if(!t||!hr)return null;const all=[...hr.cells],idx=all.map((c,i)=>visible(c)?i:-1).filter(i=>i>=0),weekend=new Set();idx.forEach((orig,n)=>{if(all[orig].classList.contains('weekend'))weekend.add(n)});const heads=idx.map(i=>clean(all[i].innerText));const body=[...t.tBodies].flatMap(tb=>[...tb.rows]).map(r=>idx.map((orig,n)=>n===0?nameText(r.cells[orig]):clean(r.cells[orig]?.innerText)));return{heads,body,weekend};}
function selected(){const wanted=new Set($$('[data-v772-group]:checked').map(x=>x.dataset.v772Group));return $$(root+' .v7-panel').map(p=>({title:clean(p.querySelector('.v7-panel-head h3')?.textContent)||'Tabela',data:readTable(p)})).filter(x=>wanted.has(x.title)&&x.data?.heads?.length);}
function kind(v){const t=clean(v).toUpperCase();if(['SV','MS','MIS'].includes(t))return'sv';if(['PREV','PRV'].includes(t))return'prev';if(t.includes('FÉRIAS')||t.includes('FERIAS'))return'ferias';if(t==='ADP')return'adp';return'';}
function load(src,test){return new Promise((ok,no)=>{if(test())return ok();const s=document.createElement('script');s.src=src;s.onload=()=>test()?ok():no(new Error('Biblioteca não disponível.'));s.onerror=()=>no(new Error('Falha ao carregar biblioteca.'));document.head.appendChild(s);});}
async function pdfLib(){await load('https://cdn.jsdelivr.net/npm/jspdf@2.5.2/dist/jspdf.umd.min.js',()=>!!window.jspdf?.jsPDF);await load('https://cdn.jsdelivr.net/npm/jspdf-autotable@3.8.4/dist/jspdf.plugin.autotable.min.js',()=>!!window.jspdf?.jsPDF?.API?.autoTable);}
async function pdfBlob(tables){await pdfLib();const {jsPDF}=window.jspdf,doc=new jsPDF({orientation:'landscape',unit:'mm',format:'a4'}),W=doc.internal.pageSize.getWidth();let y=16;const header=()=>{doc.setFont('helvetica','bold');doc.setFontSize(13);doc.text('26º PELOTÃO DE POLÍCIA DO EXÉRCITO MECANIZADO',W/2,10,{align:'center'});doc.setFontSize(10);doc.text(service?'ESCALA DE SERVIÇO':'ESCALA DE MISSÃO',W/2,15,{align:'center'});doc.setFont('helvetica','normal');doc.setFontSize(7.5);doc.text('Período: '+period(),W/2,19,{align:'center'});};header();y=25;for(const item of tables){if(y>175){doc.addPage();header();y=25;}doc.setFillColor(31,36,41);doc.rect(8,y,W-16,6,'F');doc.setTextColor(255);doc.setFont('helvetica','bold');doc.setFontSize(9);doc.text(item.title.toUpperCase(),W/2,y+4,{align:'center'});doc.setTextColor(20);y+=6;const widths={0:{cellWidth:43,halign:'left',fontStyle:'bold'}};for(let i=1;i<item.data.heads.length;i++)widths[i]={cellWidth:Math.max(8,(W-59)/Math.max(1,item.data.heads.length-1))};doc.autoTable({startY:y,head:[item.data.heads],body:item.data.body,theme:'grid',margin:{left:8,right:8,bottom:10},styles:{fontSize:7,cellPadding:1.1,halign:'center',valign:'middle',lineWidth:.15,lineColor:[75,82,88]},headStyles:{fillColor:[31,36,41],textColor:[255,255,255],fontStyle:'bold'},columnStyles:widths,didParseCell:d=>{if(item.data.weekend.has(d.column.index)){d.cell.styles.fillColor=d.section==='head'?[185,35,35]:[255,243,243];if(d.section==='head')d.cell.styles.textColor=[255,255,255];}if(d.section==='body'){const k=kind(d.cell.raw);if(k==='sv')d.cell.styles.fillColor=[236,253,245];if(k==='prev')d.cell.styles.fillColor=[255,251,220];if(k==='ferias')d.cell.styles.fillColor=[239,246,255];if(k==='adp')d.cell.styles.fillColor=[244,244,245];}},didDrawPage:header});y=(doc.lastAutoTable?.finalY||y)+5;}return doc.output('blob');}
const CRC=(()=>{const a=new Uint32Array(256);for(let n=0;n<256;n++){let c=n;for(let k=0;k<8;k++)c=(c&1)?0xedb88320^(c>>>1):c>>>1;a[n]=c>>>0;}return a;})();
const u16=n=>Uint8Array.of(n&255,n>>>8&255),u32=n=>Uint8Array.of(n&255,n>>>8&255,n>>>16&255,n>>>24&255);
function cat(parts){const z=new Uint8Array(parts.reduce((n,p)=>n+p.length,0));let o=0;parts.forEach(p=>{z.set(p,o);o+=p.length});return z;}
function crc32(b){let c=0xffffffff;for(const x of b)c=CRC[(c^x)&255]^(c>>>8);return(c^0xffffffff)>>>0;}
function zip(files){const te=new TextEncoder(),locals=[],centers=[];let off=0;for(const f of files){const name=te.encode(f.name),data=f.data instanceof Uint8Array?f.data:te.encode(String(f.data)),crc=crc32(data),local=cat([u32(0x04034b50),u16(20),u16(0x800),u16(0),u16(0),u16(0),u32(crc),u32(data.length),u32(data.length),u16(name.length),u16(0),name,data]);locals.push(local);centers.push(cat([u32(0x02014b50),u16(20),u16(20),u16(0x800),u16(0),u16(0),u16(0),u32(crc),u32(data.length),u32(data.length),u16(name.length),u16(0),u16(0),u16(0),u16(0),u32(0),u32(off),name]));off+=local.length;}const c=cat(centers),end=cat([u32(0x06054b50),u16(0),u16(0),u16(files.length),u16(files.length),u32(c.length),u32(off),u16(0)]);return cat([...locals,c,end]);}
function styles(){return `<?xml version="1.0" encoding="UTF-8"?><office:document-styles xmlns:office="urn:oasis:names:tc:opendocument:xmlns:office:1.0" xmlns:style="urn:oasis:names:tc:opendocument:xmlns:style:1.0" xmlns:text="urn:oasis:names:tc:opendocument:xmlns:text:1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" office:version="1.3"><office:styles><style:default-style style:family="paragraph"><style:text-properties fo:font-family="Arial" fo:font-size="8pt"/></style:default-style><style:style style:name="T" style:family="paragraph"><style:paragraph-properties fo:text-align="center"/><style:text-properties fo:font-size="13pt" fo:font-weight="bold"/></style:style><style:style style:name="S" style:family="paragraph"><style:paragraph-properties fo:text-align="center"/><style:text-properties fo:font-size="10pt" fo:font-weight="bold"/></style:style><style:style style:name="H" style:family="paragraph"><style:text-properties fo:font-weight="bold"/></style:style></office:styles><office:automatic-styles><style:page-layout style:name="pm"><style:page-layout-properties fo:page-width="29.7cm" fo:page-height="21cm" style:print-orientation="landscape" fo:margin="0.8cm"/></style:page-layout></office:automatic-styles><office:master-styles><style:master-page style:name="Standard" style:page-layout-name="pm"/></office:master-styles></office:document-styles>`;}
function cellStyle(i,data,v,h){if(h)return data.weekend.has(i)?'wh':'hd';if(i===0)return'nm';const k=kind(v);return k||(data.weekend.has(i)?'we':'bd');}
function content(tables){let auto='<office:automatic-styles><style:style style:name="tb" style:family="table"><style:table-properties table:align="margins" style:width="100%"/></style:style>';const cs=(n,bg,fg='#14181c',bold=false,align='center')=>`<style:style style:name="${n}" style:family="table-cell"><style:table-cell-properties fo:background-color="${bg}" fo:border="0.02cm solid #4b5258" fo:padding="0.04cm"/><style:paragraph-properties fo:text-align="${align}"/><style:text-properties fo:font-family="Arial" fo:font-size="7pt" fo:color="${fg}"${bold?' fo:font-weight="bold"':''}/></style:style>`;auto+=cs('hd','#1f2429','#ffffff',true)+cs('wh','#b92323','#ffffff',true)+cs('bd','#ffffff')+cs('we','#fff3f3')+cs('nm','#ffffff','#14181c',true,'start')+cs('sv','#ecfdf5')+cs('prev','#fffbdc')+cs('ferias','#eff6ff')+cs('adp','#f4f4f5');tables.forEach((x,ti)=>{auto+=`<style:style style:name="c${ti}_0" style:family="table-column"><style:table-column-properties style:column-width="4.2cm"/></style:style>`;for(let i=1;i<x.data.heads.length;i++)auto+=`<style:style style:name="c${ti}_${i}" style:family="table-column"><style:table-column-properties style:column-width="0.85cm"/></style:style>`});auto+='</office:automatic-styles>';const tbl=(x,ti)=>{const cols=x.data.heads.map((_,i)=>`<table:table-column table:style-name="c${ti}_${i}"/>`).join('');const row=(r,h=false)=>`<table:table-row>${r.map((v,i)=>`<table:table-cell table:style-name="${cellStyle(i,x.data,v,h)}" office:value-type="string"><text:p>${esc(v)}</text:p></table:table-cell>`).join('')}</table:table-row>`;return `<text:p text:style-name="H">${esc(x.title.toUpperCase())}</text:p><table:table table:name="${esc(x.title)}" table:style-name="tb">${cols}<table:table-header-rows>${row(x.data.heads,true)}</table:table-header-rows>${x.data.body.map(r=>row(r)).join('')}</table:table>`;};return `<?xml version="1.0" encoding="UTF-8"?><office:document-content xmlns:office="urn:oasis:names:tc:opendocument:xmlns:office:1.0" xmlns:style="urn:oasis:names:tc:opendocument:xmlns:style:1.0" xmlns:text="urn:oasis:names:tc:opendocument:xmlns:text:1.0" xmlns:table="urn:oasis:names:tc:opendocument:xmlns:table:1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" office:version="1.3">${auto}<office:body><office:text><text:p text:style-name="T">26º PELOTÃO DE POLÍCIA DO EXÉRCITO MECANIZADO</text:p><text:p text:style-name="S">${service?'ESCALA DE SERVIÇO':'ESCALA DE MISSÃO'}</text:p><text:p>Período: ${esc(period())} · Gerado em ${new Date().toLocaleDateString('pt-BR')}</text:p><text:p>Escala Preta = dias úteis · Escala Vermelha = sábados, domingos e feriados · SV/MS = confirmado · PREV = previsão · ADP = adaptação · FÉRIAS = afastado</text:p>${tables.map(tbl).join('')}</office:text></office:body></office:document-content>`;}
function odtBlob(t){const e=new TextEncoder(),manifest=`<?xml version="1.0" encoding="UTF-8"?><manifest:manifest xmlns:manifest="urn:oasis:names:tc:opendocument:xmlns:manifest:1.0" manifest:version="1.3"><manifest:file-entry manifest:full-path="/" manifest:version="1.3" manifest:media-type="${ODT}"/><manifest:file-entry manifest:full-path="content.xml" manifest:media-type="text/xml"/><manifest:file-entry manifest:full-path="styles.xml" manifest:media-type="text/xml"/><manifest:file-entry manifest:full-path="meta.xml" manifest:media-type="text/xml"/></manifest:manifest>`,meta=`<?xml version="1.0" encoding="UTF-8"?><office:document-meta xmlns:office="urn:oasis:names:tc:opendocument:xmlns:office:1.0" xmlns:meta="urn:oasis:names:tc:opendocument:xmlns:meta:1.0" office:version="1.3"><office:meta><meta:generator>TAREFAS ${VER}</meta:generator></office:meta></office:document-meta>`;return new Blob([zip([{name:'mimetype',data:e.encode(ODT)},{name:'content.xml',data:e.encode(content(t))},{name:'styles.xml',data:e.encode(styles())},{name:'meta.xml',data:e.encode(meta)},{name:'META-INF/manifest.xml',data:e.encode(manifest)}])],{type:ODT});}
async function save(blob,name){if(window.TarefasNative?.isNative&&window.TarefasNative?.files?.saveBlob){const r=await window.TarefasNative.files.saveBlob(blob,name);if(r?.saved)return r;}const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),30000);return{saved:true};}
function modal(open){$('#v772ScaleExport')?.classList.toggle('open',open);}
function ui(){if($('#v772ScaleExport'))return;const m=document.createElement('div');m.id='v772ScaleExport';m.className='v7-modal-bg';m.innerHTML=`<div class="v7-modal" style="width:min(620px,100%)"><div class="v7-modal-head"><h3>Gerar escala <small style="font-size:9px;color:var(--v4-muted)">V${VER}</small></h3><button class="v7-close" data-v772-close>×</button></div><div class="v7-note">Escolha o formato. O ODT é editável no LibreOffice e Microsoft Word.</div><div class="v7-form"><div class="v7-field full"><label>Formato</label><label><input type="radio" name="v772fmt" value="pdf" checked> PDF</label> &nbsp; <label><input type="radio" name="v772fmt" value="odt"> ODT editável</label></div><div class="v7-field full"><label>Tabelas</label><div style="display:grid;gap:6px">${groups.map(g=>`<label style="padding:7px;border:1px solid var(--v4-border);border-radius:7px"><input type="checkbox" data-v772-group="${g}" checked> ${g}</label>`).join('')}</div></div><div class="v7-field full"><div id="v772status" class="v72-last-change">Pronto para gerar.</div></div></div><div class="v7-modal-actions"><button class="v7-btn" data-v772-close>Cancelar</button><button class="v7-btn primary" id="v772go">Gerar arquivo</button></div></div>`;document.body.appendChild(m);m.onclick=e=>{if(e.target===m||e.target.closest('[data-v772-close]'))modal(false)};$('#v772go').onclick=generate;}
async function generate(){const t=selected();if(!t.length)return alert('Selecione pelo menos uma tabela.');const f=$('input[name="v772fmt"]:checked')?.value||'pdf',b=$('#v772go'),s=$('#v772status');try{b.disabled=true;b.textContent='Gerando...';s.textContent=f==='odt'?'Montando ODT editável...':'Montando PDF...';const blob=f==='odt'?odtBlob(t):await pdfBlob(t),name=`${service?'escala_servico':'escala_missao'}_${new Date().toISOString().slice(0,10)}_v${VER}.${f}`;const r=await save(blob,name);s.textContent=r?.path?'Salvo em '+r.path:'Arquivo gerado com sucesso.';setTimeout(()=>modal(false),500);}catch(e){console.error('[TAREFAS 7.7.2 ESCALA]',e);s.textContent='Erro: '+(e?.message||e);alert('Não foi possível gerar a escala.');}finally{b.disabled=false;b.textContent='Gerar arquivo';}}
window.TAREFAS_SCALE_EXPORT_V772={version:VER,odtBlob,readTable,selected};
function boot(){ui();const a=$('.v7-head .v7-actions');if(!a||$('#v772ScaleBtn'))return;const b=document.createElement('button');b.id='v772ScaleBtn';b.className='v7-btn';b.textContent='Gerar escala';b.onclick=()=>modal(true);a.appendChild(b);}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
