(()=>{
'use strict';
const MARK='__TAREFAS_CHAT_ATTACHMENTS_782__';if(window[MARK])return;window[MARK]=true;
if((location.pathname.split('/').pop()||'').toLowerCase()!=='usuarios.html')return;
const ENDPOINT='https://bpvijatnsluwsgnzklrd.supabase.co/functions/v1/tarefas-chat-files',SESSION_KEY='tarefasPushSession17',MAX_FILES=4,MAX_FILE=10*1024*1024,MAX_TOTAL=25*1024*1024;
let partnerId=0,selected=[],busy=false,objectUrls=[];
function me(){try{return JSON.parse(localStorage.getItem('usuarioLogado')||'null')}catch(_){return null}}
function session(){return String(localStorage.getItem(SESSION_KEY)||'').trim()}
function profile(){return Number(me()?.perfil_id||0)}
function headers(){return{'X-Tarefas-Session':session(),'X-Tarefas-Profile':String(profile())}}
function notify(text,error=false){let n=document.getElementById('chat782Toast');if(!n){n=document.createElement('div');n.id='chat782Toast';n.style.cssText='position:fixed;right:18px;bottom:18px;z-index:10090;padding:11px 14px;border-radius:10px;color:#fff;background:#111827;box-shadow:0 12px 30px rgba(0,0,0,.25);font:700 12px Arial;max-width:min(360px,calc(100vw - 36px));opacity:0;transition:.2s';document.body.appendChild(n)}n.textContent=text;n.style.background=error?'#991b1b':'#111827';n.style.opacity='1';clearTimeout(n._t);n._t=setTimeout(()=>n.style.opacity='0',3000)}
function css(){if(document.getElementById('chat782Style'))return;const s=document.createElement('style');s.id='chat782Style';s.textContent=`.chat782-tools{display:flex;align-items:center;gap:8px;margin-top:8px}.chat782-attach{border:1px solid var(--v4-border-strong,#cbd5e1);background:var(--v4-surface,#fff);color:var(--v4-text,#111827);border-radius:8px;padding:8px 11px;font-weight:800;cursor:pointer}.chat782-selected{display:flex;flex-wrap:wrap;gap:6px;flex:1}.chat782-chip{display:inline-flex;align-items:center;gap:5px;max-width:200px;border:1px solid var(--v4-border,#d7dce3);background:var(--v4-surface-2,#f6f7f9);border-radius:999px;padding:5px 8px;font-size:10px}.chat782-chip span{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.chat782-chip button{border:0;background:none;cursor:pointer;color:#b91c1c;font-weight:900}.chat782-files{display:grid;gap:6px;margin-top:7px}.chat782-file{display:flex;align-items:center;gap:8px;width:100%;border:1px solid rgba(0,0,0,.12);background:rgba(255,255,255,.72);border-radius:8px;padding:7px;text-align:left;color:inherit;cursor:pointer}.chat782-file img{width:52px;height:52px;border-radius:7px;object-fit:cover;background:#e5e7eb}.chat782-file-icon{font-size:21px;flex:0 0 28px;text-align:center}.chat782-file-meta{min-width:0}.chat782-file-name{font-size:11px;font-weight:800;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.chat782-file-size{font-size:9px;opacity:.65;margin-top:2px}.chat782-bubble-text:empty{display:none}`;document.head.appendChild(s)}
function sizeText(n){const x=Number(n)||0;return x<1024?`${x} B`:x<1048576?`${(x/1024).toFixed(1)} KB`:`${(x/1048576).toFixed(1)} MB`}
function currentPartner(){const selectedRow=document.querySelector('.user-row.selected .msg-btn');return Number(selectedRow?.getAttribute('data-id')||partnerId||0)}
function validate(files){if(files.length>MAX_FILES)return`Máximo de ${MAX_FILES} anexos por mensagem.`;let total=0;for(const f of files){if(f.size>MAX_FILE)return`${f.name}: máximo de 10 MB.`;total+=f.size}if(total>MAX_TOTAL)return'Os anexos juntos ultrapassam 25 MB.';return''}
function renderSelected(){const box=document.getElementById('chat782Selected');if(!box)return;box.textContent='';selected.forEach((f,i)=>{const c=document.createElement('span');c.className='chat782-chip';const t=document.createElement('span');t.textContent=`${f.name} · ${sizeText(f.size)}`;const x=document.createElement('button');x.type='button';x.textContent='×';x.onclick=()=>{selected.splice(i,1);renderSelected()};c.append(t,x);box.appendChild(c)})}
async function compressImage(file){if(!file.type.startsWith('image/')||file.size<2.5*1024*1024)return file;try{const bmp=await createImageBitmap(file),max=1920,scale=Math.min(1,max/Math.max(bmp.width,bmp.height));if(scale>=1)return file;const canvas=document.createElement('canvas');canvas.width=Math.round(bmp.width*scale);canvas.height=Math.round(bmp.height*scale);canvas.getContext('2d').drawImage(bmp,0,0,canvas.width,canvas.height);const blob=await new Promise(r=>canvas.toBlob(r,'image/jpeg',.84));bmp.close?.();if(!blob||blob.size>=file.size)return file;return new File([blob],file.name.replace(/\.[^.]+$/,'.jpg'),{type:'image/jpeg',lastModified:Date.now()})}catch{return file}}
async function pickFiles(input){let files=[...input.files||[]];files=await Promise.all(files.map(compressImage));const merged=[...selected,...files].slice(0,MAX_FILES);const err=validate(merged);if(err){notify(err,true);input.value='';return}selected=merged;input.value='';renderSelected()}
function ensureUi(){const panel=document.getElementById('messagePanel'),textarea=document.getElementById('messageText'),send=document.getElementById('sendMessage');if(!panel||!textarea||!send)return;if(document.getElementById('chat782Tools'))return;css();const tools=document.createElement('div');tools.id='chat782Tools';tools.className='chat782-tools';tools.innerHTML='<button type="button" class="chat782-attach" id="chat782Attach">📎 Anexar</button><div class="chat782-selected" id="chat782Selected"></div><input id="chat782Input" type="file" multiple hidden accept="image/*,application/pdf,text/plain,text/csv,application/json,application/rtf,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document,application/vnd.ms-excel,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/vnd.oasis.opendocument.text,application/vnd.oasis.opendocument.spreadsheet">';textarea.insertAdjacentElement('afterend',tools);const input=document.getElementById('chat782Input');document.getElementById('chat782Attach').onclick=()=>input.click();input.onchange=()=>pickFiles(input);renderSelected();setTimeout(()=>refresh(currentPartner()),120)}
async function fetchBlob(id){const r=await fetch(`${ENDPOINT}?id=${encodeURIComponent(id)}`,{headers:headers()});if(!r.ok)throw new Error('download');return r.blob()}
async function openAttachment(a){try{const blob=await fetchBlob(a.id),url=URL.createObjectURL(blob);objectUrls.push(url);if(String(a.arquivo_mime||'').startsWith('image/')||a.arquivo_mime==='application/pdf')window.open(url,'_blank');else{const x=document.createElement('a');x.href=url;x.download=a.arquivo_nome||'arquivo';document.body.appendChild(x);x.click();x.remove()}}catch{notify('Não foi possível abrir o anexo.',true)}}
function fileNode(a){const b=document.createElement('button');b.type='button';b.className='chat782-file';if(String(a.arquivo_mime||'').startsWith('image/')){const img=document.createElement('img');img.alt=a.arquivo_nome||'Foto';b.appendChild(img);fetchBlob(a.id).then(blob=>{const u=URL.createObjectURL(blob);objectUrls.push(u);img.src=u}).catch(()=>{})}else{const i=document.createElement('span');i.className='chat782-file-icon';i.textContent=a.arquivo_mime==='application/pdf'?'📄':'📎';b.appendChild(i)}const meta=document.createElement('span');meta.className='chat782-file-meta';const name=document.createElement('div');name.className='chat782-file-name';name.textContent=a.arquivo_nome||'Arquivo';const size=document.createElement('div');size.className='chat782-file-size';size.textContent=sizeText(a.arquivo_tamanho);meta.append(name,size);b.appendChild(meta);b.onclick=()=>openAttachment(a);return b}
async function refresh(partner){partner=Number(partner||0);if(!partner||!session()||!profile())return;partnerId=partner;try{const r=await fetch(`${ENDPOINT}?partner=${encodeURIComponent(partner)}`,{headers:headers()});const d=await r.json();if(!r.ok||!d?.ok)return;const box=document.getElementById('conversation');if(!box)return;objectUrls.forEach(URL.revokeObjectURL);objectUrls=[];const by=new Map;for(const a of d.attachments||[]){const k=String(a.mensagem_id);if(!by.has(k))by.set(k,[]);by.get(k).push(a)}box.textContent='';if(!(d.messages||[]).length){const e=document.createElement('div');e.className='empty';e.textContent='Nenhuma mensagem ainda.';box.appendChild(e);return}const uid=String(me()?.id||'');for(const m of d.messages){const bubble=document.createElement('div');bubble.className=`bubble ${String(m.remetente_id)===uid?'me':'other'}`;bubble.dataset.messageId=String(m.id);const text=document.createElement('div');text.className='chat782-bubble-text';text.textContent=m.conteudo||'';bubble.appendChild(text);const files=by.get(String(m.id))||[];if(files.length){const fb=document.createElement('div');fb.className='chat782-files';files.forEach(a=>fb.appendChild(fileNode(a)));bubble.appendChild(fb)}const time=document.createElement('div');time.className='bubble-time';time.textContent=new Date(m.criada_em).toLocaleString('pt-BR');bubble.appendChild(time);box.appendChild(bubble)}box.scrollTop=box.scrollHeight}catch{}}
async function send(){if(busy)return;const partner=currentPartner(),textarea=document.getElementById('messageText'),button=document.getElementById('sendMessage');const text=String(textarea?.value||'').trim();if(!partner)return notify('Selecione um usuário para conversar.',true);if(!text&&!selected.length)return notify('Digite uma mensagem ou anexe um arquivo.',true);const err=validate(selected);if(err)return notify(err,true);busy=true;if(button)button.disabled=true;try{const fd=new FormData();fd.set('partner_id',String(partner));fd.set('text',text);selected.forEach(f=>fd.append('files',f,f.name));const r=await fetch(ENDPOINT,{method:'POST',headers:headers(),body:fd});const d=await r.json().catch(()=>({}));if(!r.ok&&!d?.message)throw new Error(d?.error||'send');if(textarea)textarea.value='';selected=[];renderSelected();notify(d?.warning?'Mensagem enviada, mas um anexo falhou.':'Mensagem enviada.');await refresh(partner)}catch{notify('Não foi possível enviar a mensagem/anexo.',true)}finally{busy=false;if(button)button.disabled=false}}
document.addEventListener('click',e=>{const target=e.target instanceof Element?e.target:null;const mb=target?.closest('.msg-btn');if(mb){partnerId=Number(mb.getAttribute('data-id')||0);selected=[];setTimeout(ensureUi,0);setTimeout(()=>refresh(partnerId),180);return}const sb=target?.closest('#sendMessage');if(sb){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();send()}},true);
const obs=new MutationObserver(()=>ensureUi());obs.observe(document.body,{subtree:true,childList:true});
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',ensureUi,{once:true});else ensureUi();
})();
