(function(){
'use strict';
if(window.__TAREFAS_V783_MATERIAL_CARGA_SAFE__)return;
window.__TAREFAS_V783_MATERIAL_CARGA_SAFE__=true;
const DAY=86400000,$=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const dt=v=>v?new Date(v).toLocaleString('pt-BR'):'-';
let docs=[],pending=[],users=[],usersMap=new Map(),user=null,busy=false,bound=false;
function client(){try{return typeof supabaseClient!=='undefined'?supabaseClient:null}catch(_){return null}}
function timeout(p,ms){return Promise.race([Promise.resolve(p),new Promise((_,rej)=>setTimeout(()=>rej(new Error('timeout')),ms))])}
function tipo(){return document.querySelector('[data-carga-tipo].active')?.dataset.cargaTipo||'dependencia'}
function ref(){const t=$('cargaTitle')?.textContent?.trim();return t&&t!=='-'?t:null}
function latest(t,r){return docs.find(x=>x.tipo_referencia===t&&x.referencia===r)||null}
function pend(t,r){return pending.filter(x=>x.tipo_referencia===t&&x.referencia===r&&x.status==='pendente')}
function uname(id){const u=usersMap.get(String(id));return u?[u.patente,u.nome_guerra].filter(Boolean).join(' '):id?`Usuário ${id}`:'Não informado'}
function due(t,r){const d=latest(t,r),p=pend(t,r),days=t==='deposito'?30:90;if(!d)return{level:'critical',text:'Sem relação atualizada',d,p};const base=new Date(d.conferido_em||d.criado_em),left=Math.ceil(((base.getTime()+days*DAY)-Date.now())/DAY);if(p.length)return{level:'critical',text:'Atualização obrigatória após processo',d,p};if(left<0)return{level:'critical',text:`Vencido há ${Math.abs(left)} dia(s)`,d,p};if(left<=7)return{level:'warning',text:left===0?'Atualizar hoje':`Vence em ${left} dia(s)`,d,p};return{level:'ok',text:`Em dia · ${left} dia(s) restantes`,d,p}}
function css(){if($('v783CargaCss'))return;const s=document.createElement('style');s.id='v783CargaCss';s.textContent='.v770-carga-status{margin-top:7px;font-size:11px;font-weight:800}.v770-carga-status.ok{color:#16a34a}.v770-carga-status.warning{color:#d97706}.v770-carga-status.critical{color:#dc2626}.v770-carga-panel{margin:12px 0;padding:12px;border:1px solid var(--v4-border,#d1d5db);border-radius:10px;background:var(--v4-surface,#fff)}.v770-checker{display:grid;gap:5px;margin-bottom:8px}.v770-checker select{min-height:38px}';document.head.appendChild(s)}
async function load(){const c=client();if(!c||busy)return;busy=true;try{const [d,p,u]=await Promise.allSettled([timeout(c.from('orc_documentos_carga').select('*').order('tipo_referencia').order('referencia').order('versao',{ascending:false}),6000),timeout(c.from('orc_carga_pendencias').select('*').order('criada_em',{ascending:false}),6000),timeout(c.from('usuarios').select('id,patente,nome_guerra').order('nome_guerra'),6000)]);if(d.status==='fulfilled'&&!d.value.error)docs=d.value.data||[];if(p.status==='fulfilled'&&!p.value.error)pending=p.value.data||[];if(u.status==='fulfilled'&&!u.value.error){users=u.value.data||[];usersMap=new Map(users.map(x=>[String(x.id),x]))}render()}finally{busy=false}}
function checker(){const area=$('cargaFiscalUpdate');if(!area)return;let sel=$('cargaConferidoPor');if(!sel){const w=document.createElement('div');w.className='v770-checker';w.innerHTML='<label>Quem conferiu *</label><select id="cargaConferidoPor"><option value="">Selecione quem conferiu...</option></select>';area.prepend(w);sel=$('cargaConferidoPor')}const sig=users.map(x=>x.id).join(',');if(sel.dataset.sig!==sig){const cur=sel.value;sel.innerHTML='<option value="">Selecione quem conferiu...</option>'+users.map(u=>`<option value="${esc(u.id)}">${esc([u.patente,u.nome_guerra].filter(Boolean).join(' '))}</option>`).join('');sel.dataset.sig=sig;if(cur)sel.value=cur;else if(user?.id)sel.value=String(user.id)}}
function annotate(){const t=tipo();document.querySelectorAll('#cargaRefList [data-carga-ref]').forEach(card=>{const x=due(t,card.dataset.cargaRef);let el=card.querySelector('.v770-carga-status');if(!el){el=document.createElement('div');card.appendChild(el)}el.className=`v770-carga-status ${x.level}`;if(el.textContent!==x.text)el.textContent=x.text})}
function detail(){const r=ref();if(!r||!$('cargaDetail')||$('cargaDetail').hidden)return;const t=tipo(),x=due(t,r),d=x.d;let p=$('v770CargaPanel');if(!p){p=document.createElement('div');p.id='v770CargaPanel';p.className='v770-carga-panel';const target=$('cargaFiscalUpdate')||$('cargaDetentorPanel')||$('cargaDetail');target.parentNode.insertBefore(p,target)}const key=`${t}|${r}|${d?.id||0}|${x.p.map(v=>v.id).join(',')}`;if(p.dataset.key===key)return;p.dataset.key=key;p.innerHTML=`<h4>Conferência e validade</h4><div><small>Quem conferiu</small><b> ${d?esc(uname(d.conferido_por)):'-'}</b></div><div><small>Conferido em</small><b> ${d?esc(dt(d.conferido_em||d.criado_em)):'-'}</b></div><div class="v770-carga-status ${x.level}">${esc(x.text)}</div>`}
function render(){checker();annotate();detail()}
function bind(){if(bound)return;bound=true;document.addEventListener('click',e=>{if(e.target.closest('[data-carga-tipo]'))setTimeout(()=>{window.MaterialCarga783?.reload?.();load()},80);if(e.target.closest('#cargaRefList [data-carga-ref]'))setTimeout(render,0)},true);window.addEventListener('focus',()=>{window.MaterialCarga783?.reload?.();load()});document.addEventListener('visibilitychange',()=>{if(!document.hidden){window.MaterialCarga783?.reload?.();load()}})}
function start(){try{user=JSON.parse(localStorage.getItem('usuarioLogado')||'null')}catch(_){user=null}css();bind();load();if(new URLSearchParams(location.search).get('modulo')==='material_carga')window.MaterialCarga783?.reload?.();setInterval(()=>{if(new URLSearchParams(location.search).get('modulo')==='material_carga')load()},60000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();