package br.com.guerravpn.crediflow

import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.text.KeyboardOptions
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.input.KeyboardType
import androidx.compose.ui.text.input.PasswordVisualTransformation
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import kotlinx.coroutines.launch
import java.text.NumberFormat
import java.util.Locale

private val Bg=Color(0xFF07101E);private val Panel=Color(0xFF0E1A2D);private val Panel2=Color(0xFF13233B);private val Blue=Color(0xFF61A8FF);private val Mint=Color(0xFF5CE0B8);private val Muted=Color(0xFF93A7C3);private val Danger=Color(0xFFFF6B7B);private val Warning=Color(0xFFFFCC66)
private enum class Screen{WELCOME,REGISTER,ANALYSIS,ACTIVATE,CREATE_PASSWORD,LOGIN,HOME,LOAN_DRAFT,ADMIN,ADMIN_DETAIL}

class MainActivity:ComponentActivity(){override fun onCreate(savedInstanceState:Bundle?){super.onCreate(savedInstanceState);setContent{MaterialTheme(colorScheme=darkColorScheme(primary=Blue,secondary=Mint,background=Bg,surface=Panel,surfaceVariant=Panel2,onPrimary=Bg,onBackground=Color(0xFFF0F6FF),onSurface=Color(0xFFF0F6FF))){CrediFlowApp()}}}}

@Composable private fun CrediFlowApp(){
    val context=androidx.compose.ui.platform.LocalContext.current;val store=remember{SessionStore(context)}
    var session by remember{mutableStateOf(store.session())};var selected by remember{mutableStateOf<AdminApplication?>(null)}
    var screen by remember{mutableStateOf(when{session?.role=="admin"->Screen.ADMIN;session!=null&&session?.activationRequired==false->Screen.HOME;session!=null->Screen.CREATE_PASSWORD;store.pendingApplication()!=null->Screen.ANALYSIS;else->Screen.WELCOME})}
    Surface(Modifier.fillMaxSize(),color=Bg){when(screen){
        Screen.WELCOME->WelcomeScreen(store.pendingApplication()!=null,{screen=Screen.REGISTER},{screen=Screen.LOGIN},{screen=Screen.ANALYSIS})
        Screen.REGISTER->RegisterScreen({screen=Screen.WELCOME}){id,secret,email->store.savePendingApplication(id,secret,email);screen=Screen.ANALYSIS}
        Screen.ANALYSIS->AnalysisScreen(store.pendingApplication(),{screen=Screen.WELCOME},{screen=Screen.ACTIVATE})
        Screen.ACTIVATE->ActivationScreen(store.pendingApplication()?.third?:"",{screen=Screen.ANALYSIS}){s->store.saveSession(s);session=s;screen=Screen.CREATE_PASSWORD}
        Screen.CREATE_PASSWORD->PasswordScreen(session,{s->store.saveSession(s);store.clearPendingApplication();session=s;screen=if(s.role=="admin")Screen.ADMIN else Screen.HOME},{store.clearSession();session=null;screen=Screen.WELCOME})
        Screen.LOGIN->LoginScreen({screen=Screen.WELCOME}){s->store.saveSession(s);session=s;screen=when{ s.role=="admin"->Screen.ADMIN;s.activationRequired->Screen.CREATE_PASSWORD;else->Screen.HOME}}
        Screen.HOME->HomeScreen(session,{screen=Screen.LOAN_DRAFT},{store.clearSession();session=null;screen=Screen.WELCOME})
        Screen.LOAN_DRAFT->LoanDraftScreen(session){screen=Screen.HOME}
        Screen.ADMIN->AdminScreen(session,{selected=it;screen=Screen.ADMIN_DETAIL},{store.clearSession();session=null;screen=Screen.WELCOME})
        Screen.ADMIN_DETAIL->AdminDetailScreen(session,selected,{screen=Screen.ADMIN}){screen=Screen.ADMIN}
    }}
}

@Composable private fun WelcomeScreen(hasAnalysis:Boolean,onRegister:()->Unit,onLogin:()->Unit,onAnalysis:()->Unit){Column(Modifier.fillMaxSize().padding(22.dp),verticalArrangement=Arrangement.Center){Box(Modifier.size(68.dp).background(Blue,RoundedCornerShape(20.dp)),contentAlignment=Alignment.Center){Text("C",color=Bg,fontSize=34.sp,fontWeight=FontWeight.Black)};Spacer(Modifier.height(24.dp));Text("CREDIFLOW · v0.1 build 1",fontSize=11.sp,color=Muted,fontWeight=FontWeight.Bold);Text("Crédito com clareza do início ao fim.",fontSize=34.sp,lineHeight=38.sp,fontWeight=FontWeight.Black);Spacer(Modifier.height(28.dp));Primary("Criar cadastro",onRegister);Spacer(Modifier.height(10.dp));Secondary("Entrar na minha conta",onLogin);if(hasAnalysis){TextButton(onClick=onAnalysis,modifier=Modifier.fillMaxWidth()){Text("Acompanhar minha análise")}};Spacer(Modifier.height(16.dp));Text("Open Finance e transferências Pix reais dependem da conexão com um provedor financeiro autorizado.",color=Muted,fontSize=12.sp,lineHeight=17.sp)}}

@Composable private fun RegisterScreen(onBack:()->Unit,onCreated:(String,String,String)->Unit){
    val scope=rememberCoroutineScope();var loading by remember{mutableStateOf(false)};var error by remember{mutableStateOf<String?>(null)}
    var name by remember{mutableStateOf("")};var email by remember{mutableStateOf("")};var cpf by remember{mutableStateOf("")};var phone by remember{mutableStateOf("")};var birth by remember{mutableStateOf("")};var street by remember{mutableStateOf("")};var number by remember{mutableStateOf("")};var complement by remember{mutableStateOf("")};var neighborhood by remember{mutableStateOf("")};var city by remember{mutableStateOf("")};var state by remember{mutableStateOf("RS")};var cep by remember{mutableStateOf("")};var occupation by remember{mutableStateOf("")};var income by remember{mutableStateOf("")};var consent by remember{mutableStateOf(false)}
    Page("Seu cadastro","Preencha os dados para iniciar a análise.",onBack){
        Info("Fluxo","Cadastro → Open Finance → Análise manual → Aprovação → Código por e-mail → Senha.")
        Field("Nome completo",name){name=it};Field("E-mail",email,KeyboardType.Email){email=it};Field("CPF",cpf,KeyboardType.Number){cpf=it};Field("Celular",phone,KeyboardType.Phone){phone=it};Field("Data de nascimento (AAAA-MM-DD)",birth){birth=it};Section("Endereço");Field("Rua / avenida",street){street=it};Field("Número",number){number=it};Field("Complemento",complement){complement=it};Field("Bairro",neighborhood){neighborhood=it};Field("Cidade",city){city=it};Field("UF",state){state=it.uppercase().take(2)};Field("CEP",cep,KeyboardType.Number){cep=it};Section("Dados financeiros");Field("Profissão / ocupação",occupation){occupation=it};Field("Renda mensal aproximada",income,KeyboardType.Decimal){income=it}
        Row(verticalAlignment=Alignment.CenterVertically){Checkbox(consent,{consent=it});Text("Confirmo que os dados são verdadeiros e concordo com o uso deles para cadastro e análise, conforme os termos e a política de privacidade.",fontSize=12.sp,color=Muted)}
        error?.let{ErrorBox(it)}
        Button(enabled=!loading&&consent,onClick={
            if(listOf(name,email,cpf,phone,birth,street,number,neighborhood,city,state,cep).any{it.isBlank()}){error="Preencha os campos obrigatórios."}else{
                val inc=income.replace(",",".").toDoubleOrNull();if(inc==null||inc<0){error="Informe uma renda válida."}else{loading=true;error=null;scope.launch{try{val r=SupabaseApi.submitApplication(name.trim(),email.trim(),cpf,phone,birth.trim(),street.trim(),number.trim(),complement.trim(),neighborhood.trim(),city.trim(),state.trim(),cep,occupation.trim(),inc);onCreated(r.first,r.second,email.trim())}catch(e:Exception){error=friendly(e)}finally{loading=false}}}
            }
        },modifier=Modifier.fillMaxWidth().height(52.dp)){Text(if(loading)"Enviando..." else "Enviar cadastro")}
    }
}

@Composable private fun AnalysisScreen(pending:Triple<String,String,String>?,onBack:()->Unit,onActivation:()->Unit){val scope=rememberCoroutineScope();var st by remember{mutableStateOf<ApplicationStatus?>(null)};var loading by remember{mutableStateOf(false)};var error by remember{mutableStateOf<String?>(null)};fun refresh(){if(pending==null)return;loading=true;scope.launch{try{st=SupabaseApi.checkApplication(pending.first,pending.second);error=null}catch(e:Exception){error=friendly(e)}finally{loading=false}}};LaunchedEffect(pending?.first){refresh()};Page("Análise",pending?.third?:"Sua solicitação",onBack){if(pending==null){ErrorBox("Não há solicitação salva neste aparelho.");return@Page};Step("1","Cadastro","Concluído",Mint);Step("2","Open Finance",if(st?.openFinanceStatus=="connected")"Conectado" else "Aguardando provedor",if(st?.openFinanceStatus=="connected")Mint else Warning);Step("3","Análise manual",when(st?.status){"approved","activation_sent","active"->"Aprovado";"rejected"->"Não aprovado";else->"Aguardando"},when(st?.status){"approved","activation_sent","active"->Mint;"rejected"->Danger;else->Warning});Step("4","Ativação",when(st?.status){"activation_sent"->"Código enviado";"active"->"Ativa";else->"Pendente"},if(st?.status=="active")Mint else Muted);when(st?.status){"approved"->Info("Aprovado","Seu limite foi aprovado. Aguarde o envio do código de acesso.");"activation_sent"->{Success("Código enviado","Confira seu e-mail e digite o código de 6 dígitos.");st?.approvedLimit?.let{Info("Limite aprovado",brl(it))};Primary("Inserir código de acesso",onActivation)};"active"->Success("Conta ativa","Sua conta já foi ativada.");"rejected"->ErrorBox("A solicitação não foi aprovada.");else->Info("Open Finance pendente","A conexão real será habilitada quando configurarmos o provedor. O painel Admin já recebe o cadastro.")};error?.let{ErrorBox(it)};Secondary(if(loading)"Atualizando..." else "Atualizar status"){if(!loading)refresh()}}}

@Composable private fun ActivationScreen(email:String,onBack:()->Unit,onVerified:(Session)->Unit){val scope=rememberCoroutineScope();var code by remember{mutableStateOf("")};var loading by remember{mutableStateOf(false)};var error by remember{mutableStateOf<String?>(null)};Page("Código de acesso",email,onBack){Info("Aprovação concluída","Digite o código de 6 dígitos enviado ao e-mail.");Field("Código",code,KeyboardType.Number){code=it.filter(Char::isDigit).take(6)};error?.let{ErrorBox(it)};Button(enabled=code.length==6&&!loading,onClick={loading=true;scope.launch{try{onVerified(SupabaseApi.verifyEmailOtp(email,code))}catch(e:Exception){error=friendly(e)}finally{loading=false}}},modifier=Modifier.fillMaxWidth()){Text(if(loading)"Validando..." else "Validar código")}}}

@Composable private fun PasswordScreen(session:Session?,onDone:(Session)->Unit,onLogout:()->Unit){val scope=rememberCoroutineScope();var pass by remember{mutableStateOf("")};var confirm by remember{mutableStateOf("")};var loading by remember{mutableStateOf(false)};var error by remember{mutableStateOf<String?>(null)};Page("Crie sua senha",session?.email?:"",null){Info("Última etapa","Ao concluir, a conta abre com o limite aprovado no Admin.");PassField("Senha",pass){pass=it};PassField("Confirmar senha",confirm){confirm=it};error?.let{ErrorBox(it)};Button(enabled=!loading&&pass.length>=8&&pass==confirm&&session!=null,onClick={val s=session?:return@Button;loading=true;scope.launch{try{SupabaseApi.setPassword(s.accessToken,pass);SupabaseApi.completeActivation(s.accessToken);val r=if(s.refreshToken.isNotBlank())SupabaseApi.refreshSession(s.refreshToken) else s.copy(activationRequired=false);onDone(r)}catch(e:Exception){error=friendly(e)}finally{loading=false}}},modifier=Modifier.fillMaxWidth()){Text(if(loading)"Ativando..." else "Criar senha e entrar")};TextButton(onClick=onLogout,modifier=Modifier.fillMaxWidth()){Text("Cancelar")}}}

@Composable private fun LoginScreen(onBack:()->Unit,onLogin:(Session)->Unit){val scope=rememberCoroutineScope();var email by remember{mutableStateOf("")};var pass by remember{mutableStateOf("")};var loading by remember{mutableStateOf(false)};var error by remember{mutableStateOf<String?>(null)};Page("Entrar","Cliente ou administrador",onBack){Field("E-mail",email,KeyboardType.Email){email=it};PassField("Senha",pass){pass=it};error?.let{ErrorBox(it)};Primary(if(loading)"Entrando..." else "Entrar"){if(!loading){loading=true;scope.launch{try{onLogin(SupabaseApi.signIn(email,pass))}catch(e:Exception){error=friendly(e)}finally{loading=false}}}};Text("O login identifica automaticamente o perfil cliente ou administrador.",color=Muted,fontSize=12.sp)}}

@Composable private fun HomeScreen(session:Session?,onLoan:()->Unit,onLogout:()->Unit){val scope=rememberCoroutineScope();var home by remember{mutableStateOf<ClientHome?>(null)};var loading by remember{mutableStateOf(true)};var error by remember{mutableStateOf<String?>(null)};fun load(){val token=session?.accessToken?:return;loading=true;scope.launch{try{home=SupabaseApi.loadClientHome(token);error=null}catch(e:Exception){error=friendly(e)}finally{loading=false}}};LaunchedEffect(session?.accessToken){load()};Page("Olá, ${home?.fullName?.substringBefore(" ")?:"cliente"}","Sua conta CrediFlow",null){if(loading&&home==null)CircularProgressIndicator() else home?.let{h->val av=(h.limitAmount-h.usedLimit).coerceAtLeast(0.0);Card(colors=CardDefaults.cardColors(containerColor=Panel2),modifier=Modifier.fillMaxWidth()){Column(Modifier.padding(18.dp)){Text("Limite disponível",color=Muted,fontSize=12.sp);Text(brl(av),fontSize=34.sp,fontWeight=FontWeight.Black);Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Text("Total ${brl(h.limitAmount)}",color=Muted,fontSize=12.sp);Text("Em uso ${brl(h.usedLimit)}",color=Muted,fontSize=12.sp)}}};Spacer(Modifier.height(12.dp));Primary("Solicitar crédito",onLoan);Section("Condições atuais");Two("Parcelamento","até ${h.maxInstallments}x","Taxa",h.monthlyRate?.let{"${pct(it*100)}% a.m."}?:"—");Section("Empréstimos");if(h.loans.isEmpty())Info("Nenhum empréstimo ativo","Operações aparecerão aqui depois da integração financeira.") else h.loans.forEach{Info(brl(it.principal),"${it.installments}x · ${it.status}")}};error?.let{ErrorBox(it)};Secondary("Atualizar"){load()};TextButton(onClick=onLogout,modifier=Modifier.fillMaxWidth()){Text("Sair da conta")}}}

@Composable private fun LoanDraftScreen(session:Session?,onBack:()->Unit){var home by remember{mutableStateOf<ClientHome?>(null)};var amount by remember{mutableStateOf("")};var inst by remember{mutableIntStateOf(1)};var pixType by remember{mutableStateOf("CPF")};var pix by remember{mutableStateOf("")};var pending by remember{mutableStateOf(false)};LaunchedEffect(session?.accessToken){session?.accessToken?.let{try{home=SupabaseApi.loadClientHome(it)}catch(_:Exception){}}};Page("Solicitar crédito","Monte sua proposta",onBack){val h=home;val av=((h?.limitAmount?:0.0)-(h?.usedLimit?:0.0)).coerceAtLeast(0.0);Info("Disponível",brl(av));Field("Valor desejado",amount,KeyboardType.Decimal){amount=it};Section("Parcelas permitidas");Row(horizontalArrangement=Arrangement.spacedBy(7.dp)){(1..(h?.maxInstallments?.coerceAtMost(5)?:1)).forEach{n->FilterChip(selected=inst==n,onClick={inst=n},label={Text("${n}x")})}};Section("Chave Pix para receber");Row(horizontalArrangement=Arrangement.spacedBy(5.dp)){listOf("CPF","Celular","E-mail").forEach{t->FilterChip(selected=pixType==t,onClick={pixType=t},label={Text(t,fontSize=10.sp)})}};Field("Chave Pix",pix){pix=it};val principal=amount.replace(",",".").toDoubleOrNull()?:0.0;val rate=h?.monthlyRate?:0.0;if(principal>0)Info("Resumo demonstrativo","${inst}x · total estimado ${brl(principal*(1+rate*inst))}. O contrato definitivo exibirá CET e condições antes da assinatura.");Button(enabled=principal>0&&principal<=av&&pix.isNotBlank(),onClick={pending=true},modifier=Modifier.fillMaxWidth()){Text("Continuar")};if(pending)Info("Integração financeira pendente","A proposta foi montada, mas esta build não envia dinheiro nem cria cobrança real. Falta conectar o parceiro Pix/BaaS/Open Finance.")}}

@Composable private fun AdminScreen(session:Session?,onSelect:(AdminApplication)->Unit,onLogout:()->Unit){val scope=rememberCoroutineScope();var apps by remember{mutableStateOf<List<AdminApplication>>(emptyList())};var loading by remember{mutableStateOf(true)};var error by remember{mutableStateOf<String?>(null)};fun load(){val t=session?.accessToken?:return;loading=true;scope.launch{try{apps=SupabaseApi.listApplications(t);error=null}catch(e:Exception){error=friendly(e)}finally{loading=false}}};LaunchedEffect(session?.accessToken){load()};Page("Painel Admin","${apps.size} cadastro(s)",null){Info("Análise manual","O painel exibe os dados. Limite, juros e parcelas são informados por você; o app não decide automaticamente.");if(loading)LinearProgressIndicator(modifier=Modifier.fillMaxWidth());error?.let{ErrorBox(it)};if(!loading&&apps.isEmpty())Info("Sem solicitações","Novos cadastros aparecerão aqui.");apps.forEach{a->Card(onClick={onSelect(a)},colors=CardDefaults.cardColors(containerColor=Panel),modifier=Modifier.fillMaxWidth()){Column(Modifier.padding(15.dp)){Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Text(a.fullName,fontWeight=FontWeight.Bold);Pill(a.status)};Text(a.email,color=Muted,fontSize=12.sp);Text("Open Finance: ${a.openFinanceStatus}",color=if(a.openFinanceStatus=="connected")Mint else Warning,fontSize=12.sp)}};Spacer(Modifier.height(8.dp))};Secondary("Atualizar lista"){load()};TextButton(onClick=onLogout,modifier=Modifier.fillMaxWidth()){Text("Sair do Admin")}}}

@Composable private fun AdminDetailScreen(session:Session?,app:AdminApplication?,onBack:()->Unit,onUpdated:()->Unit){val scope=rememberCoroutineScope();var limit by remember{mutableStateOf(app?.approvedLimit?.toString()?:"50")};var tier by remember{mutableStateOf(app?.approvedRiskTier?:"novo")};var rate by remember{mutableStateOf(app?.approvedMonthlyRate?.let{(it*100).toString()}?:"4")};var inst by remember{mutableStateOf(app?.approvedMaxInstallments?.toString()?:"1")};var notes by remember{mutableStateOf("")};var loading by remember{mutableStateOf(false)};var msg by remember{mutableStateOf<String?>(null)};var err by remember{mutableStateOf(false)};Page("Análise do cliente",app?.fullName?:"Cadastro",onBack){val a=app;val token=session?.accessToken;if(a==null||token==null){ErrorBox("Cadastro ou sessão Admin indisponível.");return@Page};Two("CPF",maskCpf(a.cpf),"Nascimento",a.birthDate);Two("Cidade","${a.city}/${a.state}","Renda",a.monthlyIncome?.let(::brl)?:"—");Two("Ocupação",a.occupation.ifBlank{"—"},"Open Finance",a.openFinanceStatus);if(a.openFinanceStatus!="connected")Info("Atenção","Open Finance ainda não conectado. Aprovação nesta build deve ser usada somente para teste até configurar o provedor real.");Section("Decisão manual");Field("Limite aprovado (R$)",limit,KeyboardType.Decimal){limit=it};Field("Faixa interna",tier){tier=it};Field("Juros mensais (%)",rate,KeyboardType.Decimal){rate=it};Field("Máximo de parcelas",inst,KeyboardType.Number){inst=it};Field("Observações",notes){notes=it};msg?.let{if(err)ErrorBox(it)else Success("Concluído",it)};Button(enabled=!loading,onClick={val l=limit.replace(",",".").toDoubleOrNull();val r=rate.replace(",",".").toDoubleOrNull();val n=inst.toIntOrNull();if(l==null||l<=0||r==null||r<0||n==null||n<1){msg="Revise limite, juros e parcelas.";err=true}else{loading=true;scope.launch{try{SupabaseApi.recordReview(token,a.id,"approved",l,tier,r/100,n,notes);msg="Cadastro aprovado. Agora envie o código de acesso.";err=false}catch(e:Exception){msg=friendly(e);err=true}finally{loading=false}}}},modifier=Modifier.fillMaxWidth()){Text(if(loading)"Salvando..." else "Aprovar condições")};OutlinedButton(enabled=!loading,onClick={loading=true;scope.launch{try{SupabaseApi.sendActivation(token,a.id);msg="Código solicitado ao serviço de e-mail.";err=false}catch(e:Exception){msg=friendly(e);err=true}finally{loading=false}}},modifier=Modifier.fillMaxWidth()){Text("Enviar código de acesso")};TextButton(enabled=!loading,onClick={loading=true;scope.launch{try{SupabaseApi.recordReview(token,a.id,"rejected",null,null,null,null,notes);onUpdated()}catch(e:Exception){msg=friendly(e);err=true}finally{loading=false}}},modifier=Modifier.fillMaxWidth()){Text("Não aprovar",color=Danger)}}}

@Composable private fun Page(title:String,subtitle:String,onBack:(()->Unit)?,content:@Composable ColumnScope.()->Unit){Column(Modifier.fillMaxSize().verticalScroll(rememberScrollState()).padding(18.dp)){if(onBack!=null){TextButton(onClick=onBack,contentPadding=PaddingValues(0.dp)){Text("← Voltar")}};Text(title,fontSize=28.sp,fontWeight=FontWeight.Black);if(subtitle.isNotBlank())Text(subtitle,color=Muted,fontSize=13.sp);Spacer(Modifier.height(18.dp));content();Spacer(Modifier.height(25.dp));Text("CrediFlow · v0.1 build 1",color=Muted,fontSize=10.sp)}}
@Composable private fun Field(label:String,value:String,type:KeyboardType=KeyboardType.Text,onChange:(String)->Unit){OutlinedTextField(value,onChange,label={Text(label)},keyboardOptions=KeyboardOptions(keyboardType=type),singleLine=true,modifier=Modifier.fillMaxWidth().padding(bottom=8.dp))}
@Composable private fun PassField(label:String,value:String,onChange:(String)->Unit){OutlinedTextField(value,onChange,label={Text(label)},visualTransformation=PasswordVisualTransformation(),singleLine=true,modifier=Modifier.fillMaxWidth().padding(bottom=8.dp))}
@Composable private fun Primary(label:String,onClick:()->Unit){Button(onClick=onClick,modifier=Modifier.fillMaxWidth().height(50.dp)){Text(label,fontWeight=FontWeight.Bold)}}
@Composable private fun Secondary(label:String,onClick:()->Unit){OutlinedButton(onClick=onClick,modifier=Modifier.fillMaxWidth().height(48.dp)){Text(label)}}
@Composable private fun Section(s:String){Text(s,fontSize=17.sp,fontWeight=FontWeight.Bold,modifier=Modifier.padding(top=12.dp,bottom=8.dp))}
@Composable private fun Info(t:String,b:String){Card(colors=CardDefaults.cardColors(containerColor=Panel),modifier=Modifier.fillMaxWidth().padding(bottom=10.dp)){Column(Modifier.padding(14.dp)){Text(t,fontWeight=FontWeight.Bold);Text(b,color=Muted,fontSize=12.sp,lineHeight=17.sp)}}}
@Composable private fun Success(t:String,b:String){Card(colors=CardDefaults.cardColors(containerColor=Color(0xFF0E2A28)),modifier=Modifier.fillMaxWidth().padding(bottom=10.dp)){Column(Modifier.padding(14.dp)){Text(t,fontWeight=FontWeight.Bold,color=Mint);Text(b,color=Color(0xFFCDEFE6),fontSize=12.sp)}}}
@Composable private fun ErrorBox(b:String){Card(colors=CardDefaults.cardColors(containerColor=Color(0xFF311820)),modifier=Modifier.fillMaxWidth().padding(bottom=10.dp)){Text(b,color=Color(0xFFFFB7C0),modifier=Modifier.padding(14.dp),fontSize=12.sp)}}
@Composable private fun Step(n:String,t:String,s:String,c:Color){Row(Modifier.fillMaxWidth().padding(vertical=7.dp),verticalAlignment=Alignment.CenterVertically){Box(Modifier.size(34.dp).background(c.copy(alpha=.18f),RoundedCornerShape(11.dp)),contentAlignment=Alignment.Center){Text(n,color=c,fontWeight=FontWeight.Black)};Spacer(Modifier.width(12.dp));Column{Text(t,fontWeight=FontWeight.SemiBold);Text(s,color=c,fontSize=12.sp)}}}
@Composable private fun Two(t1:String,v1:String,t2:String,v2:String){Row(Modifier.fillMaxWidth().padding(bottom=8.dp),horizontalArrangement=Arrangement.spacedBy(8.dp)){listOf(t1 to v1,t2 to v2).forEach{(t,v)->Card(colors=CardDefaults.cardColors(containerColor=Panel),modifier=Modifier.weight(1f)){Column(Modifier.padding(12.dp)){Text(t,color=Muted,fontSize=10.sp);Text(v,fontWeight=FontWeight.Bold,fontSize=13.sp)}}}}}
@Composable private fun Pill(s:String){val c=when(s){"approved","activation_sent","active"->Mint;"rejected"->Danger;else->Warning};Surface(color=c.copy(alpha=.14f),shape=RoundedCornerShape(99.dp)){Text(s,color=c,fontSize=10.sp,modifier=Modifier.padding(horizontal=9.dp,vertical=5.dp))}}
private fun brl(v:Double)=NumberFormat.getCurrencyInstance(Locale("pt","BR")).format(v)
private fun pct(v:Double)=String.format(Locale.US,"%.2f",v).replace(".",",")
private fun maskCpf(c:String):String{val d=c.filter(Char::isDigit);return if(d.length==11)"***.${d.substring(3,6)}.${d.substring(6,9)}-**" else c}
private fun friendly(e:Exception):String{val r=e.message?:"Erro inesperado";return when{r.contains("application_already_exists",true)->"Já existe um cadastro em análise para este CPF.";r.contains("invalid_email",true)->"E-mail inválido.";r.contains("minimum_age_18",true)->"O cadastro exige idade mínima de 18 anos.";r.contains("invalid_cpf",true)->"CPF inválido.";r.contains("invalid_credentials",true)||r.contains("Invalid login",true)->"E-mail ou senha incorretos.";r.contains("Email address not authorized",true)->"O SMTP ainda não está configurado para clientes externos.";r.contains("otp_send_failed",true)->"Não foi possível enviar o código. Verifique o SMTP do Supabase.";else->r.replace("_"," ")}}
