name: tmp-patch-sha
on:
  push:
    branches: [app/releases]
jobs:
  hash:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Hash patch
        run: sha256sum patches/TAREFAS-2.4.1.10.tpatch
